### ISSUE TITLE
LiquidBlock doesn't use Supplier in shouldSpreadLiquid

### ISSUE THREAD

**Issue by rehwinkel** [MinecraftForge/MinecraftForge#8002] opened 2021-08-13 09:27 UTC
**Minecraft Version:** 1.17.1
**Forge Version:** 37.0.33
**Logs:** https://gist.github.com/rehwinkel/9b62e91ab2926fb7847cdd7ee08c1307

**Steps to Reproduce:**
 1. Create a Fluid and a LiquidBlock referencing that Fluid using the Supplier-Constructor.
 2. Place Fluid in World using Bucket
 3. Error appears in Console, Fluid is briefly placed, then disappears.

**Description of issue:**
This issue is due to the Supplier-Constructor of LiquidBlock setting `this.fluid = null;`, which causes an NPE in `shouldSpreadLiquid` because that method uses `this.fluid` instead of `this.getFluid()`.

**Comment by rehwinkel** [comment] 2021-08-13 10:11
Fixed by Fluid Overhaul PR: #7992

**Comment by remplerus** [comment] 2021-08-13 11:10
same request as #7922

**Comment by AterAnimAvis** [comment] 2021-09-22 17:22
Closing as duplicate of #7922

**Closed as completed by AterAnimAvis** 2021-09-22 17:22 UTC
Labels: Bug, Fluids, 1.17
