### ISSUE TITLE
Furnace minecart speed increased when using Forge

### ISSUE THREAD

**Issue by addmix** [MinecraftForge/MinecraftForge#7658] opened 2021-02-12 05:14 UTC
**Minecraft Version:** {Minecraft version}
1.16.4
**Forge Version:** {Forge version. *Version number, not latest/rb*}
35.1.5
**Steps to Reproduce:**
Compare furnace minecart speed in vanilla to forge.

**Description of issue:**
furnace minecart runs much faster when using forge, compared to vanilla.

**Comment by JoJoDeveloping** [comment] 2021-04-29 23:00
I can not reproduce this. I ran the powered minecart on an identical loop in vanilla Minecraft, forge dev and forge-dev-clean (which is decompiled but without forge's patches). This is the loop (12x6):
![2021-04-30_00 58 52](https://user-images.githubusercontent.com/7198985/116628402-5647f900-a94f-11eb-935f-1c7949754d85.png)

The minecarts took 38.41s in vanilla, 38.57 in forge, and 38.51 in forge-clean.

I did use Minecraft 1.16.5 and Forge latest, though.

**Comment by Cyborgmas** [comment] 2021-04-29 23:07
Perhaps it is becaused the linked PR was merged but the issue was not closed :p

**Comment by TheCurle** [comment] 2021-04-29 23:07
Indeed. This should have been closed ages ago.

**Closed as completed by TheCurle** 2021-04-29 23:07 UTC
