### ISSUE TITLE
World Edit Commands in /execute

### ISSUE THREAD

**Issue by Correlander** [MinecraftForge/MinecraftForge#9739] opened 2023-10-06 08:38 UTC
**Minecraft Version:** {Minecraft version}
1.19.2
**Forge Version:** {Forge version. *Version number, not latest/rb*}
43.3.2
**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}
[latest.log](https://github.com/MinecraftForge/MinecraftForge/files/12828764/latest.log)
**Steps to Reproduce:**
 1. Turn on MC with forge 43.3.2, and world edit 7.2.12 installed.
 2. Run "/execute as @s run /copy" or just any world edit command through /execute

**Description of issue:**
Nothing happens when you run a world edit command through /execute. It won't error, but it won't work either. I'm reporting it here because a world edit dev said it's likely a forge/minecraft bug.

**Comment by LexManos** [comment] 2023-10-07 04:04
You can try and get people to help you with figuring out the root cause of this issue on our [discord](http://discord.minecraftforge.net/) But closing here as 
1) We're on 1.20.2
2) executing normal vanilla commands as other users works fine so its most likely a mod issue not us.
It would all depend on how he registers his commands. See if you or someone else can find the root issue on our discord.

**Closed as completed by LexManos** 2023-10-07 04:04 UTC
