### ISSUE TITLE
Forge causes a crash when running Minecraft on Wayland (Linux) natively.

### ISSUE THREAD

**Issue by m00nwtchr** [MinecraftForge/MinecraftForge#10062] opened 2024-08-11 12:42 UTC
**Minecraft Version:** 1.20.1

**Forge Version:** 47.3.0

**Logs:** https://gist.github.com/m00nwtchr/40f413edf341ccf57bda2717c8837b51

**Steps to Reproduce:**
 1. Make a brand new installation of Forge on Linux, with a Desktop Environment such as KDE in Wayland mode, or sway
 2. Launch Minecraft with `-Dorg.lwjgl.glfw.libname=/usr/lib/libglfw.so` (or the equivalent GUI toggle using PrismLauncher)
 3. Crash

**Description of issue:**
Minecraft ships with a version of GLFW that doesn't support the [Wayland](https://en.wikipedia.org/wiki/Wayland_(protocol)) protocol, which means that in Linux desktop environments using it, it runs in the XWayland "translation layer", which in many cases cripples performance and causes visual glitches. The solution to that is to replace the GLFW library with the system installation, which launcher like PrismLauncher expose as an easy switch. 

However, when running with Forge, the above `Wayland: The platform does not provide the window position` error appears. That is not the case with either Vanilla Minecraft or other modloaders, such as Fabric. 

Searching around gave me `-Dfml.earlyprogresswindow=false` as a possible fix, but that doesn't seem to do anything anymore, even with the GLFW replacement disabled.

**Comment by Jonathing** [comment] 2024-08-11 14:02
Pretty much all video games run under XWayland because Proton also runs under XWayland (see ValveSoftware/Proton#4638). If you are experiencing performance issues with XWayland applications, that may be due to system configuration or environment issues.

In my opinion, it is unrealistic to expect Forge to support a version of the library that Minecraft does not ship with. HOWEVER, to give benefit of doubt, I believe that this issue is caused by the early loading screen, so I will leave this issue open for potential discussion. If you are able to, please try disabling the early loading window within FML's config file.

**Comment by m00nwtchr** [comment] 2024-08-11 16:10
> Pretty much all video games run under XWayland because Proton also runs under XWayland (see ValveSoftware/Proton#4638). If you are experiencing performance issues with XWayland applications, that may be due to system configuration or environment issues.
> 

Not video games which are available as native Linux binaries (if they have recent versions of graphics libraries etc.). And yes, the reason why XWayland performs poorly for me is because of NVIDIA driver issues, but I can't really do anything about that. (Some compositors do implement fixes/workarounds which make it better, but those can also be a pain to get working)

> In my opinion, it is unrealistic to expect Forge to support a version of the library that Minecraft does not ship with.

Minecraft doesn't ship with it, but it does run completely fine with it. And Forge would have to make changes to support Wayland anyway, if Mojang updated GLFW upstream.

> If you are able to, please try disabling the early loading window within FML's config file.

That changes the error to `Wayland: The platform does not support setting the window icon`. (This can be resolved by installing a patched version of GLFW, glfw/glfw#2510, but that's a hack)

**Comment by LexManos** [comment] 2024-08-11 17:22
Forge doesn't support environments which the vanilla game doesn't directly support. So I don't really care about this too much.

However like Jonathing said, it's probably the early loading screen because it's notorious for being annoying with graphic drivers, so your best bet is to try disabling it. If that doesn't work then you may have to put on your developer hat and try tracking it down as I have no way of testing/debugging this issue.

Edit: I now see your edit that disabling the early loading screen does solve that issue. And you have another issue after it. But looking more into it, it seems that the issue is that your glfw version doesn't support some behaviors exposed by glfw. Which seems like an issue and they chose to hard crash instead of warning. So I'm inclined to think they expect that behavior.

As for what can be done on our end. Would need to figure out where that window icon is changed and see if disabling it fixes your issue. Tho I'm unsure why it would need to change the icon of the window if there isn't already a window... this is where I would need a way to debug this comes in. Which I don't have a way as I don't have a computer setup with Wayland.

**Comment by Jonathing** [comment] 2024-08-11 17:41
Since the early loading screen will eventually need to be refactored to account for native Wayland support in a future version of Minecraft, I'll keep this issue open.

However, I still think it's worth looking into your hardware configuration to solve this issue with XWayland. I have a friend running Nobara Linux 40 (KDE Plasma) using the NVIDIA image and he has no problems running any XWayland applications.

**Comment by LexManos** [comment] 2024-08-11 18:29
Looking more into it, The only place that the window icon is set, is here:
```java
    public void setIcon(PackResources p_281860_, IconSet p_282155_) throws IOException {
        int i = GLFW.glfwGetPlatform();
        switch (i) {
            case GLFW_PLATFORM_WIN32:
            case GLFW_PLATFORM_X11:
                    //Snip
                    GLFW.glfwSetWindowIcon(this.window, buffer.position(0));
                    break;
            case GLFW_PLATFORM_COCOA:
                MacosUtil.loadIcon(p_282155_.getMacIcon(p_281860_));
            case GLFW_PLATFORM_WAYLAND:
            case GLFW_PLATFORM_NULL:
                break;
            default:
                LOGGER.warn("Not setting icon for unrecognized platform: {}", i);
        }
    }
``` 

Which explicitly doesn't set the window icon if it's GLFW_PLATFORM_WAYLAND, And this is vanilla code. So I am really confused on when this error happens.

**Comment by m00nwtchr** [comment] 2024-08-11 18:33
> However, I still think it's worth looking into your hardware configuration to solve this issue with XWayland. I have a friend running Nobara Linux 40 (KDE Plasma) using the NVIDIA image and he has no problems running any XWayland applications.

IIRC That's because sway doesn't yet support the latest NVIDIA driver features that were introduced recently, while KDE does.

RE: LexManos

I'll see if I can make a PR. One thing to note about the icon setting issue is that it seems to be present on 1.20.1 (didn't test 1.20.2+), but not 1.21.x.

I did stumble upon this code, which seems to be commented out in the later versions, but no idea if that could have anything to do with it: https://github.com/MinecraftForge/MinecraftForge/blob/1.20.1/fmlearlydisplay/src/main/java/net/minecraftforge/fml/earlydisplay/DisplayWindow.java#L455-L467 (I'm guessing this is a coincidence since this class shouldn't even be called while the earlyWindowControl config is false)

**Comment by LexManos** [comment] 2024-08-11 18:44
That would be the only other reference to that function in 1.20.1, which you're correct is not run at all if `earlyWindowControl=false`.

HOWEVER, on 1.20.1 the vanilla setIcon code was:
```java
   public void setIcon(PackResources p_281860_, IconSet p_282155_) throws IOException {
      RenderSystem.assertInInitPhase();
      if (Minecraft.ON_OSX) {
         MacosUtil.loadIcon(p_282155_.getMacIcon(p_281860_));
      } else {
          // snip
            GLFW.glfwSetWindowIcon(this.window, buffer.position(0));
      }
   }
   ```
   Which leads me to believe that somehow your 'vanilla' setup is tricking the game into thinking it's OSX, and thus not setting the window icon.
   
   And the platform is determined by this simple method:
   ```java
public static Util.OS getPlatform() {
      String s = System.getProperty("os.name").toLowerCase(Locale.ROOT);
      if (s.contains("win")) {
         return Util.OS.WINDOWS;
      } else if (s.contains("mac")) {
         return Util.OS.OSX;
      } else if (s.contains("solaris")) {
         return Util.OS.SOLARIS;
      } else if (s.contains("sunos")) {
         return Util.OS.SOLARIS;
      } else if (s.contains("linux")) {
         return Util.OS.LINUX;
      } else {
         return s.contains("unix") ? Util.OS.LINUX : Util.OS.UNKNOWN;
      }
   }
   ```
  So... what does your os.name system properly contain? Tho it shouldn't matter as we don't touch that function. But perhaps something in your setup is editing it on your 'working' launches but not on the Forge one.
  
  But ya knowing that this is only a 1.20.1 issue is a good place to start. As my goto is only to care about the latest as thats typically the workspace I have up.

**Comment by m00nwtchr** [comment] 2024-08-11 19:25
Hmm, launching Vanilla 1.20.1 without the "platform does not support setting the window icon" error earlier might have been a fluke or something, since I can't reproduce it now, so that's probably not related to forge, then. But it is fixed as early as 1.20.2, so that's fine.

**Comment by LexManos** [comment] 2024-08-11 19:36
Yup just checked the logs, 1.20.2 is when they changed that setIcon function.
So, the take away for us {Jonathing} is that if someone wanted to re-introduce the Forge icon on the early loading screen, we would have to make sure our function stays in sync with Vanilla's setIcon function.
But honestly I don't care about the icon so keeping it disabled is good enough for me.

As for the other issues you get when the early loading screen is running. If you feel like debugging it go for it. But honestly that thing is full of so much bad code that I don't care about it at all.

**Comment by Jonathing** [comment] 2024-08-11 21:02
@m00nwtchr Slightly off-topic, but I would strongly recommend pushing for Sway to get the new NVIDIA drivers underway, since XWayland performance issues are a lot more of a problem than just Minecraft or Forge. A lot of applications still are built on the legacy X11 protocols.

**Comment by lpaulino07** [comment] 2024-08-19 22:49
Minecraft does support Wayland rendering since 1.20.4 through both OpenJDK 17 and OpenJDK  21. As mentioned before, the issue is caused by Forge's loading screen, this can be avoided by disabling it through fml.toml.

**Comment by LexManos** [comment] 2024-08-20 02:25
Closing this:
Any version that vanilla supports it, Forge's loading screen supports it.
The check was added in 1.20.1 like I said, and the window title issue was removed [4 months ago](https://github.com/MinecraftForge/MinecraftForge/commit/e7a5c589075f73fef7daec3ebc1c4d4875f14c4e)
For any version other then that you can disable the early loading screen and then do whatever is needed for Vanilla to work.

**Closed as completed by LexManos** 2024-08-20 02:25 UTC
Labels: Bug, Rendering, Help Wanted

**Comment by lpaulino07** [comment] 2024-08-20 03:37
> Any version that vanilla supports it, Forge's loading screen supports it.

Unfortunately, that's not true. Vanilla Minecraft has had native support for Wayland since 1.20.4, including its latest release 1.21.1, without the need for any modifications. However, upon installing Forge, the instance doesn't go past the loading screen. This is obviously a Forge issue, and a simple test from your end would prove that. I guess you can keep this closed, you'll figure it out eventually.

**Comment by LexManos** [comment] 2024-08-20 04:54
It can not be tested because I don't have the hardware to test it on.
So there will be no testing done.
If you have a build that the loading screen triggers the issue. Then disable the loading screen.
If you wanna PR the disabling of that section of code to old MC versions feel free.
I have no way of testing so i don't really care.

Edit: So after speaking with others on the team and looking at the git repo. The fix is in versions that we care about/build all the way back to 1.20.4
It is not in 1.20.2 or 1.20.3 because we don't care about those versions, As they are either small or not adopted by the community enough that we have not made a backporting branch for them. 
As such I'll amend my comment to: `Any version that vanilla supports it, that we care about (1.20.4+), Forge's loading screen supports it.`
