### ISSUE TITLE
[1.12] Item.getItemFromBlock returns null (air) for all vanilla doors.

### ISSUE THREAD

**Issue by Shadows-of-Fire** [MinecraftForge/MinecraftForge#3981] opened 2017-06-14 08:56 UTC
Since `Item.getItemFromBlock` returns `Item item = BLOCK_TO_ITEM.get(block);` with a null check to return `Items.AIR`, it appears that an Item for all the vanilla doors (`Blocks.IRON_DOOR` etc.) is not registered to this map.

**Comment by Shadows-of-Fire** [comment] 2017-06-14 08:59
Upon further inspection this seems to be the case for all vanilla blocks with custom itemblocks, such as cauldrons and brewing stands.

**Comment by diesieben07** [comment] 2017-06-14 09:43
Yes, this is not a bug.

**Comment by Actuarius** [comment] 2017-06-15 04:31
@tterrag1098 closed this issue

**Closed as completed by Actuarius** 2017-06-15 04:31 UTC

**Comment by tterrag1098** [comment] 2017-06-15 04:33
This is true for any block without a trivial mapping to an itemblock. Doors have been special cased like this for a long time.
