### ISSUE TITLE
ModelLoader registered with ModelLoaderRegistry.registerLoader is not being called

### ISSUE THREAD

**Issue by Jkmcameron** [MinecraftForge/MinecraftForge#6578] opened 2020-03-21 05:25 UTC
**Minecraft Version:** 1.15.2

**Forge Version:** 31.1.19

**Logs:** no crash so no crash report, heres a link to the log: https://drive.google.com/file/d/13D19Bxk06FrY1Br6D1Sd2wExwoVbUuJB/view?usp=sharing

**Steps to Reproduce:**
 1. Register a new `ModelLoader `with `ModelLoaderRegistry.registerLoader`
 2. Find out it doesn't work

I've got in my Mod class:

```
    @OnlyIn(Dist.CLIENT)
    @SubscribeEvent
    public void clientSetup(FMLClientSetupEvent event)
    {
	ModelLoaderRegistry.registerLoader(new ResourceLocation("t3l", "log"), LogModelLoader.INSTANCE);
    }

```

And I've verified with a print to the log that `clientSetup` gets called. Here's my `LogModelLoader` class:

```
public class LogModelLoader implements IModelLoader<LogModel>
{
    public static final LogModelLoader INSTANCE = new LogModelLoader();

    @Override
    public void onResourceManagerReload(IResourceManager resourceManager)
    {
	System.out.println("TEST TEST TEST");
    }

    @Override
    public LogModel read(JsonDeserializationContext deserializationContext, JsonObject modelContents)
    {
	System.out.println("TEST TEST TEST");

	return new LogModel();
    }
}

```

And in my white_oak_log.json model file:

```
{
    "forge_marker": 1,
    "textures": {
      "bark": "t3l:block/white_oak_log",
      "core": "t3l:block/stripped_white_oak_log",
      "ring": "t3l:block/white_oak_log_top"
    },
    "loader": "t3l:log"    
}

```
I have set the "loader" key in the json to the same string I registered my `LogModelLoader` under but the `read` function is never called, verified by the  lack of a console output. The only thing questionable is that I haven't setup the variants in my block json file (which the console is screaming about) but thats because I assigned properties in my `LogBlock` class that I intend to use in my code and never address in the json files. This shouldn't be the issue since replacing the "loader" keyin my json file with the vanilla "elements" tag causes the block to get loaded correctly.

**Comment by Jkmcameron** [comment] 2020-03-21 15:22
Ok what ended up working for me was removing the "model" key in my blockstate jsoon from the "default" block and putting it into the "variants" block:

```
{
  "variants": {
    "": {
      "model": "t3l:block/white_oak_log"
    }
  }
}
```

I'm not sure if this is working as intended

**Comment by gigaherz** [comment] 2020-03-21 15:32
"default" was a feature of the forge blockstates system, which doesn't exist anymore in 1.15.
It has never been part of the vanilla file format.
Closing this as it's it's working as intended.

**Closed as completed by gigaherz** 2020-03-21 15:32 UTC

**Comment by Jkmcameron** [comment] 2020-03-25 14:32
:/ The forge documentary is doodoo
