### ISSUE TITLE
Modded overworld biomes not generating

### ISSUE THREAD

**Issue by gdude2002** [MinecraftForge/MinecraftForge#6940] opened 2020-07-08 19:00 UTC
**Minecraft Version:** 1.16.1

**Forge Version:** 32.0.59

**Logs:** [debug.log](https://gist.github.com/gdude2002/76e9ab4aa149ab0bf061929aa7c28636) / [latest.log](https://gist.github.com/gdude2002/cbf32afe687ffaba09ce8be0a8352279)

**Steps to Reproduce:**
1. Register a modded biome as you would have in 1.15.x
2. Generate a world and attempt to find the biome, either by hand or using the new `/locatebiome` command

**Description of issue:**
Quite simply, while everything appears to be registered just fine (and buffet-type world still work correctly), modded biomes no longer appear to generate on the overworld.

I'm not familiar with the nature of how Forge handles biome registration - so, unfortunately, I can't directly comment on that. That said, multiple people on Discord have mentioned that the BiomeManager may not have its hooks implemented just yet.

I'm working on porting up a mod from 1.15.x, where biome registration worked correctly. Unfortunately, I'm not able to provide my source at this time - but it should be quite easy to come up with a test case for this.

**Comment by LexManos** [comment] 2020-07-13 21:37
Please provide a sample mod.
'Register a modded biome as you would' isn't showing us what you're doing.
It's also nice to have a small test case to verify any fixes people do.

**Comment by Cheaterpaul** [comment] 2020-07-14 16:11
i have the same problem. I have created a test mod and tested it with both 1.16.1-32.0.66 and 1.15.2-31.2.0 and with 1.15 this works as intended, but in 1.16 the biome is not generated. https://github.com/Cheaterpaul/testmod.
The 1.15 line are commented out

The ModClass https://github.com/Cheaterpaul/testmod/blob/master/src/main/java/test/test/Test.java

**Comment by Cheaterpaul** [comment] 2020-07-19 16:04
#6990 probably solves this

**Comment by ghost** [comment] 2020-07-19 17:12
Should do

**Comment by sciwhiz12** [comment] 2020-07-28 15:37
As the PR linked above has been merged, I believe this issue can be closed.

**Comment by Cheaterpaul** [comment] 2020-07-28 16:28
yes

**Comment by TheCurle** [comment] 2020-07-28 16:30
Direct any more problems to the PR that fixed this.

**Closed as completed by TheCurle** 2020-07-28 16:30 UTC
