### ISSUE TITLE
Forge Attributes cause error spamm on client

### ISSUE THREAD

**Issue by steam9w** [MinecraftForge/MinecraftForge#10148] opened 2024-10-27 05:09 UTC
**Minecraft Version:** 1.20.1

**Forge Version:** 47.3.11

**Steps to Reproduce:**
1. Setup a forge server
2. Connect to it with a vanilla client

Description of issue:
Since forge adds their own attributes (see ForgeMod.SWIM_SPEED, or ForgeMod.REACH_DISTANCE) when those get sent to the client for update the client obviously doesnt know about them causing "Entity x does not have attribute null" error message spamm

**Logs:**
https://pastebin.com/Q4CK98CU

Why did you close my issue? - https://github.com/MinecraftForge/MinecraftForge/issues/10147
Here is a similar problem that was solved - https://github.com/MinecraftForge/MinecraftForge/issues/7368

**Comment by LexManos** [comment] 2024-10-27 05:16
I closed the issue because of the reason stated by the bot. This isn't a bug in forge. This is an issue in your setup and you need to do some basic debugging on the forums or discord to figure it out. The github is a place for confirmed issues.

I have seen you posting on the discord as well providing no information. Which is why nobody is helping you.

Your conclusion that the client doesn't know about the atributs is just flat out wrong as if that was the case everyone using forge would have the issues and the laws of computing would be broken.

Ao, again, closing this go to the discord to do basic debugging or just start deleting mods from your pack until it's resolved as it's not anforge issue

**Closed as completed by LexManos** 2024-10-27 05:16 UTC

**Comment by steam9w** [comment] 2024-10-27 05:23
There are 0 mods and 0 plugins installed on the server and client!!!!!

**Comment by LexManos** [comment] 2024-10-27 05:25
I highly doubt that as again the laws of computing would have to change. Nobody else is getting your issue and everyone would if your assertion was true.

Go to the damn discord. Post your FULL DEBUG LOGS and maybe someone can figure it out.
