### ISSUE TITLE
forge minecraft 39.0.66

### ISSUE THREAD

**Issue by 999lordcalvert** [MinecraftForge/MinecraftForge#8451] opened 2022-02-06 08:47 UTC
![image](https://user-images.githubusercontent.com/99117294/152673686-423a2678-a6ee-4030-a2ee-e712bd612069.png)
![image](https://user-images.githubusercontent.com/99117294/152673698-79d79bb0-c137-45bc-b084-a4e21786a363.png)
ever since i installed forge it seems to cause the commands to not work on any server, while it works just fine not using forge as the main client.

**Comment by sciwhiz12** [comment] 2022-02-06 09:04
Duplicate of #8438

**Closed as completed by sciwhiz12** 2022-02-06 09:04 UTC
