### ISSUE TITLE
Race condition in LazyOptional

### ISSUE THREAD

**Issue by malte0811** [MinecraftForge/MinecraftForge#7610] opened 2021-01-19 20:48 UTC
Version: 19f8d2a7937dc7968ecbef2f9785687193fcd210/36.0.1.

This probably isn't a major issue in practice (though we did get reports of it for IE, see BluSunrize/ImmersiveEngineering#4547), I still think that it should at least be documented somewhere:

`LazyOptional` appears to be designed for multithreaded use (otherwise using an `AtomicReference` would be a very unusual choice). However [this](https://gist.github.com/malte0811/217cf7b7cd5e190958df44e65c56b0fe) code does not produce the expected result: Expected behavior would be for both threads to run without any exceptions, in practice one of them crashes with [this](https://github.com/MinecraftForge/MinecraftForge/blob/19f8d2a7937dc7968ecbef2f9785687193fcd210/src/main/java/net/minecraftforge/common/util/LazyOptional.java#L133) exception.  
(Note: The call to sleep isn't realistic, but the race condition can still occur with reasonable getters. Sleep just makes it trivial to reproduce)  
The problem is that `resolved` is [set to a reference to `null` in one thread](https://github.com/MinecraftForge/MinecraftForge/blob/19f8d2a7937dc7968ecbef2f9785687193fcd210/src/main/java/net/minecraftforge/common/util/LazyOptional.java#L115), causing the second thread to [return that `null`](https://github.com/MinecraftForge/MinecraftForge/blob/19f8d2a7937dc7968ecbef2f9785687193fcd210/src/main/java/net/minecraftforge/common/util/LazyOptional.java#L110-L111).  
The easiest fix would be to add a lock, similar to `Lazy.concurrentOf`. I'm not sure about the performance implications of that lock though, and the original code seems to be an attempt at keeping that function as fast as possible. On the other hand the "inner" part of `getValue` should only run rarely (outside of bugs), so it may not be necessary to keep that section super fast.

**Comment by LexManos** [comment] 2021-01-19 20:59
The inner part of getValue, as in everything inside the `if (supplier != null)` block should only ever be run once per lazy optional. So throwing a sync lock internally on that would probably be the best idea.
Would need to be a proper double checked sync lock. But should be simple enough.
LazyOptional was designed to work around costly value construction, so having the supplier take some time isn't unreasonable.

**Comment by malte0811** [comment] 2021-01-20 10:27
I've implemented a fix for this, but ran into one more question: Do we care about the exact behavior for broken suppliers (ones that return null)? In the current implementation they are called once (even if the first call doesn't immediately crash everything), my current implementation would call them every time `getValue` is called. Is that acceptable? Otherwise I'll probably need to wrap `resolved` in something similar to `AtomicReference` again (probably `Mutable<T>`), which feels like a lot of effort for handling a broken mod.

**Comment by LexManos** [comment] 2021-01-20 18:06
Yes we care, that is why there is currently an exception raised.
The supplier should only ever be called once, that's one of the main points.
This fix is simple, just put a `sync(this){ if (value != null) return value; ...` inside the `if (supplier != null)`

**Comment by malte0811** [comment] 2021-01-20 18:22
With your formatting I'm not quite sure if you read the question correctly, and your "quick fix" does not really make the behavior in the case I'm talking about clear either. Consider this code:
```java
LazyOptional<T> foo = LazyOptional.of(() -> {
    System.out.println("FOO");
    return null;
});
foo.ifPresent(f -> {});
foo.ifPresent(f -> {});
```
Currently this will [print (not throw) an exception](https://github.com/MinecraftForge/MinecraftForge/blob/19f8d2a7937dc7968ecbef2f9785687193fcd210/src/main/java/net/minecraftforge/common/util/LazyOptional.java#L117-L121) and print "FOO" on the first call, but not on the second. **Given that the contract of a LO is already being violated**, is it important to keep this behavior?  
My implementation from earlier today is [this](https://gist.github.com/malte0811/2974f1878b0e02a209a8d521f7364989), which is probably the obvious one and (I think) the one you are suggesting. With that implementation the exception and "FOO" will be logged on both calls (`resolved` is still `null` in the second call since the supplier returned null).

**Comment by LexManos** [comment] 2021-01-20 18:27
Let me be more plain, yes you should keep the atomic, Yes it should only log/error once. {I really thought we threw an error but I think that may of changed due to modders breaking things...} There is a reason it's a NonNullSupplier and not a normal supplier. It was intended to error if modders returned null. There is no reason to continue calling a supplier if we know the return will be null. It's a factory that gets called once.

**Comment by Alan4245** [comment] 2021-02-06 11:40
Sorry guys but I'm new and I'm trying to follow the problem (which I also have). Is the problem currently solved or do we have to wait for a new forge version?

**Comment by gigaherz** [comment] 2021-02-06 11:47
No the fix for this issue has not yet been merged. Once it's merged, this issue will be closed, indicating that it's no longer a problem.

**Closed as completed** 2021-02-15 20:49 UTC
