### ISSUE TITLE
[1.14.4] Dying in a dimension other than Overworld causes IOException and lockup.

### ISSUE THREAD

**Issue by Unnoen** [MinecraftForge/MinecraftForge#5978] opened 2019-07-27 03:10 UTC
**Minecraft Version:** 1.14.4

**Forge Version:** 28.0.19

**Java Version:** 1.8.0_222 by AdoptOpenJDK

**Logs:**
First attempt (Clean install): https://gist.github.com/Unnoen/d175eca05b90a87c664ee7d7c0735ad5
Recorded attempt: https://gist.github.com/Unnoen/ce90c3342b73d75020c08419c292f8e3

**Video of reproduction:** https://puu.sh/DXS46/9dc5527658.mp4

**Steps to Reproduce:**
1. Clean install (I did not change any options).
2. Create new world (I did this in creative).
3. Give yourself obsidian and a flint.
4. Create and enter portal.
5. Find pigman, change gamemode to survival and aggro it.
6. Die.

**Description of issue:**
Dying in the Nether causes what I believe is a race condition of some sort, locking up the game and preventing *any* further actions (GUI works). I was able to reproduce this using the provided steps 100% of the time (4 times tested).

**Comment by Unnoen** [comment] 2019-07-27 03:14
I should clarify, issue *does not* persist in vanilla, it appears to be Forge only.

**Comment by Unnoen** [comment] 2019-07-27 03:21
Second recording with F3 overlay enabled - https://puu.sh/DXSkY/990a4eb5a1.mp4 (Also showing the only way to exit is to kill the process)

**Comment by Unnoen** [comment] 2019-07-27 03:29
I just confirmed this is also happening in The End, same repro steps, except with an End portal and Enderman. https://gist.github.com/Unnoen/89bf74768e84cbf44d901883ff5c58a7

**Comment by Aeronica** [comment] 2019-07-27 03:37
I can reproduce this, although I do have my test mod jar installed too.
![2019-07-26_22 26 04](https://user-images.githubusercontent.com/6465667/61989491-ce082780-aff5-11e9-8681-8da4e95641fb.png)

debug log
[https://gist.github.com/Aeronica/d77d272e17a505536a28d84bb685bc11](url)

**Comment by ProsperCraft** [comment] 2019-07-27 03:44
This has happened many times on our server, and one of my guys reproduced it with only forge in single player - 
https://www.minecraftforge.net/forum/topic/73624-forge-1144-28017-cant-respawn-after-dying-in-nether

And Gigahertz reproduced it here - https://github.com/gigaherz/ToolBelt/issues/37#issuecomment-511236508

**Comment by LexManos** [comment] 2019-07-27 05:10
Something in your workspace is closing the world.
Unfortunately there isn't a log message telling us who.
If you can reliably reproduce I could write you a debug Forge version to print who is doing it.

**Comment by Unnoen** [comment] 2019-07-27 05:43
latest.log and debug.log using modified Forge version Lex sent me for testing:
latest: https://gist.github.com/Unnoen/1ead8179217ce4bf29c400b438d1f73c
debug: https://gist.github.com/Unnoen/d2ebb5eff2e912e3ddcc368da206e5dc

**Comment by Gamebuster19901** [comment] 2019-07-27 06:00
I was able to reproduce the issue. You might have figured it out, but I might as well post it anyway. It appears DimensionManager.canUnloadWorld() is returning true even though it doesn't appear that it should be.

**Comment by LexManos** [comment] 2019-07-27 06:07
If a player isnt in the world. Then it should unload just fine.
This isn't a issue with that. Somehow you're being removed from the world. And then ticked in the world.

**Comment by Ommina** [comment] 2019-07-27 09:29
Does the death cause make any reasonable difference?

28.0.17 will reliably lockup for me if I die to a pigman, and has locked up on death due to fall damage, or suffocating in a block (one attempt each).  However, the lockup does **not** occur if I jump into lava.

**Comment by LexManos** [comment] 2019-07-27 09:33
No, I got a fix, for some unknown reason they are ticking the player even when the player is dead, and removed from the world.
I'm just gunna make it stop that.

**Closed as completed** 2019-07-27 09:35 UTC

**Comment by BlayTheNinth** [comment] 2019-08-16 17:43
Would the fix remain functional with only checking for `!removed` instead of `isAlive()` (since that also checks for player health)?

My mod [Hardcore Revival](https://www.curseforge.com/minecraft/mc-mods/hardcore-revival) has players remain in world with zero health upon death, counting down a timer during which they can be rescued, which depended on the player tick event being fired.
