### ISSUE TITLE
black particle

### ISSUE THREAD

**Issue by seema84** [MinecraftForge/MinecraftForge#8297] opened 2021-12-13 15:21 UTC
**Minecraft Version:** 1.17.1

**Forge Version:** 1.17.1 - 37.1.1

**Steps to Reproduce and Description:**
In some situations, black particles are displayed in masses (also on graphic setting fancy). 
This only happens when forge is installed. This behavior has occurred since version 1.17.1. 

![unknown](https://user-images.githubusercontent.com/2832339/145838651-95acfdbe-b7f5-4fc3-9d70-6ad98c7e845d.png)
![2021-12-13_14 40 19](https://user-images.githubusercontent.com/2832339/145837694-03ab4d14-a1c0-4788-afb0-1db79fe8af7a.png)

**Comment by AterAnimAvis** [comment] 2021-12-13 15:24
Seems to be duplicate of <https://github.com/MinecraftForge/MinecraftForge/issues/8221>

**Closed as completed** 2021-12-13 15:25 UTC
Labels: Bug, 1.17

**Comment by seema84** [comment] 2021-12-13 15:27
this does not look like the same issue

**Comment by AterAnimAvis** [comment] 2021-12-13 15:44
#8221 is a regression introduced in 1.17 and will be fixed in 1.18 (#8291) which can turn all particles on screen black (this effects all particles).

The issue you've reported matches what I know of #8221 is in a version in which that issue is present.

**Comment by seema84** [comment] 2021-12-13 15:49
will there be a fix for version 1.17.1?

**Comment by gigaherz** [comment] 2021-12-13 15:59
Nope. the 1.17.1 branch is now considered legacy. We won't backport things to it unless it's a critical issue like the log4j one.

**Comment by seema84** [comment] 2021-12-13 16:09
that is a pity but thanks for the information
