### ISSUE TITLE
1.9: Item.shouldCauseReequipAnimation is ignored

### ISSUE THREAD

**Issue by Vazkii** [MinecraftForge/MinecraftForge#2550] opened 2016-03-16 00:51 UTC
The method should also be updated to have an EnumHand parameter.

**Comment by LexManos** [comment] 2016-03-20 04:54
I decided against the EnumHand part because that really shouldn't matter.
Also can you post a small same to test it. It *should* work but i'll look into it.

**Comment by Vazkii** [comment] 2016-03-20 14:47
Sure, throw this in any item and you'll see it doing the requip animation constantly https://gist.github.com/Vazkii/a431564ab6bbbe240787

**Comment by Actuarius** [comment] 2016-04-05 19:09
@williewillus added labels [Bug]

**Comment by LexManos** [comment] 2016-05-29 06:23
This has been fixed IIRC, and I also can not reproduce it using your code. So closing.

**Closed by LexManos** 2016-05-29 06:23 UTC
Labels: Bug
