### ISSUE TITLE
Resource packs and overrides

### ISSUE THREAD

**Issue by tomaxed** [MinecraftForge/MinecraftForge#3540] opened 2016-12-14 20:16 UTC
Hi, I'm the creator of a resource pack called [Beyond the Lands](https://minecraft.curseforge.com/projects/beyond-the-lands) and on this resource pack, there's a function with the overrides that allow map makers to have new content available with commands. this function use overrides and the possibility to set a different model to a normal damaged item and a damaged item with the unbreaking tag on it.

Here is an example of the code used on a tool:

`"overrides": [
		{ "predicate": {"damaged": 0, "damage": 0.0006402048655569782}, "model": "item/_aura1"},
		{ "predicate": {"damaged": 0, "damage": 0.0012804097311139564}, "model": "item/_aura2"},
		{ "predicate": {"damaged": 0, "damage": 0.0019206145966709346}, "model": "item/_aura3"},
		{ "predicate": {"damaged": 1, "damage": 0.0006402048655569782}, "model": "item/diamond_hoe"},
		{ "predicate": {"damaged": 1, "damage": 0.0012804097311139564}, "model": "item/diamond_hoe"},
		{ "predicate": {"damaged": 1, "damage": 0.0019206145966709346}, "model": "item/diamond_hoe"}]`

So the problem is that this function don't work with forge, the first custom model is displayed on all the metadatas of the item, with or without the unbreakable tag.

can the mod get a fix for that or should I remove this feature from my resource pack?

thanks.

**Comment by howtonotwin** [comment] 2016-12-25 01:09
Could this be related to/duplicate #3264?

**Comment by williewillus** [comment] 2016-12-25 01:20
Dupe of 3264, yes

**Comment by mezz** [comment] 2016-12-27 09:07
Thanks for the report!
This definitely looks like a Forge bug. There is no timeline for a fix but it is not intentional.

**Closed as completed by mezz** 2016-12-27 09:07 UTC
