### ISSUE TITLE
Sculk sensors do not emit light when the "experimentalForgeLightPipelineEnabled" setting is enabled.

### ISSUE THREAD

**Issue by Lolothepro** [MinecraftForge/MinecraftForge#9584] opened 2023-06-21 19:21 UTC
Sculk sensors do not emit light when the "experimentalForgeLightPipelineEnabled" setting is enabled.

**Minecraft Version:** 1.20.1

**Forge Version:** 47.0.15

**Steps to Reproduce:**
1.	Use Sculk Sensors with experimentalForgeLightPipelineEnabled
2.	Use Sculk Sensors without experimentalForgeLightPipelineEnabled
3.	Compare

**Screenshot:**

Without:
![2023-06-21_21 19 04](https://github.com/MinecraftForge/MinecraftForge/assets/68275908/0790e281-bf3b-495e-b603-18829237a051)
With:
![2023-06-21_21 20 23](https://github.com/MinecraftForge/MinecraftForge/assets/68275908/0b00c3c5-031f-4003-8a4d-20cc9849edc4)

**Comment by marchermans** [comment] 2023-06-21 19:24
This should be fixed in the build that has been published a couple of minutes ago.

**Comment by Lolothepro** [comment] 2023-06-21 19:24
> This should be fixed in the build that has been published a couple of minutes ago.

No

**Comment by PlatinPython** [comment] 2023-06-21 19:33
Can reproduce on Forge version 47.0.15

**Comment by marchermans** [comment] 2023-06-21 19:34
This should be fixed in the build that has been published a couple of minutes ago.can reproduce this too.

I will need to check i just merged something to deal with emitting blocks like this and that might interfere with this

**Comment by XFactHD** [comment] 2023-06-21 19:41
The PR you just merged kinda flipped the bug on its head. Before, the fullbright effect of the block itself (magma and sculk sensor) didn't work but the slight "aura" of light around it worked fine. Now, the fullbright effect of the block itself works but the light "aura" is gone

**Comment by marchermans** [comment] 2023-06-21 20:03
Yeah i tested the underwater magma stuff and there the halo was not noticeable for me which is why I missed it

I will check on this tomorrow

**Comment by pupnewfster** [comment] 2023-06-21 21:07
My guess is this is probably due to my comment on the PR you merged where I was unsure if it was supposed to be doing what I did or like vanilla where it calls the `getLightColor` with the same state. If so this part of the thing was probably already broken even before my PR when in the experimental pipeline.

**Comment by LexManos** [comment] 2023-07-15 15:08
https://github.com/MinecraftForge/MinecraftForge/pull/9651

**Closed as completed by LexManos** 2023-07-15 15:08 UTC
Labels: Rendering, 1.20
