### ISSUE TITLE
[1.20.1][47.0.16] Unable to start forge client with example mod

### ISSUE THREAD

**Issue by The-Lord-of-Owls** [MinecraftForge/MinecraftForge#9590] opened 2023-06-22 16:03 UTC
**Minecraft Version:** 1.20.1

**Forge Version:** 47.0.16

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Download MDK
 2. Rename examplemod class and set things up as shown here(excluding where the build.gradle file is modified): https://www.youtube.com/watch?v=p-mp91zrlqo&list=PLKGarocXCE1FlLU16RRfaS0bcabHDSvLA
 4. setup our mod properties inside gradle.properties
 5. open gradle window and attempt to run client.
 6. Execution failed for task ':runClient'.

**Description of issue:** Unable to get inteliJ to run the actual client with the mod. console provides no helpful info on how to resolve
[debug.log](https://github.com/MinecraftForge/MinecraftForge/files/11836032/debug.log)
[latest.log](https://github.com/MinecraftForge/MinecraftForge/files/11836033/latest.log)

**Comment by marchermans** [comment] 2023-06-22 20:32
What system are you on?

**Comment by marchermans** [comment] 2023-06-22 20:32
@cpw his system seems to be stuck at the OpenGL check....

**Comment by cpw** [comment] 2023-06-22 20:34
Hardware you're trying to run on? Exact details of graphics card and OS please...

FYI @marchermans that debug line is when it's trying to open the window. It's possibly one of those worst case scenarios where asking for a specific GL version causes unexpected behaviour.

**Comment by marchermans** [comment] 2023-06-22 21:03
> Hardware you're trying to run on? Exact details of graphics card and OS please...
> 
> FYI @marchermans that debug line is when it's trying to open the window. It's possibly one of those worst case scenarios where asking for a specific GL version causes unexpected behaviour.

Yep which is why I wanted this to go on your radar for sure. We will need to see and triage this accordingly

**Comment by The-Lord-of-Owls** [comment] 2023-06-22 21:11
Hardware and OS info

OS: Windows 10
CPU: AMD Ryzen 5 1500x @ 3.5 GHz
GPU: AMD RX 460(x2 using crossfire)
RAM: 64gb @ 3200 MHz

**Comment by cpw** [comment] 2023-06-22 21:14
Hmmm. What version of the AMD drivers are you using? I'm assuming vanilla works fine? Are you on the forge discord?

**Comment by The-Lord-of-Owls** [comment] 2023-06-22 21:22
Not on forge discord and I think I read your msg too late I kinda already started a update for radeon settings to see if it would fix it. its still updating but should probably start working when it finishes. I hope atleast

**Comment by cpw** [comment] 2023-06-22 21:43
Yeah, there's some bugs in amd drivers from last year that can cause hangs.

**Comment by The-Lord-of-Owls** [comment] 2023-06-23 00:53
yea it was old driver issue, now to just fix my own code is all thats currently a problem for me :p

**Comment by cpw** [comment] 2023-06-23 01:09
Reopening until pr is merged as this is an invalid behaviour even if it is a driver issue.

**Closed as completed** 2023-06-23 05:58 UTC
Labels: 1.20
