### ISSUE TITLE
[1.16.5] Cannot join LAN worlds after removing blocks/items

### ISSUE THREAD

**Issue by SuperMartijn642** [MinecraftForge/MinecraftForge#7737] opened 2021-04-29 16:20 UTC
**Minecraft Version:** 1.16.5

**Forge Version:** 36.1.13

**Logs:**
The hosting player's and joining player's logs,
https://gist.github.com/SuperMartijn642/8e57c32c63b1c5ffe884a5a1c900842a

**Steps to Reproduce:**
1. Subscribe the following method to the mod event bus:
```java
public static void onItemRegistry(RegistryEvent.Register<Block> e){
    e.getRegistry().register(new Block(AbstractBlock.Properties.create(Material.ROCK)).setRegistryName("block"));
}
```
2. Create a world and save it
3. Remove the above method from the event bus
4. Start two instances
5. Load the previously created world and open it to LAN in one of the instances
6. Try to join the LAN session with the other instance

**Description of issue:**
Players can't join a LAN world after previously registered items and blocks are removed from that world.
For example:
A player creates a world with a mod that adds items or blocks. Then the player removes that mod. When the player loads the world again and opens it to LAN, other players can't join. Joining players will receive a "Failed to synchronize registry data from server, closing connection" message.

The issue is not present on dedicated servers, only on LAN worlds.

**Example Mod:**
I created an example mod to demonstrate the issue,
https://github.com/SuperMartijn642/ForgeLanIssueExampleMod/blob/master/src/main/java/com/supermartijn642/forgelanissue/ForgeLanIssue.java

**Comment by TheCurle** [comment] 2021-04-29 16:24
We're aware of this issue. 
The difficulty in solving it, is that these events are fired deep inside CompletableFuture hell, which is nigh impossible to debug properly.

I'll keep you updated if anything happens on that front.

**Comment by JoJoDeveloping** [comment] 2021-04-29 22:09
The problem, as far as I can see, is this. Note the comment at the end of line 317:
https://github.com/MinecraftForge/MinecraftForge/blob/929c7b7a0b4d56bf0cc9a9025d915f001fed47a7/patches/minecraft/net/minecraft/client/Minecraft.java.patch#L314-L317

This runs injection twice. The first time, we mark the missing block as a dummy:
https://github.com/MinecraftForge/MinecraftForge/blob/929c7b7a0b4d56bf0cc9a9025d915f001fed47a7/src/main/java/net/minecraftforge/registries/ForgeRegistry.java#L783
The second time, we re-read things from the local file, which unmarks that block from being a dummy:
https://github.com/MinecraftForge/MinecraftForge/blob/929c7b7a0b4d56bf0cc9a9025d915f001fed47a7/src/main/java/net/minecraftforge/registries/ForgeRegistry.java#L399

**Comment by JoJoDeveloping** [comment] 2021-04-29 22:26
This ^^ was introduced in Lex' fix for #7586, commit 50d75a27e1e8ff94797fecae29c2f18d4503f0d4

**Comment by LexManos** [comment] 2021-04-30 00:04
Yes, the issue is this double read and the fact that the game reads the full state of the dynamic registries before starting the world. 
The problem is getting around to fixing it. There are two approaches: Revert to frozen and re-inject. This has unknown side effects related to the other dynamic registries and the objects MC creates during world verification.
The other is to make the system smarter, and make it check if the source object it's copying over is a dummied object. The whole problem is that it's loosing the dummy flag.

**Comment by JoJoDeveloping** [comment] 2021-04-30 18:50
Re 2, the problem is that the object being copied over from the save is not a dummy in the saved snapshot, as it previously actually existed. And the snapshot injection then un-dummies the previously registered dummy since it got injected with an actually existing thing, which is the intended behavior in other places.

**Comment by LexManos** [comment] 2021-04-30 18:57
What.. Yes, resuscitating and un-dummifying things is an intended behavior yes. But what I am saying is that the second pass *should* be able to know that the object is dummied as it has access to the registry class. So it can see that the object exists. But it's also marked as dummied so it doesn't remove the flag.

The other path, where resuscitating is intended. Would NOT have the dummy flag set, and the objects will not be created by the dummy factories.

**Comment by TheCurle** [comment] 2021-05-01 08:19
@diesieben07 has a somewhat workable solution in #7700.
Although, this comment is mostly just to link these.

**Comment by Elrynon** [comment] 2021-06-10 04:57
Any update on this? Sadly my wife and I just lost a world we've been playing on for a few weeks now due to this bug. :(

**Comment by diesieben07** [comment] 2021-06-10 06:52
This bug does not damage or destroy worlds. It just makes it so you can't play it with "Open to LAN". As a workaround you can run a local server.

**Comment by WenXin20** [comment] 2021-06-10 07:06
Just thought that I should mention that I also have seen this bug, but I use a server, not Open to LAN. It could be possible another mod causes the same issue to occur on the server. I don't have a log of this anymore, but if it happens again I'll be sure to send it. From what I can remember, it disconnected me because of missing block registries.

**Comment by diesieben07** [comment] 2021-06-10 07:10
If it happens on the server, it is not the same issue as this. If you have issues, please make a thread on the forums.

**Comment by Elrynon** [comment] 2021-06-10 09:23
So if I set up a local server we'd be able to keep playing the world we were already playing?

Edit: Nm, just found on google how to transfer the world over to local server. I was told on another site that until Forge fixed the bug we just had to wait to play the world we already had. Which in my eyes is the same as "losing" that world. Ty for your advice!

**Comment by privacyrespected** [comment] 2021-06-22 10:14
Is there a way to solve it from the client side?

**Comment by SizableShrimp** [comment] 2021-06-22 10:15
The solution is to run the LAN world as a local server until the problem is fixed.

**Comment by LexManos** [comment] 2021-07-20 04:17
Finally got a repro case, and got around to digging into this. 
It's been solved: https://github.com/MinecraftForge/MinecraftForge/commit/4e4d31b68c788872a403316b48fa9e6be182ce9f#diff-c36889606c030a80f1661c88f2ee97bf5e2bbbb31824344ad4fbb332df9791d9R727

**Closed as completed by LexManos** 2021-07-20 04:17 UTC
Labels: Bug, Confirmed, 1.16
