### ISSUE TITLE
[1.16.1] Disable Button "<- ->"

### ISSUE THREAD

**Issue by Rumaruka** [MinecraftForge/MinecraftForge#6820] opened 2020-06-26 06:39 UTC
**Minecraft Version:** {Minecraft version}
1.16.1
**Forge Version:** {Forge version. *Version number, not latest/rb*}
32.0.7

Choose the button "Search"

![image](https://user-images.githubusercontent.com/8148679/85828317-8a87e180-b7a1-11ea-9bb5-52b75c1dce1a.png)

**Comment by Rumaruka** [comment] 2020-06-26 06:40
Now button return back, but I think report about this,

**Comment by Asherslab** [comment] 2020-06-26 06:54
Apologies but i'm not entirely certain what the bug that you're reporting is? 
could you please detail it further?
Thanks.

**Comment by 3TUSK** [comment] 2020-06-26 06:58
According to the screenshot, the buttons for "go to next/previous page of item groups/creative tabes" is visually missing, Asher.

**Comment by 3TUSK** [comment] 2020-06-26 07:16
To add up, I can reproduce this with just Forge 32.0.7 and gigaherz's Enderthing 1.0.1 (to get a new creative tab). In theory, you only need a mod that adds a new item group to reproduce this.
![image](https://user-images.githubusercontent.com/9113033/85830935-46b1bf80-b742-11ea-8655-75d40d77978c.png)

------

Further tests show that those buttons will reappear after I ~~enlarge the window, or enter full-screen mode~~ resize the window, not matter how. Buttons won't disappear again if I re-size the window back again. And those buttons are functional, as shown below:
![image](https://user-images.githubusercontent.com/9113033/85831158-b4f68200-b742-11ea-9932-9c6f2595a487.png)

------

Further tests show that buttons will only disappear upon I first open a save, no matter if I am in window mode or full-screen mode, and no matter what size of window I have.

**Comment by Cyborgmas** [comment] 2020-06-26 11:09
Should be fixed in #6827

**Comment by 3TUSK** [comment] 2020-06-26 18:45
Confirmed to be fixed ~~in~~ as of Forge 32.0.18

Update: wording

**Comment by TheCurle** [comment] 2020-06-26 18:46
Looks like the fix was merged in 32.0.12, as a matter of fact. But, yeah. It's fixed now.

**Closed as completed** 2020-06-26 18:48 UTC
Labels: Bug, 1.16
