### ISSUE TITLE
FML "Loading" screen very slow at high resolutions

### ISSUE THREAD

**Issue by ArcanoxDragon** [MinecraftForge/MinecraftForge#5594] opened 2019-03-05 00:08 UTC
This issue is a re-post of mezz/JustEnoughItems#1442. Loading Minecraft on my 4K laptop takes several orders of magnitude longer when the Minecraft window is maximized as opposed to when it is the default size that Minecraft starts with. My presumption is that the rendering code for the loading screen is relatively CPU-heavy, starving mods of CPU cycles during loading when the rendered area is fairly large. More information can be found at issue referenced above.

**Comment by LexManos** [comment] 2019-03-11 22:05
Unable to reproduce, even on my 4K monitor.
And considering the Forge loading screen is gone in 1.13, to be replaced by Vanilla's in 1.14+, and there is a simple 'fix'. Going to file this as wontfix.

**Closed as completed by LexManos** 2019-03-11 22:05 UTC
Labels: Wont Fix/Works As Intended
