### ISSUE TITLE
chest doesnt open and get this in the console 

### ISSUE THREAD

**Issue by abdullamu** [MinecraftForge/MinecraftForge#4670] opened 2018-01-09 11:34 UTC
i dont know if it's forge problem but there's no indication of other mode causing it.

[16:34:06] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: net.minecraftforge.common.property.ExtendedBlockState$ExtendedStateImplementation.doesSideBlockChestOpening(Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/EnumFacing;)Z
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_151]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.AbstractMethodError: net.minecraftforge.common.property.ExtendedBlockState$ExtendedStateImplementation.doesSideBlockChestOpening(Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/EnumFacing;)Z
	at net.minecraft.block.BlockChest.func_176456_n(BlockChest.java:541) ~[api.class:?]
	at net.minecraft.block.BlockChest.func_176457_m(BlockChest.java:536) ~[api.class:?]
	at net.minecraft.block.BlockChest.func_189418_a(BlockChest.java:460) ~[api.class:?]
	at net.minecraft.block.BlockChest.func_180676_d(BlockChest.java:444) ~[api.class:?]
	at net.minecraft.block.BlockChest.func_180639_a(BlockChest.java:421) ~[api.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:446) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more

**Comment by marvin-roesch** [comment] 2018-01-09 12:07
Duplicate of #4669. Update Optifine and refer to the forums for support in the future.

**Closed as completed** 2018-01-09 17:56 UTC
