### ISSUE TITLE
[1.18.2] forge:tag_empty recipe conditional broken on first load

### ISSUE THREAD

**Issue by bdew** [MinecraftForge/MinecraftForge#8509] opened 2022-03-12 13:20 UTC
TagEmptyCondition is checking against Registry.ITEM.getTag which is empty at that point
after /reload it works (but presumably is checking against tags from previous load)

**Comment by KnightMiner** [comment] 2022-03-12 16:01
This issue was mentioned on #8498, not sure if it counts as a duplicate. See [this comment](https://github.com/MinecraftForge/MinecraftForge/issues/8498#issuecomment-1059760284)

**Comment by sciwhiz12** [comment] 2022-03-26 05:48
Confirmed on 1.18.2-40.0.32 in my Forgedev workspace. As the author surmises and as I've explained in https://github.com/MinecraftForge/MinecraftForge/issues/8498#issuecomment-1079612143, this is because the resolution of the values of tags must not be done during recipe deserialization.

Because of that and the fact that we cannot delay the resolution of tags until after recipe deserialization here since the tag's contents will determine whether the recipe is deserialized or not, the only solution I see here is the removal of `TagEmptyCondition`/`forge:tag_empty` entirely.

**Comment by sciwhiz12** [comment] 2022-03-28 00:30
Further discussion in Discord brought up two other possible solutions (which I note here so they aren't buried in Discord):
 - Implementing a second pass of recipe conditions after tags are bound, so tag-using conditions have an opportunity to work as expected. (Suggested by @KnightMiner)
 - Making available somehow (possibly through a `static` field) the `TagManager` to recipe conditions, which they can pull the tag values information from instead of the registries. (Suggested by @Technici4n)

**Comment by KnightMiner** [comment] 2022-03-28 05:15
A third option is one I will most likely use as a workaround for now: using empty tags in my recipes, then conditioning the recipes matches on not having an empty tag. Any recipes with the empty tags will hide in JEI. Worth nothing vanilla already does this with their recipes (see `Recipe#isIncomplete`, hides things from the recipe book if any ingredient is empty), though forge's "make empty tags a renamed barrier" might break the feature. Might be worth rethinking that feature as a fix for this issue.

----

Of the two solutions suggested above, I prefer the second pass as that lets us use it for other datapack content (e.g. a recipe conditioned on a server config option or on something in worldgen), making tag manager static only fixes works around this one problem without additional flexibility, and possibly in a way that would break again if mojang changes datapacks again.

**Comment by Technici4n** [comment] 2022-04-02 07:30
Fixed by #8546.

**Closed as completed** 2022-04-02 07:55 UTC
Labels: Regression, Confirmed, 1.18
