### ISSUE TITLE
[1.8.9] (MDK) LAN mode sends packets with wrong discriminator

### ISSUE THREAD

**Issue by gigaherz** [MinecraftForge/MinecraftForge#2373] opened 2016-01-14 17:17 UTC
I just tested my mod in LAN mode, and I was receiving packets with strange data.

@williewillus told me on IRC it appears LAN mode always uses discriminator 0 instead of the proper one.

**Comment by williewillus** [comment] 2016-01-14 17:30
Occurred to me with ProjectE as well.
Host is fine, any other clients connected to lan always would get crashed as the wrong packet got used with the wrong handlers. (If I recall correctly, the proper packets got sent, but always appeared to the LAN client as discriminator 0, and would be processed as such. Usually crashing said client.)

**Comment by ShetiPhian** [comment] 2016-01-14 17:50
I was having a similar issue the other day, but the discriminator wasn't being set to 0, it was being dropped and the following integer in my packet was being used.

This didn't happen on sendToServer or sendTo but happened every time with sendToAllAround.
it might be related to this error that was fixed in the past: https://github.com/MinecraftForge/MinecraftForge/issues/1908

I haven't looked into the bug, but have coded a quick workaround

I gather a list of players around a point and send the packet like this:
```
for (EntityPlayerMP player : players) { this.simplenetwork.sendTo(packet, player); }
```

**Comment by LexManos** [comment] 2016-01-14 20:04
I would still like to see a way to reproduce this.
I'd rather not have work around for real problems.
There is no reason there should be an issue with the selection process here.

**Comment by Azanor** [comment] 2016-01-16 10:53
I am experiencing the exact same problem with sendToAllAround in LAN mode. If I send the packets to each player manually everything is fine.
The problem is very easy to reproduce.
https://github.com/Azanor/thaumcraft-5/issues/227
https://github.com/Azanor/thaumcraft-5/issues/244

**Comment by gegy1000** [comment] 2016-01-16 11:10
JurassiCraft is also having this problem, or similar. It seems like it's not just the discriminator getting received / sent incorrectly, but also every other value on the packet.

**Comment by gigaherz** [comment] 2016-01-16 13:46
As @ShetiPhian said, the issue is that the discriminator byte is somehow not in the array when it's decoded, so the first byte, which should be the discriminator, is actually the first byte of the message, and every other byte is also shifted by one.

In my case I expected a packet like (using [] to delimit the numbers):
```[01] [00 00 00 16] [00 00 00 01] [00 ....```
instead I received:
```[00] [00 00 16 00] [00 00 01 00] [....```

I do not know if the issue was on sending, with the byte not being added, or somehow skipping the byte on the receiving side.

**Comment by cpw** [comment] 2016-01-16 19:41
Weird..

**Closed** 2016-01-16 21:35 UTC
