### ISSUE TITLE
scaffold block on fire

### ISSUE THREAD

**Issue by SpinHD** [MinecraftForge/MinecraftForge#9368] opened 2023-03-04 17:43 UTC
Minecraft Version: 1.19

Forge Version: 43.2.0 to 43.2.6

Good day my problem is that in the forge versions the scaffolding block starts to catch fire, this is not the case in the vanilla game please fix this bug

**Comment by Matyrobbrt** [comment] 2023-03-04 17:49
Duplicate of #8449

**Closed as completed** 2023-03-04 17:49 UTC
