### ISSUE TITLE
[1.11] Legless Chickens and Hopper Clock issues

### ISSUE THREAD

**Issue by Ristellise** [MinecraftForge/MinecraftForge#3415] opened 2016-11-18 14:03 UTC
Currently when forge Version: 13.19.0.2149 is installed. Creating a hopper clock and dropping in an item crashes forge
[gist crash log](https://gist.github.com/Joshwoo70/d19368121d3a2ab11de077a02e70a97f)
How to reproduce, Drop in an item with 2 hoppers facing each other as shown.
![2016-11-18_22 00 46](https://cloud.githubusercontent.com/assets/7894419/20432572/c74ba2e8-adda-11e6-8b5b-af37b8069b03.png)
Chicken appears to have no legs when facing towards the player. the front texture is missing.
![2016-11-18_21 52 53](https://cloud.githubusercontent.com/assets/7894419/20432566/ba0711b2-adda-11e6-8d01-efbdb01aea68.png)

**Comment by shadowfacts** [comment] 2016-11-18 22:21
The hopper issue has somehow been fixed between 2150 and the latest on GitHub, so probably by #3392.

**Comment by shadowfacts** [comment] 2016-11-18 22:25
I'm also unable to reproduce the chicken issue with 2150 or 2149:

![2016-11-18_17 23 36](https://cloud.githubusercontent.com/assets/7091588/20448836/ecee41ee-adb3-11e6-95d0-569f83aa35fc.png)

**Comment by LexManos** [comment] 2016-11-18 23:07
Ya unable to reproduce chicken issue, and dont combine issues.
Closing cuz hoppers are fixed.

**Closed as completed by LexManos** 2016-11-18 23:07 UTC
