### ISSUE TITLE
[1.12] guiToasts?!

### ISSUE THREAD

**Issue by CluelessPhil** [MinecraftForge/MinecraftForge#4147] opened 2017-07-07 20:44 UTC
So, there's this crash i'm getting (its continuous)  that has something weird with toast. This crash didn't happen the first time I loaded the Test Pack (for an update and then on the same pack no modifications made, it had this crash). This also happened on the newly downloaded profile of the modpack on the Twitch App. I'm so confused of this crash, please help. Here's the crash: [crash-2017-07-07_16.36.56-client.txt](https://github.com/MinecraftForge/MinecraftForge/files/1132277/crash-2017-07-07_16.36.56-client.txt)

**Comment by marvin-roesch** [comment] 2017-07-07 20:46
This is a duplicate of #4124 and can be closed.

**Closed as completed** 2017-07-07 20:46 UTC
