### ISSUE TITLE
Window not realizable after exiting full screen mode.

### ISSUE THREAD

**Issue by LapisSea** [MinecraftForge/MinecraftForge#2479] opened 2016-02-17 08:27 UTC
The MC window seems to be unrealizable after exiting full screen mode (aka clicking  F11).

**Comment by williewillus** [comment] 2016-02-17 14:07
Vanilla bug

**Comment by LexManos** [comment] 2016-02-17 20:10
We've been getting some reports of this and it sounds more like a lwjgl issue or something. As it only happens on some systems. I'm closing thing because its not a bug on Forge's end. If you happen across of a fix that Forge can patch in let us know.

**Closed by LexManos** 2016-02-17 20:10 UTC
