### ISSUE TITLE
Door Disappearing is Still An Issue

### ISSUE THREAD

**Issue by Orange1861** [MinecraftForge/MinecraftForge#3160] opened 2016-08-04 06:57 UTC
The door disappearing bug is still an issue in forge 2044.

**Comment by williewillus** [comment] 2016-08-04 12:38
You're going to need more details than tjay

**Comment by Orange1861** [comment] 2016-08-04 13:46
The bug where the top half or the entire door visually disappears.

**Comment by williewillus** [comment] 2016-08-04 16:20
Bug reporting 101:
* Version (try the latest build)
* Precise setup 
* Precise steps to reproduce

**Comment by williewillus** [comment] 2016-08-04 16:20
I cannot reproduce this in 2044

**Comment by Orange1861** [comment] 2016-08-04 18:36
There is a chance when you log back onto a world, a door can visually disappear.

**Comment by raoulvdberge** [comment] 2016-08-04 19:06
Are you *sure* you are on Forge 2044?

Check the start screen what version it says (you may have updated wrongly).

**Comment by Orange1861** [comment] 2016-08-04 19:16
What I'm saying is that the two fixes that "fixed" this problem didn't work, and yes, I was using 2044 when I reported this bug.

**Comment by williewillus** [comment] 2016-08-04 19:19
Your steps to reproduce are poor/absent.

When I say precise I mean step by step, e.g.

1. Install Forge 4045
2. Create superflat world and set to peaceful mode
3. Spam doors in various orientations and rotations
4. Relog 
5. Doors should be missing

I still stand that I cannot reproduce this, so not sure what is up with your install

**Comment by Orange1861** [comment] 2016-08-04 20:04
It is random and difficult to reproduce. Why do you think that 2 fixes to fix one thing have been unsuccessful.

**Comment by LexManos** [comment] 2016-08-04 20:08
Closing due to stupidity.
Please report issues correctly.
I have done extensive testing in the conditions of the reported issues. I have literally replicated the fix for ALL possible variants of the issue in our list.
So unless some mod is hacking around how a registry works then its fixed.
Actually provide details if you're gunna suggest something is wrong, especially if it's been verified to be fixed.
The first fix DID fix the fist problem that as shown. The second fix fixed all others.

**Closed by LexManos** 2016-08-04 20:08 UTC
