### ISSUE TITLE
onEntityDamaged is called twice for the mainhand enchantment

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#6556] opened 2020-03-09 09:33 UTC
**Minecraft Version:** 1.14 & 1.15
**Related mc issue:** MC-131637 (there's a message about this bug in)
**Forge Version:** all

**Steps to Reproduce:**
 1. apply an enchantment using onEntityDamaged on a weapon in mainhand
 2. hit a creature
 3. the method onEntityDamaged is called twice

**Description of issue:**
```java
   public static void applyArthropodEnchantments(LivingEntity user, Entity target) {
      EnchantmentHelper.IEnchantmentVisitor enchantmenthelper$ienchantmentvisitor = (p_212574_2_, p_212574_3_) -> {
         p_212574_2_.onEntityDamaged(user, target, p_212574_3_);
      };
      if (user != null) {
         applyEnchantmentModifierArray(enchantmenthelper$ienchantmentvisitor, user.getEquipmentAndArmor()); // both hands & armor
      }

      if (user instanceof PlayerEntity) {
         applyEnchantmentModifier(enchantmenthelper$ienchantmentvisitor, user.getHeldItemMainhand()); // mainhand
      }
   }
```

**Comment by LexManos** [comment] 2020-03-09 09:47
Update to a modern/supported version if you wish to receive support. And use the forums for basic things.

**Comment by ghost** [comment] 2020-03-09 09:47
1.15/1.16 is not enough? in fact your trouble is probably you don't read, and it's really ennoying to see you all the time be like this.

**Comment by LexManos** [comment] 2020-03-09 09:51
You posted a version in the format the mimics the standard MCVersion-ModVersion, so I may of read it wrong. Not to mention the fact that you stated 1.16, which is a version that does not exist yet. Specify specific versions. If it's something that can be reproduced in just vanilla/Forge then we can address. However, this sounds like you're going through the basic misunderstanding of client/server threads. Again, use the forums to flesh out your issue.

**Comment by Unnoen** [comment] 2020-03-09 09:51
It was an accident, I myself almost closed this thinking it was for 1.12.

**Comment by ghost** [comment] 2020-03-09 09:54
damage are server side.
edit : i agree that the version was not necessarily ideal for forge but it was more to show the affected versions (even i didn't make the tests in 1.16 yet)

**Comment by Unnoen** [comment] 2020-03-09 10:14
The issue has been around for some time and Mojang haven't shown too much interest in fixing it, although it does appear as a bug, it may break functionality expected by vanilla players.

It also isn't too simple a fix, because logically, you'd only want a weapon enchantment to apply when you're holding it in the hand you attacked with. But not all the information is there for that.

Unless Mojang shows that they want to fix this, we're not going to attempt to change it in Forge for the listed reasons above.

**Closed as completed by Unnoen** 2020-03-09 10:14 UTC

**Comment by ghost** [comment] 2020-03-09 11:00
@Unnoen I have a doubt about your answer being not a native english, i don't want the enchantment to only apply for the hand hitting the creature, i want this enchantment only present on this weapon (with no offhand) to only apply once and not twice.

**Comment by ghost** [comment] 2020-03-10 11:06
![bug](https://user-images.githubusercontent.com/17954109/76306612-86ee4e80-62c7-11ea-8dbf-95a54bde4f39.jpg)
good morning, i try with picture ;)
