### ISSUE TITLE
[1.13.2] genEclipseRuns not working

### ISSUE THREAD

**Issue by yuxuanchiadm** [MinecraftForge/MinecraftForge#5568] opened 2019-02-26 01:19 UTC
genEclipseRuns task generate duplicated MOD_CLASSES entries like this:
```
modid%%C:\path\to\dir\bin\main;modid%%E:\path\to\dir\bin\main;modid%%E:\path\to\dir\bin\main;modid%%E:\path\to\dir\bin\main
```
And mod can not be loaded.

**Comment by 3TUSK** [comment] 2019-02-26 01:25
Duplicate of #5556 and thus wrong repo, correct ticket is PR MinecraftForge/ForgeGradle#562?

**Comment by yuxuanchiadm** [comment] 2019-02-26 01:28
> Duplicate of #5556 and thus wrong repo, correct ticket is PR [MinecraftForge/ForgeGradle#562](https://github.com/MinecraftForge/ForgeGradle/pull/562)?

Not same issue. Anything related to mod files just not listed in `MOD_CLASSES`. Only `bin\main` does.

**Comment by yuxuanchiadm** [comment] 2019-02-26 01:40
So either ForgeGradle need to recursively generate all entries in `bin\main` directory or FML need to traversing all files in `MOD_CLASSES` and add them into `explodedTargets` will fix this issues.

**Comment by yuxuanchiadm** [comment] 2019-02-26 01:42
Second solution is preferred imo. Otherwise we need to run `.\gradlew genEclipseRuns` everytimes when added or removed files from proejct.

**Comment by yuxuanchiadm** [comment] 2019-02-26 02:18
I see the problem. At:
https://github.com/MinecraftForge/MinecraftForge/blob/af98088d04186452cb364280340124dfd4766a5c/src/fmllauncher/java/net/minecraftforge/fml/loading/FMLCommonLaunchHandler.java#L101
We expected first appeared path to be resources. And others to be classes. This makes no sense at least at `MOD_CLASSES`'s syntax level. Solution will be unified treat them. Do both resources and classes search for them. Or at least we need to change the syntax of `MOD_CLASSES`. Otherwise same entry appeared twice when resources and classes in same directory makes no sense.

**Comment by LexManos** [comment] 2019-03-11 23:18
This should be fixed, but if not, report properly to the FG repo.

**Closed as completed by LexManos** 2019-03-11 23:18 UTC
