### ISSUE TITLE
DimensionTypes from server are not synced to client

### ISSUE THREAD

**Issue by Gegy** [MinecraftForge/MinecraftForge#6147] opened 2019-09-11 15:07 UTC
Currently, while `ModDimension` is synced to clients from the server, `DimensionType` is not. This causes issues because the values in `DimensionType` are stilled used in many cases on the client, and mods may also require them. One instance where the `DimensionType` is used on the client is initialization of `ClientWorld` -- if it is missing on the client, the client will crash with a NPE.

This leads to horrible workarounds to sync such as [this](https://github.com/Cryptic-Mushroom/The-Midnight/blob/c38d3ae8e904b3f0ac389ac471ab2a41303f5ab8/src/main/java/com/mushroom/midnight/common/registry/MidnightDimensions.java#L38-L64) (shameful 😅)
Though this is a simple case, because Forge intends to be able to support dimensions created dynamically. DimensionTypes would need to be synced as they are created

**Comment by Gegy** [comment] 2019-10-03 18:29
Seems like this might have been addressed in https://github.com/MinecraftForge/MinecraftForge/commit/48735c3946516ece5feb60bcc0d13f553b2d6122

Wonder the implication of not syncing `DimensionType`s that the player is not in -- I guess it would only affect mods that compare dimensions with the `DimensionType` instead of `ModDimension`

**Comment by willis81808** [comment] 2019-10-04 10:35
I have not been able to test it yet, but according to the changelog for build 1.14.4-28.1.31 this issue should be resolved. In my mod, an arbitrary number of dimensions could be generated (all sharing a single `ModDimension`), and prior to any workaround a player could enter one of these dimensions, but the client would still believe it was in the overworld/nether/end (whatever dimension they'd been in before), and players would be unable to finish joining the server if they had previously logged out while in one of these such dimensions. 

For any mod that doesn't have a fixed number of dimensions the client could know about without asking the server, this issue was completely game-breaking.

**Comment by Unnoen** [comment] 2019-10-15 22:47
Have you had a chance to test with the new build? Is this issue resolved?

**Comment by willis81808** [comment] 2019-10-16 07:39
Sorry for the delay. I hadn't had a chance to test it, but I have now. From all I can determine the issue is entirely resolved, and everything works as expected/intended now (without all the hack-y workarounds)

**Comment by Unnoen** [comment] 2019-10-16 22:50
Closing issue then, if it hasn't been resolved, feel free to reopen.

**Closed as completed by Unnoen** 2019-10-16 22:50 UTC
Labels: Bug, Needs Update, 1.14

**Comment by tterrag1098** [comment] 2019-10-17 23:23
This was resolved by https://github.com/MinecraftForge/MinecraftForge/commit/48735c3946516ece5feb60bcc0d13f553b2d6122
