### ISSUE TITLE
Backport of Stemblock Patch to 1.19.2

### ISSUE THREAD

**Issue by ItsDaveMate** [MinecraftForge/MinecraftForge#9357] opened 2023-02-25 19:20 UTC
**Minecraft Version:** {1.19.2}

**Forge Version:** {Forge version. *43.2.6*}

**Steps to Reproduce:**
 1. Place a mud block next to farmland with melon stem
2. Make sure there is a water source nearby
3. Wait for melon to be placed on the mud block

**Description of issue:**
Upon placing the melon seed it will not work in any way, despite fixing this issue in Forge Minecraft 1.19.3 (the stemblock patch referenced in #9336 and #9337) it won't work in 1.19.2 and needs to be backported.

**Comment by ferriarnus** [comment] 2023-02-25 19:42
The backport has been made, but not merged yet, see #9338

**Comment by ItsDaveMate** [comment] 2023-03-01 09:04
Any approximate on when it will be merged? I just want to make the most powerful Melon farm in the history of 1.19.2 man.

**Comment by sciwhiz12** [comment] 2023-03-09 17:52
Duplicate of #9336

**Closed as not planned by sciwhiz12** 2023-03-09 17:52 UTC
