### ISSUE TITLE
Minecraft client crashes when trying to load realms

### ISSUE THREAD

**Issue by jbatesy** [MinecraftForge/MinecraftForge#5877] opened 2019-06-27 11:53 UTC
**Minecraft Version:** {Minecraft version}
1.14.3
**Forge Version:** {Forge version. *Version number, not latest/rb*}
27.0.13
**Full Log:** {Link to GitHub Gist with full latest.log}
https://gist.github.com/jbatesy/e95a3c6770e5ec78aec8ce82e7b167f5
**Steps to Reproduce:**
1. STart minecraft (1.14.3) with latest forge version (27.0.13) 
2. Click on "Minecraft Realms"
3. Minecraft crashes

**Description of bug:**
Minecraft crashes when attempting to click on realms with Forge installed.

**Comment by Darkhax** [comment] 2019-06-28 23:03
This is a duplicate of https://github.com/MinecraftForge/MinecraftForge/issues/5864 they have no immediate plans to fix it.

**Closed as completed** 2019-06-29 11:22 UTC
Labels: Bug
