### ISSUE TITLE
[1.17] `Minecraft.getInstance().getMainRenderTarget().enableStencil()` breaks depth testing on all RenderTargets created beforehand

### ISSUE THREAD

**Issue by tasgon** [MinecraftForge/MinecraftForge#7991] opened 2021-08-08 05:09 UTC
**Minecraft Version:** 1.17

**Forge Version:** Any version of 37

**Logs:** `OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Depth formats do not match.'`

**Steps to Reproduce:**
 1. Run the Forge test client with the `StencilEnableTest` mod enabled (true by default if cloning master).
 2. Turn on Fabulous graphics.
 3. Look at water or any translucent block.

**Description of issue:** When Fabulous mode is enabled, Minecraft creates 5 `RenderTarget`s through `LevelRenderer.initTransparency()`. In the main render loop, the depth attachment from the main render target is copied onto those targets for their rendering purposes. However, when the stencil is enabled, the main render target has its depth attachment updated but the other render targets are (seemingly) not updated, which causes a mismatch between depth formats when they attempt to read in the main target's depth texture data.

![2021-08-08_01 07 54](https://user-images.githubusercontent.com/10052313/128621524-bd0b9264-c7b6-4a73-b906-e062793aeb00.png)

**Comment by malte0811** [comment] 2021-08-08 10:19
Duplicate of #6995, will be fixed by #7978 (assuming that gets merged).

**Closed as completed** 2021-08-15 14:46 UTC
