### ISSUE TITLE
[1.18.2] - `cachePackAccess = true` increase significant (5x) loading time of mod packs.

### ISSUE THREAD

**Issue by MarkusBordihn** [MinecraftForge/MinecraftForge#8962] opened 2022-08-13 14:28 UTC
**Minecraft Version:** 1.18.2

**Forge Version:** 1.18.2 - 40.1.73

**Steps to Reproduce:**
 1. Load a huge mod pack with `cachePackAccess = true` and stop the loading time.
 2. Change `cachePackAccess = false` and stop the loading time 
 3. Compare the two loading times.

**Description of issue:**
 `cachePackAccess = true` ~ 10:58.755 min
 `cachePackAccess = false` ~ 02:21.096 min

I would expect that the new option (which is enabled by default) is not causing such a increase (5x) in the loading times.
I assume that is maybe caused by long timeouts during scanning, loading or parsing the relevant resources.

The issue is not happening with former forge versions, so it's seems to be related to the following change:
https://github.com/MinecraftForge/MinecraftForge/commit/4df024ef43524d8ec48928c70f561903f7a8e184

I'm using the Curse Forge Launcher for loading the mod pack like:
https://www.curseforge.com/minecraft/modpacks/bos-adventure-world/files/3932653

**Comment by sciwhiz12** [comment] 2022-08-13 14:57
I've been informed by the author of the original caching PR #8829, @OrionDevelopment, that this increase in loading time is an intentional side-effect of the new resource caching system. 

Loading time for worlds is decreased in exchange for increased loading time on startup, as the caching system eagerly caches resource paths (not the contents, only names and paths) after resource packs are loaded. World loading improvement is ~10–15x while game loading regression is ~5x, according to him. (Bear in mind that differences in modpacks and hardware can cause variations in speed.)

Closing as working as intended.

**Comment by marchermans** [comment] 2022-08-13 15:03
@MarkusBordihn What is are your options for offthread indexing?
Also what is your hardware configuration?

**Comment by MarkusBordihn** [comment] 2022-08-13 15:17
Thanks for the feedback. But I'm not really understand the math here, it's like comparing apples with pears.

Example loading time until remote world (from dedicated server) is loaded:
cachePackAccess = true ~ 10:58.755 min (client loading)+ 0:24.458 min (world loading)
cachePackAccess = false ~ 02:21.096 min (client loading) + 0:47.716 min  (world loading)

This means even if the "world loading time" is improved the total loading time until the player is in the world is still higher by factor 3x (~11:22min vs ~3:18min). In general I never saw a world loading which took longer than 2 minutes to load.

But as long I could deactivate the feature it's fine with me.

**Comment by MarkusBordihn** [comment] 2022-08-13 15:27
> What is are your options for offthread indexing?

I'm using the default values from CurseForge and Forge, so nothing special was setup or specific here, beside of the memory with 16GB.

> Also what is your hardware configuration?

My hardware should not be the bottleneck here, its a i7-11700k 3.60GHz, RTX 3090 and 64 GB Ram 2666Mhz. Minecraft is loaded from an Samsung SSD 860 Pro.

**Comment by eerussianguy** [comment] 2022-08-13 15:36
It is very dependent on the exact mod situation and whether or not you are in a dev environment. For me, this took world load times in dev from 6 to 1 minute, and out of dev from 2 min to like, 20 seconds.

**Comment by MarkusBordihn** [comment] 2022-08-13 16:17
I agree that it's improving things for specific use cases like mod development or smaller mod packs, which I notice myself.

As shown with my example it's seem that currently this optimization is contra productive for larger mod packs and the day by day users. 

Anyways, I don't want to argument for or against this optimization. 
I just want to report that there is reproducible issues with larger mods packs and this optimization, which was defined as "working as intended" from your side.

**Comment by marchermans** [comment] 2022-08-13 16:26
> Thanks for the feedback. But I'm not really understand the math here, it's like comparing apples with pears.
> 
> Example loading time until remote world (from dedicated server) is loaded: cachePackAccess = true ~ 10:58.755 min (client loading)+ 0:24.458 min (world loading) cachePackAccess = false ~ 02:21.096 min (client loading) + 0:47.716 min (world loading)
> 
> This means even if the "world loading time" is improved the total loading time until the player is in the world is still higher by factor 3x (~11:22min vs ~3:18min). In general I never saw a world loading which took longer than 2 minutes to load.
> 
> But as long I could deactivate the feature it's fine with me.

Do you know how to make a profile of the application when it starts using something like VisualVM?
That would allow us to verify what is going on here.

**Comment by MarkusBordihn** [comment] 2022-08-13 16:36
Sorry but I see no reason to spend my time on an issue which is closed and marked as "Wont fix/Worked As Intended".
I provided all needed details to reproduce the issue, if needed.

**Comment by marchermans** [comment] 2022-08-13 16:52
Yeah except I can't reproduce this, and if you consider this an issue, I might spend time on fixing it.

**Comment by LexManos** [comment] 2022-08-13 17:00
A default option should  not bee having any SIGNIFICANNT impact on loading times.
If you set indexVanillaPackCachesOnThread to true, then it'll doo everything on thread and would explain your issue.
However, we need more information.

**Comment by MarkusBordihn** [comment] 2022-08-13 17:42
Thanks for re-opening the issue. Unfortunately some of the comments give me the impression that you haven't try to reproduce the issue with the CurseForge launcher and the provided mod pack on your side.

Let me clarify some additional details:

- The mod pack was not downloaded from your side over CurseForge during the first few comments and about 10 min after the issue was closed.
- The mod pack includes all config files like the `forge-common.toml` which shows that it's using the default settings like `indexVanillaPackCachesOnThread = false` and `indexModPackCachesOnThread = false`.
- I got two independent user reports (pm) for the increased loading time and was also able to reproduce the issue reliable on 3 different machines (2xdesktop / 1xlaptop) myself with the provided mod pack. Otherwise I wouldn't report this as an issue.

I will have no time today for further testing, but happy to discuss this issue more in detail over Discord tomorrow or so.
Please let me know if you have a dedicated channel or if I should just ping someone directly?

Wish you a happy rest of your day. Keep up the good work.

**Comment by LatvianModder** [comment] 2022-08-13 18:00
Is this a situation where magnitude of optimisation doesnt matter, because you decrease worldgen time 10x (60 seconds to 6 seconds, 1 min difference) but increase loading time 5x (2 mins to 10 mins, 8 min difference), in total making it slower?

**Comment by marchermans** [comment] 2022-08-13 18:21
> Is this a situation where magnitude of optimisation doesnt matter, because you decrease worldgen time 10x (60 seconds to 6 seconds, 1 min difference) but increase loading time 5x (2 mins to 10 mins, 8 min difference), in total making it slower?

Except that I can not reproduce it, except for with his modpack as of now.
We are still trying to figure out what the exact cause is here.

We are 100% sure that on 1.19 it does not happen, but on 1.18 this is the first time we are aware of it.

**Comment by MarkusBordihn** [comment] 2022-08-13 19:15
![image](https://user-images.githubusercontent.com/12183293/184507550-ed0cf9fe-636d-44d8-9629-caa6673b305a.png)

I just created a sampler for the loading process with `cachePackAccess = true`, seems related to the way how the files are handled / processed.
Will take a deeper look tomorrow and happy to discuss this directly in discord, if needed.

**Comment by marchermans** [comment] 2022-08-13 20:23
> ![image](https://user-images.githubusercontent.com/12183293/184507550-ed0cf9fe-636d-44d8-9629-caa6673b305a.png)
> 
> I just created a sampler for the loading process with `cachePackAccess = true`, seems related to the way how the files are handled / processed. Will take a deeper look tomorrow and happy to discuss this directly in discord, if needed.

I get the same results, interestingly enough the code for the index call only takes several seconds on my machine.....
I wonder where the remaining slow down is coming from.
@pupnewfster Might be right the call: `Path.getFileName().toString()` might be abotleneck here.

Will debug tomorrow.

**Comment by LatvianModder** [comment] 2022-08-14 11:22
Do you have network drives, SMB shares? If mine are disconnected, it can freeze up to several minutes, even if no files are pulled from them. Just listing available drives freezes up everything. `Path#getFileName()` could potentially cause that.

**Comment by MarkusBordihn** [comment] 2022-08-14 12:16
I traced some of the file IO activities and I think I found something interesting.

<img width="1520" alt="image" src="https://user-images.githubusercontent.com/12183293/184535955-6e0240f0-fb68-4593-8a18-e985ba4014ac.png">

As we know the process scanning the .jar take a lot of time even it shouldn't. The screenshot above shows that the total disc activity e/a is only 72 KB/s (total system wide) so there is a lot of resources left for just reading the files from the disc.

After this I activated the "debug" options of CurseForge to check any log output and got 726MB for log entries with `cachePackAccess = true` but only about 209MB for `cachePackAccess = false`.

According the debug logs I could see a kind of loop with error like:
```
[14Aug2022 13:47:44.513] [Worker-Main-6/DEBUG] [net.minecraftforge.resource.ResourceCacheManager$NamespacedResourceCacheManager/]: Failed to cache resources, the directory does not exist!
java.nio.file.NoSuchFileException: /data/waila
[14Aug2022 13:47:44.513] [Worker-Main-13/DEBUG] [net.minecraftforge.resource.ResourceCacheManager$NamespacedResourceCacheManager/]: Failed to cache resources, the directory does not exist!
java.nio.file.NoSuchFileException: /assets/waila
[14Aug2022 13:47:44.513] [Worker-Main-5/DEBUG] [net.minecraftforge.resource.ResourceCacheManager$NamespacedResourceCacheManager/]: Failed to cache resources, the directory does not exist!
java.nio.file.NoSuchFileException: /data/waila
[14Aug2022 13:47:44.513] [Worker-Main-16/DEBUG] [net.minecraftforge.resource.ResourceCacheManager$NamespacedResourceCacheManager/]: Failed to cache resources, the directory does not exist!
java.nio.file.NoSuchFileException: /assets/waila
[14Aug2022 13:47:44.513] [Worker-Main-4/DEBUG] [net.minecraftforge.resource.ResourceCacheManager$NamespacedResourceCacheManager/]: Failed to cache resources, the directory does not exist!
java.nio.file.NoSuchFileException: /data/waila
[14Aug2022 13:47:44.514] [Worker-Main-7/DEBUG] [net.minecraftforge.resource.ResourceCacheManager$NamespacedResourceCacheManager/]: Failed to cache resources, the directory does not exist!
java.nio.file.NoSuchFileException: /assets/waila
[14Aug2022 13:47:44.514] [Worker-Main-2/DEBUG] [net.minecraftforge.resource.ResourceCacheManager$NamespacedResourceCacheManager/]: Failed to cache resources, the directory does not exist!
java.nio.file.NoSuchFileException: /data/waila
[14Aug2022 13:47:44.514] [Worker-Main-3/DEBUG] [net.minecraftforge.resource.ResourceCacheManager$NamespacedResourceCacheManager/]: Failed to cache resources, the directory does not exist!
java.nio.file.NoSuchFileException: /data/waila
...
```

This looks for me that even in the case of an error like "directory does not exists" it retries to find the directory several time which leads to waste resources and maybe to the additional loading time.

I see this kind of entries and repeating pattern for most of the mods of the mod pack.

**Comment by marchermans** [comment] 2022-08-14 12:29
@cpw This now becomes your area of expertise I assume some change in UFS is needed to prevent the weird NSFE's from occuring?

**Comment by MarkusBordihn** [comment] 2022-08-14 12:55
I just checked the log more in detail and it seems that the former errors happening only for about 20 secs.
See log snippet: https://gist.github.com/MarkusBordihn/0f55612ef7058f5a7590750e08d1ef4d

Most of the time is lost in the following parts `cachePackAccess = true`:
```
[14Aug2022 13:49:38.669] [Worker-Main-12/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'minecraft:block' referenced from: domum_ornamentum:blockpillar#column=pillar_base: java.io.FileNotFoundException: minecraft:models/block.json
[14Aug2022 13:50:03.198] [Worker-Main-12/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Exception loading blockstate definition: byg:blockstates/potted_hydrangea_bush.json: java.io.FileNotFoundException: byg:blockstates/potted_hydrangea_bush.json
[14Aug2022 13:50:03.199] [Worker-Main-12/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Exception loading blockstate definition: 'byg:blockstates/potted_hydrangea_bush.json' missing model for variant: 'byg:potted_hydrangea_bush#'
[14Aug2022 13:50:32.404] [Worker-Main-12/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'dragonmounts:block/dragon_egg' referenced from: dragonmounts:dragon_egg#: java.io.FileNotFoundException: dragonmounts:models/block/dragon_egg.json
[14Aug2022 13:51:28.943] [Worker-Main-12/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'minecraft:cultivator_top' referenced from: parkbuilder:cultivator#facing=north,half=upper,lit=true: java.io.FileNotFoundException: minecraft:models/cultivator_top.json
[14Aug2022 13:51:28.977] [Worker-Main-12/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'minecraft:incubator_top' referenced from: parkbuilder:incubator#facing=north,half=upper,lit=true: java.io.FileNotFoundException: minecraft:models/incubator_top.json
[14Aug2022 13:52:02.690] [Worker-Main-12/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Exception loading blockstate definition: rftoolsbuilder:blockstates/invisible_mover_block.json: java.io.FileNotFoundException: rftoolsbuilder:blockstates/invisible_mover_block.json
[14Aug2022 13:52:02.690] [Worker-Main-12/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Exception loading blockstate definition: 'rftoolsbuilder:blockstates/invisible_mover_block.json' missing model for variant: 'rftoolsbuilder:invisible_mover_block#'
[14Aug2022 13:52:34.659] [Worker-Main-12/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'minecraft:item/celeste2a' referenced from: nethers_exoticism:rambutan_shield#inventory: java.io.FileNotFoundException: minecraft:models/item/celeste2a.json
[14Aug2022 13:52:34.664] [Worker-Main-12/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'minecraft:item/celeste2b' referenced from: nethers_exoticism:rambutan_shield#inventory: java.io.FileNotFoundException: minecraft:models/item/celeste2b.json
[14Aug2022 13:52:36.897] [Worker-Main-12/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'refinedstorage:cover#inventory' referenced from: refinedstorage:cover#inventory: java.io.FileNotFoundException: refinedstorage:models/item/cover.json
[14Aug2022 13:52:36.902] [Worker-Main-12/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'refinedstorage:hollow_cover#inventory' referenced from: refinedstorage:hollow_cover#inventory: java.io.FileNotFoundException: refinedstorage:models/item/hollow_cover.json
[14Aug2022 13:53:39.755] [Worker-Main-12/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'minecraft:cultivator' referenced from: parkbuilder:cultivator#inventory: java.io.FileNotFoundException: minecraft:models/cultivator.json
[14Aug2022 13:53:47.920] [Worker-Main-12/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'hole_filler_mod:block/hole_filler_block' referenced from: hole_filler_mod:hole_filler_block#inventory: java.io.FileNotFoundException: hole_filler_mod:models/block/hole_filler_block.json
[14Aug2022 13:53:47.932] [Worker-Main-12/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'hole_filler_mod:block/hole_filler_block_balanced' referenced from: hole_filler_mod:hole_filler_block_balanced#inventory: java.io.FileNotFoundException: hole_filler_mod:models/block/hole_filler_block_balanced.json
[14Aug2022 13:53:47.943] [Worker-Main-12/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'hole_filler_mod:block/hole_filler_block_smart' referenced from: hole_filler_mod:hole_filler_block_smart#inventory: java.io.FileNotFoundException: hole_filler_mod:models/block/hole_filler_block_smart.json
[14Aug2022 13:53:47.954] [Worker-Main-12/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'hole_filler_mod:block/hole_filler_block_water' referenced from: hole_filler_mod:hole_filler_block_water#inventory: java.io.FileNotFoundException: hole_filler_mod:models/block/hole_filler_block_water.json
[14Aug2022 13:53:47.959] [Worker-Main-12/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'hole_filler_mod:hole_filler_block_lava#inventory' referenced from: hole_filler_mod:hole_filler_block_lava#inventory: java.io.FileNotFoundException: hole_filler_mod:models/item/hole_filler_block_lava.json
[14Aug2022 13:53:47.964] [Worker-Main-12/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'hole_filler_mod:hole_filler_block_light#inventory' referenced from: hole_filler_mod:hole_filler_block_light#inventory: java.io.FileNotFoundException: hole_filler_mod:models/item/hole_filler_block_light.json
[14Aug2022 13:54:04.674] [Worker-Main-12/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'minecraft:useless_sword_icon' referenced from: useless_sword:uselesswordicon#inventory: java.io.FileNotFoundException: minecraft:models/useless_sword_icon.json
[14Aug2022 13:56:14.309] [Worker-Main-12/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to resolve texture reference: #missing in domum_ornamentum:block/trapdoors/trapdoor_waffle_spec
```

For reference `cachePackAccess = false`:
```
[14Aug2022 14:04:21.932] [Worker-Main-14/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'minecraft:block' referenced from: domum_ornamentum:blockpillar#column=pillar_base: java.io.FileNotFoundException: minecraft:models/block.json
[14Aug2022 14:04:22.490] [Worker-Main-14/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Exception loading blockstate definition: byg:blockstates/potted_hydrangea_bush.json: java.io.FileNotFoundException: byg:blockstates/potted_hydrangea_bush.json
[14Aug2022 14:04:22.491] [Worker-Main-14/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Exception loading blockstate definition: 'byg:blockstates/potted_hydrangea_bush.json' missing model for variant: 'byg:potted_hydrangea_bush#'
[14Aug2022 14:04:26.539] [Worker-Main-14/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'dragonmounts:block/dragon_egg' referenced from: dragonmounts:dragon_egg#: java.io.FileNotFoundException: dragonmounts:models/block/dragon_egg.json
[14Aug2022 14:04:28.621] [Worker-Main-14/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'minecraft:cultivator_top' referenced from: parkbuilder:cultivator#facing=north,half=upper,lit=true: java.io.FileNotFoundException: minecraft:models/cultivator_top.json
[14Aug2022 14:04:28.622] [Worker-Main-14/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'minecraft:incubator_top' referenced from: parkbuilder:incubator#facing=north,half=upper,lit=true: java.io.FileNotFoundException: minecraft:models/incubator_top.json
[14Aug2022 14:04:29.475] [Worker-Main-14/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Exception loading blockstate definition: rftoolsbuilder:blockstates/invisible_mover_block.json: java.io.FileNotFoundException: rftoolsbuilder:blockstates/invisible_mover_block.json
[14Aug2022 14:04:29.475] [Worker-Main-14/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Exception loading blockstate definition: 'rftoolsbuilder:blockstates/invisible_mover_block.json' missing model for variant: 'rftoolsbuilder:invisible_mover_block#'
[14Aug2022 14:04:31.808] [Worker-Main-14/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'minecraft:item/celeste2a' referenced from: nethers_exoticism:rambutan_shield#inventory: java.io.FileNotFoundException: minecraft:models/item/celeste2a.json
[14Aug2022 14:04:31.808] [Worker-Main-14/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'minecraft:item/celeste2b' referenced from: nethers_exoticism:rambutan_shield#inventory: java.io.FileNotFoundException: minecraft:models/item/celeste2b.json
[14Aug2022 14:04:31.844] [Worker-Main-14/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'refinedstorage:cover#inventory' referenced from: refinedstorage:cover#inventory: java.io.FileNotFoundException: refinedstorage:models/item/cover.json
[14Aug2022 14:04:31.845] [Worker-Main-14/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'refinedstorage:hollow_cover#inventory' referenced from: refinedstorage:hollow_cover#inventory: java.io.FileNotFoundException: refinedstorage:models/item/hollow_cover.json
[14Aug2022 14:04:32.488] [Worker-Main-14/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'minecraft:cultivator' referenced from: parkbuilder:cultivator#inventory: java.io.FileNotFoundException: minecraft:models/cultivator.json
[14Aug2022 14:04:32.545] [Worker-Main-14/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'hole_filler_mod:block/hole_filler_block' referenced from: hole_filler_mod:hole_filler_block#inventory: java.io.FileNotFoundException: hole_filler_mod:models/block/hole_filler_block.json
[14Aug2022 14:04:32.546] [Worker-Main-14/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'hole_filler_mod:block/hole_filler_block_balanced' referenced from: hole_filler_mod:hole_filler_block_balanced#inventory: java.io.FileNotFoundException: hole_filler_mod:models/block/hole_filler_block_balanced.json
[14Aug2022 14:04:32.546] [Worker-Main-14/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'hole_filler_mod:block/hole_filler_block_smart' referenced from: hole_filler_mod:hole_filler_block_smart#inventory: java.io.FileNotFoundException: hole_filler_mod:models/block/hole_filler_block_smart.json
[14Aug2022 14:04:32.546] [Worker-Main-14/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'hole_filler_mod:block/hole_filler_block_water' referenced from: hole_filler_mod:hole_filler_block_water#inventory: java.io.FileNotFoundException: hole_filler_mod:models/block/hole_filler_block_water.json
[14Aug2022 14:04:32.546] [Worker-Main-14/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'hole_filler_mod:hole_filler_block_lava#inventory' referenced from: hole_filler_mod:hole_filler_block_lava#inventory: java.io.FileNotFoundException: hole_filler_mod:models/item/hole_filler_block_lava.json
[14Aug2022 14:04:32.546] [Worker-Main-14/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'hole_filler_mod:hole_filler_block_light#inventory' referenced from: hole_filler_mod:hole_filler_block_light#inventory: java.io.FileNotFoundException: hole_filler_mod:models/item/hole_filler_block_light.json
[14Aug2022 14:04:32.764] [Worker-Main-14/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'minecraft:useless_sword_icon' referenced from: useless_sword:uselesswordicon#inventory: java.io.FileNotFoundException: minecraft:models/useless_sword_icon.json
[14Aug2022 14:04:50.860] [Worker-Main-14/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to resolve texture reference: #missing in domum_ornamentum:block/trapdoors/trapdoor_waffle_spec
```

This mean it could be that the error loop has an impact, but not sure if it is the root cause for the larger delay.

**Comment by Xetaxheb** [comment] 2022-08-31 00:23
I get tens of thousands of these 
```
 [net.minecraftforge.resource.ResourceCacheManager$NamespacedResourceCacheManager/]: Failed to cache resources, the directory does not exist!
java.nio.file.NoSuchFileException: /assets/**BLAHBLAHBLAH**
```
They give me several hundred MB to a GB of debug.log (delogger) even if cachePackAccess is false.

I'm not sure how meaningfully they increase loading time. I don't really want them happening because I believe they are crashing my launchers attempting to access those enormous logs... obviously they compress down to <2MB by the log handler so file space is obnoxious but irrelevant.

**Comment by embeddedt** [comment] 2022-09-02 13:08
Interestingly the NoSuchFileExceptions do not appear in the Forge workspace, but they do appear in a mod's development environment when it uses a version of Forge with my PR included. I'm not sure what the difference is.

**Comment by Shadows-of-Fire** [comment] 2022-09-03 18:37
Given the state of this issue, I think we may want to propose reverting this change for the 1.18 branch.  100mb+ log files that cannot be disabled are simply not acceptable, and neither is the load time difference as described here.

**Comment by Xetaxheb** [comment] 2022-09-03 19:10
My solution in the interim has been to add jvm args (yes there's probably less drastic settings) 
```
-Dforge.logging.mojang.level=fatal -Dforge.logging.console.level=fatal -Dforge.logging.file.level=fatal -Dforge.logging.debugFile.level=fatal
```
and while some aspect of my mod setup may be an issue in some way, I was getting this across multiple modpacks and it may be environment-related *somehow* but here is my wall of text/notes while I was trying to really narrow it down.. I gave up eventually and I don't expect anyone to actually read this, they're a little messy. 

[experience.txt](https://github.com/MinecraftForge/MinecraftForge/files/9483224/experience.txt)

---
and just to throw my 2 cents in on world loading vs pack loading... absolutely not worth increasing pack loading times to lower world loading times at more than a 1:1 real time ratio.. 
aka if my total time from clicking play to getting in world is longer then _what is the point?_  If there's not at least a 1:2 ratio (say 10 seconds loading, 20 seconds off world) then personally I still don't see the point. 
People don't usually go back to the main menu much without closing the pack, so unless you're loading a world at least twice then this offers no real benefit. 
_**Multiplayer also needs to be considered, and should be the main consideration, as usually the loading time into that is significantly shorter and should be the real focus here since it is reasonable to connect more than once. Is this patch even relevant to MP? Is it just increasing load times overall for MP users?**_
There *may* be some value in leaving it as an option however, if creating or entering worlds (especially well-played or complex factory-esque ones) is hanging or some other long cascading time issues are resolved by doing this then it could be of value to someone. It's important to test all use cases, maybe seek out some elaborately setup tech-complex world from someone to test with? (instead of just flatgrass) Youtube might have a let's play'er with some good one.

**Comment by embeddedt** [comment] 2022-09-04 00:14
> Is this patch even relevant to MP? Is it just increasing load times overall for MP users?

It should be. In modern versions, connecting to a server generally seems to kick off a lot of scanning of tags and reloading recipes, which requires scanning through all the mods, so a working version of this should benefit multiplayer, or at least should not slow it down.

**Comment by Shadows-of-Fire** [comment] 2022-09-04 00:25
If it's scanning the assets dirs on mp though, that's a problem.

**Comment by lukebemish** [comment] 2022-09-09 01:18
> > Is this patch even relevant to MP? Is it just increasing load times overall for MP users?
> 
> It should be. In modern versions, connecting to a server generally seems to kick off a lot of scanning of tags and reloading recipes, which requires scanning through all the mods, so a working version of this should benefit multiplayer, or at least should not slow it down.

Most tags, recipes and the like are synced from the server. The client is not actively reading `data` files when joining a multiplayer world.

**Comment by sciwhiz12** [comment] 2022-09-10 00:39
Fixed by virtue of the backported caching feature being reverted by #9026.

**Closed as completed by sciwhiz12** 2022-09-10 00:39 UTC
Labels: Regression, 1.18
