### ISSUE TITLE
[1.18.2] Forge 40.2.10 Win32/Znyonm detected by Windows Defender

### ISSUE THREAD

**Issue by shkabo** [MinecraftForge/MinecraftForge#9765] opened 2023-10-27 05:36 UTC
**Minecraft Version:** 1.18.2

**Forge Version:** 40.2.10

**Logs:** No logs (screenshot attached)

**Steps to Reproduce:**
1. Use Windows 11 with latest updates
2. Try to download forge 1.18.2-40.2.10 installer
3. Window defender blocks it with information that it detected Win32/Znyonm 

A bit more context. I'm using PrismLauncher to play Stoneblock3. All was fine, but today with latest updates of defender, it reports that forge installer has trojan in itself. I thought it was regarding PrismLauncher as it's not latest version, but tried to get it manually from your site, and still it reports the same that jar is corrupted.

**Description of issue:**
![Screenshot 2023-10-27 070504](https://github.com/MinecraftForge/MinecraftForge/assets/1276333/fe3e0de0-56c8-49a5-9643-9cc12d92de7a)

**Comment by bypassblitz** [comment] 2023-10-27 06:52
If I could also chime in I just got this today too, I deleted all of my modpacks and everything in multiMC off my laptop, and after a many hour long scan windows defender found this remaining forge file in my server folder, windows defender also obliterates the .jar file if I attempt to download it from https://files.minecraftforge.net/

In this case, defender flagged a file (not depicted in this screenshot) that has not been edited or used since Oct 9th, might be a false positive from a windows update or their virus definitions? I'm using windows 10.

![image](https://github.com/MinecraftForge/MinecraftForge/assets/129369435/4ec1d7af-c9a9-417d-b8de-bb2788b75671)

**Comment by Jonathing** [comment] 2023-10-27 09:53
Live laugh love Windows Defender.

**Comment by bypassblitz** [comment] 2023-10-27 15:14
Temporary solution: use forge 40.2.9 on clients

While it may be comical to savvy users that MS defender would decide to define the forge installer as ransomware it isn't a good look for people who you would have to explain this to. "just allow minecraft through your anti-virus" while makes sense, is gonna be redflags to sub-users.

MSdefender is not alone in specifying forge 40.2.10 as malicious, virus-totals web scanner also flags the installer .jar as malicious but not with the same report MS defender does.

**Comment by Jonathing** [comment] 2023-10-27 15:20
So when #9624 was merged in? How on God's green earth is some simple IPv4 and IPv6 logging triggering defender? If you're curious, you can see the code in the PR itself that was merged in.
@LexManos @PaintNinja thoughts?

**Comment by PaintNinja** [comment] 2023-10-27 15:31
This was already discussed on Discord. Someone confirmed that the sha1 didn't match the website but redownloading the same version and checking again made it match and was fine.

If you get a virus warning on a download, do not ignore it. Delete the file and try a fresh download.

**Comment by shkabo** [comment] 2023-10-27 15:55
@PaintNinja In my case, I already had jar locally that got flagged this morning when I started my SB3 instance as defender got updated.
I've ran virustotal with the url that I got for downloading the jar, but it's clean, you can see results [here](https://www.virustotal.com/gui/url/30fd4e1095db3c2c0487e625467deee53f9939086ecf6f2ddc7f3f8c9a80f272)
Downloading file from there still got flagged so yea. I wouldn't say it's due to sha1, and we'd need some more context to it for a resolution.

**Comment by PaintNinja** [comment] 2023-10-27 15:57
> Downloading file from there still got flagged so yea. I wouldn't say it's due to sha1, and we'd need some more context to it for a resolution.

Now redownload the same file again and check if it still gets flagged please.

**Comment by shkabo** [comment] 2023-10-27 16:12
It got flagged.
SHA256: [c5c3e038217cc6eb73f1ab315051faa71aaeeb880c6b186b4d0d35fa12e188b7](https://www.virustotal.com/gui/file/c5c3e038217cc6eb73f1ab315051faa71aaeeb880c6b186b4d0d35fa12e188b7)

**Comment by PaintNinja** [comment] 2023-10-27 16:16
Looking at the provided link, it no longer gets flagged by MS Defender and the sha1 matches the website. This confirms what I said earlier about deleting the file and redownloading.

Thanks for your help, we will investigate on our end. In the meantime our advice remains to trust Defender and delete the file then redownload. Do not run it if the sha1 doesn't match the site.

**Comment by shkabo** [comment] 2023-10-27 16:26
I have tried just now with latest update of defender (ss attached)
![defender status](https://github.com/MinecraftForge/MinecraftForge/assets/1276333/2ef00805-e14d-41e1-ac94-8112c3c16ee7)

and file still get's flagged as virus (ss attached) 
![forge virus detected](https://github.com/MinecraftForge/MinecraftForge/assets/1276333/34acd563-c75b-4a69-8a18-9964a725c797)
Direct download link (w/o ads) [here](https://maven.minecraftforge.net/net/minecraftforge/forge/1.18.2-40.2.10/forge-1.18.2-40.2.10-installer.jar)

(for previous test I disabled defender so that I could grab sha256 of that file)

Can you try to rebuild it and scan it with virustotal to see if it's still get's flagged (if you're not on windows) ?

**Comment by PaintNinja** [comment] 2023-10-27 16:32
Those screenshots are of separate antivirus software - Google Chrome's virus scanning is completely separate to Microsoft Defender. However, your earlier virustotal link showed that it passed Google's virus scanning.

Redownload the same file again a couple of times and see if it passes. My current working theory is that a middleman is inconsistently replacing the download to make it harder to track down. This is why I keep mentioning the sha1 checksum - if the downloaded file doesn't match what's listed on the website then it's not from us.

**Comment by shkabo** [comment] 2023-10-27 16:40
First [link ](https://www.virustotal.com/gui/url/30fd4e1095db3c2c0487e625467deee53f9939086ecf6f2ddc7f3f8c9a80f272) is a scan of download url (direct download, no ads) which is ok, but if you swap to 2nd tab (Details) and scroll down to the body SHA256 and click on it, you'll see result of a scan for a file that's being downloaded, which is flagged.

File is for sure corrupted and/or false flagged as a trojan. Re-downloading it doesn't do anything as I'm being served same file all over again. That's why I suggested you to re-build 1.18.2-40.2.10 forge installer and scan it manually with Virustotal by uploading that file.

I don't have local setup for java development or I'd do it myself.

**Comment by PaintNinja** [comment] 2023-10-27 16:50
We take this seriously, we are investigating on our end and our advice remains to trust your antivirus and don't run jars that don't match the associated SHA1 on the files site.

Please join our discord and share the file to me in a private message for me to analyse.

You previous messages confirm that this is happening inconsistently...

1:
> and file still get's flagged as virus (ss attached) ![forge virus detected](https://user-images.githubusercontent.com/1276333/278702418-34acd563-c75b-4a69-8a18-9964a725c797.jpg) Direct download link (w/o ads) [here](https://maven.minecraftforge.net/net/minecraftforge/forge/1.18.2-40.2.10/forge-1.18.2-40.2.10-installer.jar)

2:
> First [link ](https://www.virustotal.com/gui/url/30fd4e1095db3c2c0487e625467deee53f9939086ecf6f2ddc7f3f8c9a80f272) is a scan of download url (direct download, no ads) which is ok, but if you swap to 2nd tab (Details) and scroll down to the body SHA256 and click on it, you'll see result of a scan for a file that's being downloaded, which is flagged.

I did, it is not flagged by Google or Defender, which differs from what you showed in 1.
<img width="860" alt="image" src="https://github.com/MinecraftForge/MinecraftForge/assets/3158390/ea6fa108-7e72-4c2d-9112-31fbf389808a">

**Comment by JA876958** [comment] 2023-10-28 04:04
Im having this issue trying to install a modpack via prismlauncher.  This was the error I received from prism launcher. 

> java.io.FileNotFoundException: C:\Users\Jebbi\AppData\Roaming\PrismLauncher\libraries\net\minecraftforge\forge\1.18.2-40.2.10\forge-1.18.2-40.2.10-installer.jar (Operation did not complete successfully because the file contains a virus or potentially unwanted software)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:344)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:213)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1312)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getDataFromInstaller(IFileDetector.java:126)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getJvmArgs(IFileDetector.java:94)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:26)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
java.io.FileNotFoundException: C:\Users\Jebbi\AppData\Roaming\PrismLauncher\libraries\net\minecraftforge\forge\1.18.2-40.2.10\forge-1.18.2-40.2.10-installer.jar (Operation did not complete successfully because the file contains a virus or potentially unwanted software)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:344)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:213)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1312)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getDataFromInstaller(IFileDetector.java:126)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getInstallProfileExtraData(IFileDetector.java:119)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.checkExtraFiles(IFileDetector.java:152)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:30)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
java.io.FileNotFoundException: C:\Users\Jebbi\AppData\Roaming\PrismLauncher\libraries\net\minecraftforge\forge\1.18.2-40.2.10\forge-1.18.2-40.2.10-installer.jar (Operation did not complete successfully because the file contains a virus or potentially unwanted software)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:344)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:213)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1312)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getDataFromInstaller(IFileDetector.java:126)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getMainClass(IFileDetector.java:110)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Exception caught from launcher
java.lang.NullPointerException
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Exiting with ERROR
Process exited with code 2.

Here is the Microsoft defender output.


![image](https://github.com/MinecraftForge/MinecraftForge/assets/149220150/8f50e705-6f9d-41ac-a814-6f77463ba17b)


Here is the jar scanner provided on the curseforge website
![image](https://github.com/MinecraftForge/MinecraftForge/assets/149220150/6ac02af3-b14d-41d4-acc3-d530e2ff9681)


I hope this is just a false positive but I want to make sure.

**Comment by LexManos** [comment] 2023-10-28 04:10
Yes it's a false positive. I've submitted the files to microsoft for a manual review. itll take time. Nothing we can do about false positives besides hope they feel like not flagging it anymore.

**Comment by KaelaniRevyruun** [comment] 2023-10-28 04:37
Just to add onto this, I've gotta rebuild my technic pack cos I can't load it up despite the file being over a week old and working just 48h ago. Same issue as OP here, and to boot, my Opera GX simply refuses to actually finish downloading on 1.18.2 latest specifically. It still allowed me to get the recommended build however.

**Comment by JA876958** [comment] 2023-10-28 06:50
![image](https://github.com/MinecraftForge/MinecraftForge/assets/149220150/225a0696-e8e2-4a4f-a708-0d75c574a34e)
 

I ran the file from the forge website through virus total

**Comment by MaverickMartyn** [comment] 2023-10-28 14:00
Just chiming in to say that I got the same issue.
I've been building a 1.18.2 pack for the past week+, with no issues using 40.2.10.
Today I was moving on to testing the server side and needed the Forge installer, and this happened.
![image](https://github.com/MinecraftForge/MinecraftForge/assets/2946618/b852f411-0b21-4c49-b9cd-e78738177381)
@PaintNinja I'm not sure what you mean by "delete the file and re-download". It gets yeeted by ~~Defender~~ Chrome, so there's nothing to delete, and re-downloading gives the same result regardless of the number of attempts.
**EDIT:** Downloading through Firefox doesn't trigger Defender until I scan it manually or try to execute it, and doesn't delete the file.

**Comment by bypassblitz** [comment] 2023-10-28 16:23
@MaverickMartyn 

If you can, just switch forge to 40.2.9

.9 and .10 are compatable, so a client can have .9 and can still connect to a .10 server (with my 114 mods at least)

It has been said in discord, all that can be done is wait for the appeal to be reviewed by Microsoft or wherever the appeal process takes place.

**Comment by HackTime** [comment] 2023-10-30 22:48
![image](https://github.com/MinecraftForge/MinecraftForge/assets/61324721/21ad17e0-38e1-4d8d-bf84-11cec4e09724)

but in 40.2.09 its not happened

**Comment by LexManos** [comment] 2023-11-01 01:37
Ya, Microsoft is being shitty and not actually having a human review it. I've triggered a new build, so use .11 or .9. If MS doesnt get their crap together in a week or so I'll just nuke the .10 build.

**Comment by LexManos** [comment] 2023-11-02 06:17
So finally heard back from Microsoft, they have removed the false positive.
> At this time, the submitted files do not meet our criteria for malware or potentially unwanted applications. The detection has been removed. Please follow the steps below to clear cached detections and obtain the latest malware definitions.
>
> 1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
> 2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
> 3. Run "MpCmdRun.exe -SignatureUpdate"
> 
> Alternatively, the latest definition is available for download here: https://docs.microsoft.com/microsoft-365/security/defender-endpoint/manage-updates-baselines-microsoft-defender-antivirus
> 
> Thank you for contacting Microsoft.

**Closed as completed by LexManos** 2023-11-02 06:17 UTC
Labels: Not Us, 1.18
