### ISSUE TITLE
1.18.2-40.0.36 crashes

### ISSUE THREAD

**Issue by IchHabeHunger54** [MinecraftForge/MinecraftForge#8553] opened 2022-04-04 09:59 UTC
**Minecraft Version:** 1.18.2

**Forge Version:** 40.0.36

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}

https://gist.github.com/IchHabeHunger54/767ff022e338f325399a55ac7493ef19 (yes, this is the entire log)

**Steps to Reproduce:**
1. Install Forge 40.0.36.
2. Try running it.

**Description of issue:**

Crashes on startup. A cutoff debug.log as seen above, an even shorter latest.log (only 3 lines; all of them are in the debug.log as well), and no crash report. Downgrading to 40.0.35 resolves the issue.

**Comment by sciwhiz12** [comment] 2022-04-04 10:28
Closing as cannot reproduce on a clean installation of 1.18.2-40.0.36.

**Closed as completed by sciwhiz12** 2022-04-04 10:28 UTC
Labels: Bug, 1.18
