### ISSUE TITLE
ItemHandlerHelper.insertItemStacked is filling wrong slots

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#5644] opened 2019-03-24 22:27 UTC
related version : 1.13.2 (test on latest 25.0.92)
This is a small test to show the result with ItemHandlerHelper.insertItemStacked (the items are filled in the armor slots (the offhand is first filled before doing the test)
```java
@SubscribeEvent
    public void onBoneMeal(BonemealEvent event) {
        if (!event.getWorld().isRemote) {
            event.getEntityPlayer().getCapability(CapabilityItemHandler.ITEM_HANDLER_CAPABILITY, null).ifPresent(p -> {
                ItemHandlerHelper.insertItemStacked(p, new ItemStack(Items.STICK, 10), false);
            });
        }
    }
```
![forge_bug_give_item](https://user-images.githubusercontent.com/17954109/54886752-c3912200-4e8b-11e9-83df-ad919f8eda39.png)

**Comment by tterrag1098** [comment] 2019-03-25 00:13
This seems like an issue with the player inv wrapper rather than that method.

**Comment by tterrag1098** [comment] 2019-03-26 04:58
Duplicate of #5638

**Closed as completed by tterrag1098** 2019-03-26 04:58 UTC
Labels: Bug, 1.13
