### ISSUE TITLE
[1.17.1] Entity Join World Event not firing on all mobs

### ISSUE THREAD

**Issue by Xyndra** [MinecraftForge/MinecraftForge#8030] opened 2021-08-27 17:24 UTC
Some mobs don't seem to fire the entity join world event.
The mobs I noticed were: Sheep, Cow, Chicken, Pig, Horse, Villager, Iron Golem, End Crystal
However, if I spawn them via spawn egg, they trigger the event.

I would've sent the log file, but it is veerryy messy from my mod.

**Comment by ricksouth** [comment] 2021-08-28 15:18
Duplicate of https://github.com/MinecraftForge/MinecraftForge/issues/7962.

**Comment by gigaherz** [comment] 2021-08-28 15:20
Not 100% duplicate. The other issue mentions entities loaded from disk, but the event also fails to fire for entities added via worldgen.

**Comment by ricksouth** [comment] 2021-08-28 15:25
> Not 100% duplicate. The other issue mentions entities loaded from disk, but the event also fails to fire for entities added via worldgen.

Ah yes that's what I had mentioned in the comments on the other issue, though I did think it was caused by the same code.

**Comment by gigaherz** [comment] 2021-08-28 15:30
Yes the root cause is the same: in 1.17, entities have separate region files from block data, and a separate chunkloading process.
When generating new chunks, the info goes straight to this entity manager instead of going through Level, so the event didn't fire.
In #8033 I tried to fix both.

**Closed as completed** 2021-09-17 00:11 UTC
