### ISSUE TITLE
Strange implementation of ItemStackHandler.setStackInSlot

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#4912] opened 2018-05-06 05:02 UTC
For whatever reason, [this](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/items/ItemStackHandler.java#L59) cancels the set if the incoming stack and existing stack have equivalent value but differing identity. 

This is fine, if we lived in a world where stacks are fully immutable and thus the boundary between value and identity is nonexistent, but stacks *are* mutable and thus their identity does very much matter. I'm not sure why ISH is trying to be smart here, if I want a specific instance in the ISH, I want that instance in there, regardless of the value.

This has caused dupes and disappearances, see https://github.com/Vazkii/Botania/issues/2590, where because a `set` doesn't *actually* set anything thanks to this smart check the same stack instance ends up in the bauble inventory *and* the player hand, and subsequently a shrink affects them both.

Of course, a lazy workaround is to just `copy()` stacks everywhere all the time to establish a separate identity, but this adds onto the ever increasing pile of stack copy performance papercuts, especially if this is happening in a high-throughput environment (machines) instead of a player right clicking some baubles.

I think ISH should just stick to a simple implementation instead of trying to be "smart" with a check that isn't necessarily correct. Would forge be open to removing that early exit? I would preserve the semantics of onSlotChanged by still performing the check and not calling onSlotChanged unless the values are unequal.

**Comment by mezz** [comment] 2018-05-10 05:57
This change dates back to the original implementation. 
You could ask RWTema about it but it seems like you already have a complete idea of what's going on here.

I'm fine with removing the check. My only disagreement is that I think we probably don't want to preserve this check at all. Doesn't it make more sense that `onSlotChanged ` should be called any time `this.stacks.set` is called?

**Comment by raoulvdberge** [comment] 2018-05-10 05:59
This is a duplicate of #3465

**Comment by mezz** [comment] 2018-05-10 06:24
I think that makes an even stronger case for removing the check entirely.
I'll leave this open for a few days for discussion. If everyone agrees and nobody bothers with a PR, I can submit a fix.

**Comment by mezz** [comment] 2018-05-13 04:08
Fixed in https://github.com/MinecraftForge/MinecraftForge/commit/dae7bcee4b4397cb6cd9ee1524d58510219bce34

**Closed as completed by mezz** 2018-05-13 04:08 UTC
