### ISSUE TITLE
[1.10.2] ConcurrentModificationException on server - no other mods installed

### ISSUE THREAD

**Issue by Kuboczoch** [MinecraftForge/MinecraftForge#3299] opened 2016-10-08 19:39 UTC
This is my crash report: http://hastebin.com/ozonibinak.pl
This can be easily triggered by issuing save-off, save-all via rcon

**Comment by marcin212** [comment] 2016-10-08 20:19
Same problem without rcon
http://hastebin.com/ezalopoyeq.scala

**Comment by Aaron1011** [comment] 2016-10-08 20:44
@Kuboczoch: This is a fundamental issue with RCon, not a Forge bug - it executes all of commands on another thread. A better solution is to simply avoid using RCon - it's completely unencrypted, so the password it uses is visible to anyone watching the network.

@marcin212: That appears to be a completely different issue, as you're using 71 mods.

**Comment by Kuboczoch** [comment] 2016-10-08 21:24
I use RCon on localhost... @Aaron1011

**Comment by magik6k** [comment] 2016-10-10 16:01
I fixed it with simple transformer, https://git.starchasers.ovh/magik6k/CMEFix/src/master/src/main/java/pl/starchasers/cmefix/Transformer.java, running fine since 2 days, with hourly rcon connection to prepare server for backup(save-off/all/on)

**Comment by Pokechu22** [comment] 2016-11-16 00:10
It's a vanilla issue, see [MC-72390](https://bugs.mojang.com/browse/MC-72390).  Forge isn't really in the position to fix it (it could, but really it should be fixed on mojang's end).

**Comment by Heufneutje** [comment] 2016-11-16 07:41
Forge fixes a few vanilla bugs. Usually they are submitted with the Mojang bug tracker number in a comment in the patch so it can easily be removed once Mojang fixes it.

**Comment by JustGregory-zz** [comment] 2016-11-17 06:19
That really begs the question, does Mojang care what Forge "fixes" or not? If so, why wouldn't they adopt Forge's fixes even more quickly?

**Comment by Pokechu22** [comment] 2016-11-17 15:21
Mojang does apply fixes from the community if they're on their bug tracker (at least, occasionally; for bigger fixes or "hacky" fixes they tend to use it as advice rather than a direct patch).  I've contributed several bug fixes that way.

There is one other thing to consider (and I'm not completely in the know about it): [Forge is LGPL](https://github.com/MinecraftForge/MinecraftForge/blob/1.10.x/LICENSE-new.txt), which makes it legally complicated for Mojang to use Forge patches.  Just something to consider...

**Comment by Pokechu22** [comment] 2017-12-24 18:19
The issue is still present and the MC ticket has been updated.

**Comment by mezz** [comment] 2017-12-24 19:37
I'm not sure if it is useful to keep Forge issues open for vanilla bugs unless there is active discussion.
I think it is probably good to keep discussion centralized on the Mojang tracker unless a PR is open for Forge. What do you think?

**Comment by Pokechu22** [comment] 2017-12-24 19:42
Yeah, it'd be fine to close this and just keep the discussion on the tracker, just wanted to make it clear that the issue is still present.

**Comment by mezz** [comment] 2017-12-24 19:45
Thanks! I will close this now. 
For anyone reading, you should still feel free to open PRs to fix vanilla bugs if the fix is not too large.

**Closed as completed by mezz** 2017-12-24 19:45 UTC
Labels: Vanilla Bug
