### ISSUE TITLE
Server with Forge 10.13.3.1358 crashing after update

### ISSUE THREAD

**Issue by crescentrose** [MinecraftForge/MinecraftForge#1782] opened 2015-04-09 14:54 UTC
After updating to Forge 10.13.3.1358, my Minecraft server keeps crashing in region -2,1. I first believed the issue was in [Thermal Dynamics](https://github.com/CoFH/Feedback/issues/404), however once I completely deleted that region, I got the following crash:

http://pastebin.com/P5xMCExX

Any details on what's happening?

Thanks for looking into this.

edit: changed title for clarity

**Comment by LexManos** [comment] 2015-04-09 19:19
Post the actual FML log not the crash report.

**Comment by KingLemming** [comment] 2015-04-09 21:35
Ignore the reference above. I was reading this issue and derped on the commit number when pushing to my own repo. I fixed 1773.

**Comment by cpw** [comment] 2015-04-19 16:08
Closing, either fixed or a dupe of #1797

**Closed by cpw** 2015-04-19 16:08 UTC
