### ISSUE TITLE
[1.17.1] Forge does not detect IModLanguageProvider and crashes outside of dev

### ISSUE THREAD

**Issue by thedarkcolour** [MinecraftForge/MinecraftForge#8090] opened 2021-09-18 21:36 UTC
**Minecraft Version:** 1.17.1

**Forge Version:** 37.0.67

**Logs:**
The logs don't have the errors/warnings for some reason, so I'll add images of the errors.
In dev workspace, game launch:
Log: https://gist.github.com/thedarkcolour/3b73ef0d311e5de9ba530170fe9a1d99
![image](https://user-images.githubusercontent.com/30441001/133908388-2e95d0c1-da07-4fe9-8e52-06fdef649768.png)
In GDLauncher with kotlinforforge-2.0.0-obf.jar in the mods folder:
Log: https://gist.github.com/thedarkcolour/bcc2333aa5f7ac8b255bcc85747db41d
![image](https://user-images.githubusercontent.com/30441001/133908522-ce77802e-3bd2-47bb-9a41-c74605e4fe7e.png)

**Steps to Reproduce:**
 1. In a git bash or cmd prompt, run `git clone --branch 2.x https://github.com/thedarkcolour/KotlinForForge` to get KFF for 1.17 (as a test language provider)
 2. Run `gradlew --refresh-dependencies` to import Gradle and Forge
 3. Run `gradlew genIntellijRuns` or the equivalent for your IDE to get the run configurations
 4. Use `runClient` to get the first image/log
 5. Run `gradlew build` to get compiled mod jar `kotlinforforge-2.0.0-obf.jar` and run in a game launcher to get second image/log

**Description of issue:**
In dev workspace, KotlinForForge has its META-INF declared in the build.gradle with `FMLModType: LANGPROVIDER` and a `IModLanguageProvider` service in the src/main/resources/META-INF folder. I expect the game to run and find 3 language providers in the debug.log, but I only see the two provided by forge and a warning saying that KotlinForForge is ignored because it has no mods.toml file. When the game finishes loading, you get the first image. During 1.14-1.16, I had a mods.toml file and a test mod which worked fine in dev. I removed it in 1.17 because I heard that is not the intended behavior, and I haven't gotten Forge to recognize the IModLanguageProvider service in the mod jar either way.

Let me know if there's any other information you need.

**Comment by SizableShrimp** [comment] 2021-09-18 21:38
This is a duplicate of #7957, you should add this info there.

**Comment by AterAnimAvis** [comment] 2021-09-22 17:07
Closing as duplicate of #7957

**Closed as completed by AterAnimAvis** 2021-09-22 17:07 UTC
Labels: Bug, 1.17
