### ISSUE TITLE
- in jar name crashes on startup

### ISSUE THREAD

**Issue by Raycoms** [MinecraftForge/MinecraftForge#9172] opened 2022-12-03 09:42 UTC
**Minecraft Version:** {Minecraft version}
1.19.2

**Forge Version:** {Forge version. *Version number, not latest/rb*}
After: https://github.com/MinecraftForge/MinecraftForge/pull/9143

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}
Exception in thread "main" java.lang.IllegalArgumentException: multi-piston: Invalid module name: 'multi-piston' is not a Java identifier

(Doesnt produce a log, just this in the console)

**Steps to Reproduce:**
 1. Startup this mod: https://www.curseforge.com/minecraft/mc-mods/multi-piston/files/4029456
 2. Then crash on startup
 3. ...

**Description of issue:**
This seems to be related to having a - in a modjar name

Related issue:
https://github.com/ldtteam/Piston-Unlimited/issues/25

**Comment by sciwhiz12** [comment] 2022-12-03 09:49
This is a regression in 43.1.65, from #9143. `SecureJar.from` is called with a path whose filename may contain characters that are illegal Java identifiers, which causes a crash when an automatic module is created with a name based on that filename.

**Comment by sciwhiz12** [comment] 2022-12-03 10:09
<sup>I am a blind man.</sup> Looking into the code responsible for the creation of the module name [in securejarhandler's `JarMetadata`](https://github.com/McModLauncher/securejarhandler/blob/ee35db45b3da48a7ff1b844313167d0a8e5019b0/src/main/java/cpw/mods/jarhandling/JarMetadata.java), it seems that there is only one case in those factory names which the module name does not pass `cleanModuleName`: when the jar manifest [defines `Automatic-Module-Name`](https://github.com/McModLauncher/securejarhandler/blob/ee35db45b3da48a7ff1b844313167d0a8e5019b0/src/main/java/cpw/mods/jarhandling/JarMetadata.java#L45-L47). When the factory method determines the module name based on the filename, it passes the name through `cleanModuleName`.

Indeed, the jar given to me by the reporter defines `Automatic-Module-Name` in its manifest, with a value of `multi-piston`, which is an invalid module name due to the hyphen (as module names must be valid Java identifiers, i.e. "can this be used as a class/variable name?"). Modifying the value to remove the hyphen -- `multipiston` -- resolves the issue and the game loads normally.

Closing this issue as user error (and a wrong assumption on my part) -- when a user defines the `Automatic-Module-Name`, it is on the user to ensure that the provided module name is indeed valid.

**Closed as not planned by sciwhiz12** 2022-12-03 10:09 UTC
Labels: Regression, Confirmed, 1.19
