### ISSUE TITLE
[1.9] Threaded skin downloading for skulls broken with Forge

### ISSUE THREAD

**Issue by ganymedes01** [MinecraftForge/MinecraftForge#2835] opened 2016-05-07 22:47 UTC
When Forge is installed, if the game tries to download several skins at once the game hangs until the downloads are done.

To help people reproduce this bug I created a test world with a chest filled with skulls. When opening the chest with Forge installed the server freezes, when opening it in vanilla everything runs smoothly: https://www.dropbox.com/s/ydp767fw9o7pb7d/New%20World.zip?dl=0

**Comment by asiekierka** [comment] 2016-05-27 05:43
Can confirm that this is a problem.

**Comment by Actuarius** [comment] 2016-05-27 05:48
@tterrag1098 added labels [Regression]

**Comment by darkhax** [comment] 2016-05-27 05:59
I can also confirm this issue. In my mod Bookshelf I add a new creative tab that is populated with the heads from [Marc's Head Format](http://minecraft.gamepedia.com/Mob_head#Mojang_skins). When opening the creative tab the client will freeze for a minute or so.

**Comment by LexManos** [comment] 2016-05-28 00:17
Just tested on latest 1.9 and 1.9.4 can not reproduce. Chest opens, and I can see that split second of it downloading the skins. No lag, no freezing...

**Comment by williewillus** [comment] 2016-05-28 00:22
cannot reproduce, but that was in my not-logged-in dev environment. trying in an actual runtime rn...

**Comment by williewillus** [comment] 2016-05-28 00:25
cannot reproduce in obf environment either :P

**Comment by asiekierka** [comment] 2016-05-28 05:44
Could someone try SMP with just Forge? Maybe the issue is there...

**Comment by darkhax** [comment] 2016-05-28 06:15
If this issue is the same one as the creative tab issue, it should effect SSP and SMP equally. Perhaps the world file @ganymedes01 uploaded has some sort of cache?

**Comment by LexManos** [comment] 2016-05-28 21:00
The actual downloading of the skins/profiles is done in AuthLib. All caching is done that side. Looking at the code for that there isn't any on-disc caching being done.
Digging around i've tracked down the thread where the downloading is done. There are actually two things that are downloaded one threaded one not.
The first: The User profile for the skull owner, This is NOT threaded. So this may be where you're getting your issues
The second: The actual skin, this IS threaded in net.minecraft.client.renderer.ThreadDownloadImageData.loadTextureFromServer() and it works wonderfully in forge:


```

[13:56:21] [Texture Downloader #1/INFO] [STDOUT]: Downloader #1 126
[13:56:21] [Texture Downloader #2/INFO] [STDOUT]: Downloader #2 127
[13:56:22] [Texture Downloader #3/INFO] [STDOUT]: Downloader #3 128
[13:56:22] [Texture Downloader #4/INFO] [STDOUT]: Downloader #4 129
[13:56:22] [Texture Downloader #5/INFO] [STDOUT]: Downloader #5 130
[13:56:22] [Texture Downloader #6/INFO] [STDOUT]: Downloader #6 131
[13:56:22] [Texture Downloader #7/INFO] [STDOUT]: Downloader #7 132
[13:56:22] [Texture Downloader #8/INFO] [STDOUT]: Downloader #8 133
[13:56:22] [Texture Downloader #9/INFO] [STDOUT]: Downloader #9 134
[13:56:22] [Texture Downloader #10/INFO] [STDOUT]: Downloader #10 135
[13:56:22] [Texture Downloader #11/INFO] [STDOUT]: Downloader #11 136
[13:56:22] [Texture Downloader #12/INFO] [STDOUT]: Downloader #12 137
[13:56:22] [Texture Downloader #13/INFO] [STDOUT]: Downloader #13 138
[13:56:22] [Texture Downloader #14/INFO] [STDOUT]: Downloader #14 139
[13:56:22] [Texture Downloader #15/INFO] [STDOUT]: Downloader #15 140
[13:56:22] [Texture Downloader #16/INFO] [STDOUT]: Downloader #16 141
[13:56:22] [Texture Downloader #17/INFO] [STDOUT]: Downloader #17 142
[13:56:22] [Texture Downloader #18/INFO] [STDOUT]: Downloader #18 143
[13:56:22] [Texture Downloader #19/INFO] [STDOUT]: Downloader #19 144
[13:56:22] [Texture Downloader #20/INFO] [STDOUT]: Downloader #20 145
[13:56:22] [Texture Downloader #21/INFO] [STDOUT]: Downloader #21 146
[13:56:22] [Texture Downloader #22/INFO] [STDOUT]: Downloader #22 147
[13:56:22] [Texture Downloader #23/INFO] [STDOUT]: Downloader #23 148
[13:56:22] [Texture Downloader #24/INFO] [STDOUT]: Downloader #24 149
[13:56:22] [Texture Downloader #25/INFO] [STDOUT]: Downloader #25 150
[13:56:22] [Texture Downloader #26/INFO] [STDOUT]: Downloader #26 151
[13:56:22] [Texture Downloader #27/INFO] [STDOUT]: Downloader #27 152
[13:56:22] [Texture Downloader #28/INFO] [STDOUT]: Downloader #28 153
```

Closing this as unreproduceable

**Closed by LexManos** 2016-05-28 21:00 UTC
Labels: Regression

**Comment by asiekierka** [comment] 2016-05-28 21:01
User profiles would explain it. Thanks!

**Comment by mezz** [comment] 2016-07-05 23:41
I believe this is the relevant Mojang issue: https://bugs.mojang.com/browse/MC-65587
