### ISSUE TITLE
[1.12] error during loading of player inventory!!

### ISSUE THREAD

**Issue by NarigudoBR** [MinecraftForge/MinecraftForge#4111] opened 2017-07-01 03:24 UTC
https://pastebin.com/FP5Asnxh
when i kill minecraft and load the world again, the items are gone!
was happening in forge 2340 and happend at forge 2387!
the full log: https://pastebin.com/UgTxUVNn

**Comment by 0f-0b** [comment] 2017-07-01 06:27
Edit: Did you remove all the mods and try again **in a new world**?

**Comment by NarigudoBR** [comment] 2017-07-02 02:18
It happended again, and I lost my items and xp again!(on spawn point, like a new save). how would Quark corrupt my savefile?(quark is the only big mod in the list)

**Comment by NarigudoBR** [comment] 2017-07-02 02:19
My player file/data just reseted

**Comment by NarigudoBR** [comment] 2017-07-02 02:22
It's like.. the save feature brakes sometimes

**Comment by LexManos** [comment] 2017-07-02 04:33
It passes all of the tests we have. Are you able to reproduce reliably? If so what processes are you doing?
Please provide both the server and client log files. The reason we do not like the logs you've provided is that it is fileld with errors from other mods. Unrelated to Forge.
So if you can reproduce it without other mods we can take a look. Until then I am unable to reproduce in any way and i've tired many different combinations.

**Comment by NarigudoBR** [comment] 2017-07-05 00:38
what does it mean "Cannot cast net.minecraft.client.network.NetHandlerLoginClient to net.minecraft.client.network.NetHandlerPlayClient
	at java.lang.Class.cast(Unknown Source) ~[?:1.8.0_131]"

**Comment by williewillus** [comment] 2017-07-05 00:54
That error is a dupe of #3974

**Comment by NarigudoBR** [comment] 2017-07-05 01:42
but if this error was fixed, why is it happening with the latest forge?

**Comment by NarigudoBR** [comment] 2017-07-05 01:44
the weird thing is that if I create another world,close it, and reload, it will give the same error!

**Comment by mezz** [comment] 2017-07-05 05:47
For troubleshooting, please post in the Forge forum.

**Closed as completed** 2017-07-05 13:51 UTC
