### ISSUE TITLE
Splash Screen elements getting weird discoloration.

### ISSUE THREAD

**Issue by Drullkus** [MinecraftForge/MinecraftForge#1987] opened 2015-07-02 10:24 UTC
Game Version: 1.7.10
Version: 10.13.3.1403 and 0.13.4.1481

Using custom colors in on the splash screen causes weird discoloration. You're seeing color 0x666666 superimposed on all other colors.

![screen shot 2015-07-02 at 3 16 42 am](https://cloud.githubusercontent.com/assets/5010174/8475054/bf91d7ca-2069-11e5-907f-7c4446f7a2e4.png)

**Comment by bs2609** [comment] 2017-05-04 01:57
Has this been resolved by #3859?

**Comment by mezz** [comment] 2017-05-04 03:02
Yes, sort of, I'll explain. 
The Mojang logo can no longer be changed using the Forge config, removing their logo is kind of a lame  thing to do (eula-breaking? who knows).
I'm sure mods can find a way to add the pack logo in addition to the Mojang one, but then any coloration issues are their responsibility and not really caused by Forge.

The weird coloration of anything else besides the Mojang logo has been resolved.

**Closed by mezz** 2017-05-04 03:02 UTC
Labels: Bug, Superseded
