### ISSUE TITLE
[1.10] Unwanted deobfuscation of member fields in derived classes

### ISSUE THREAD

**Issue by Mumfrey** [MinecraftForge/MinecraftForge#3043] opened 2016-06-26 20:10 UTC
I am experiencing a problem with the FML deobfuscating remapper in 1.10 whereby fields in classes which extend from MC base classes are being remapped (effectively, deobfuscated) when they shouldn't be. This only applies to code which is obfuscated to "notch names", which all liteloader mods are since I don't have permission to redistribute MCP mappings.

The problem is easy to reproduce:

```java
public class SomeCustomScreen extends GuiScreen {

    // Member field with a name matching an obfuscated field in the parent
    protected float a;

}
```

When the class is loaded, the field `a` will be remapped to `field_175287_a` because a field `a` exists in `GuiScreen`. The type of field is not taken into account, the field can be of any type. I have confirmed that this only happens in 1.10, the latest 1.9.4 build (at time of posting, 1987) does not exhibit this behaviour.

I'm going to duck under a table before the next part: The practical upshot of this problem is that "shadow" fields in notch-obfuscated mixins are getting incorrectly remapped if a field with the same name exists in the superclass. This basically means that if forge is installed the mixin cannot be applied.

The reason this is happening is that mixins are run through the transformer chain just like regular classes, this is necessary in particular so that the deobf transformer can remap class and method names inside them. In general, a mixin class will always extend the same superclass as its target, and this means that the deobf remapper is finding the field mappings in the superclass and incorrectly applying the remap to the member field.

I believe the root cause of this might be [this change](https://github.com/MinecraftForge/MinecraftForge/commit/260be687239b7ba04d6be2f5b9a0ce432f923cf6#diff-9ded99c2c42f0ce086319530fc38780aR270) made in 1.10, which would seem to make the field map check permissive enough to match superclass fields even when the field type is different, though I'm by no means an expert on the FML codebase and it might be a red herring.

For the time being I can fix this for the current situation by breaking the superclass relationship with the mixin in question. However it would be great if you're able to address this, since it's possible that it will affect others who have similar mixin code.

If you need any further details I'd be happy to provide them, or if you'd prefer that I just PR a fix so that you don't have to waste your time with it then I'm quite happy to do that too.

**Comment by cpw** [comment] 2016-06-26 21:38
Without the highlighted fix, almost no mods would actually load from 1.9.4 into 1.10, since there are a few fields which have had their type changed. I feel that establishing compatibility for forge mods from 1.9.4 matters, so I'm not sure how I can make both camps happy.

**Comment by Mumfrey** [comment] 2016-06-26 22:49
Ah I see now why you made that change then, it makes sense.

If I could make some assumptions then about how this works (I've only taken a fairly limited look at the logic but since it's hooking into ASM's remapper I think I can make some educated guesses)?

Would it not be possible to address this by simply handling the particular scenario which is triggering this behaviour. Namely, that a field exists in a subclass which does **not** appear in the class's obf mapping table. This is what is causing the logic to "fail over" to looking up the field in the superclass table when it shouldn't.

My assumptions would guide me thus:

* The code in question, `mapField`, gets called in two situations: firstly to remap a field (`FieldNode`) itself, eg. in `GuiScreen` or whatever, and secondly to remap *references* to that field (`FieldInsnNode` etc.)
* In the first scenario, the remap operation *can safely fail*, since the only time it should succeed is when there is a mapping **for this class**
* In the second scenario, superclasses need to be considered, and we can't detect the failure state because the search needs to be promiscuous (ignore type) in order to satisfy searching for fields which have changed type

If these assumptions are correct, would it also be fair to assume that if the two scenarios were handled differently, then in the case that the first lookup fails, a 1:1 entry can be created in **this** class's lookup table which would inhibit the superclass search from that point forward?

Now I realise that if this is using ASM's remapper, then `mapField` is just called directly per the contract of `Remapper`, but I would assume it wouldn't be too tricky to do a "first pass" over the class fields before the remapper kicks off its stuff in order to perform the special handling for the extant fields.

Is that utterly implausible or does it make a crazy kind of sense?

**Comment by Mumfrey** [comment] 2016-06-29 12:02
Okay I realise the above might be a bit waffle-y so summarised version:

* I assume the superclass lookup for the field can be avoided if a mapping for the field exists for **this class** (the one being transformed)

* It's easy to determine whether a field exists in a class, and if no mapping exists for it (at all) then it doesn't make sense to resolve a mapping for the field *declaration* in the superclass.

* **Adding** a mapping for the field at that point should then prevent superclass resolution for the field where the field is *referenced*.

* This could be achieved relatively simply by making a first pass over the class fields before remapping begins, resolving mappings and adding entries wherever no mapping exists

Hope that is a better explanation.

**Comment by Mumfrey** [comment] 2016-06-29 14:38
See the above commit. This would basically change the remapping adapter to call `mapMemberFieldName` instead of calling `mapFieldName` directly. In the deobf remapper the field is then *only* resolved in the raw field map and isn't resolved in any superclass maps. The returned value is then placed into the raw field map (meaning an entry for non-remapped fields will essentially be created).

**Comment by cpw** [comment] 2016-06-29 23:37
OK. I'm not sure what you're trying to accomplish with all that new  code, but you seem to have missed what I was trying to fix with this change completely. Here's the problem:

In 1.9.4, the door fields in init.Blocks were all of declared type Block. In 1.10, they're of declared type BlockDoor. The actual instances are BlockDoor in both cases. This breaks compatibility, in my opinion, in an unecessary way - the actual functional logic is the same, just the field declaration has changed. The fix, fixed this. That's what it was designed to do. (I had this intention a long time ago, but it hasn't been a problem for many minecraft versions, and I didn't realize it didn't work properly until 1.10).

For field inheritance in general, it's always inherited the fields from parents, *and* considered their actual runtime declared type - there was a bug many years ago about the fact that DedicatedServer had an obf field (i or something) that was being incorrectly masked by an identically named field in MinecraftServer. Here's the PR: https://github.com/MinecraftForge/FML/pull/217 and here's the issue: https://github.com/MinecraftForge/FML/issues/210

**Comment by Mumfrey** [comment] 2016-06-30 01:52
No honestly I completely understand what you're going for. The point is really the remapping of field declarations vs. references in the code to those fields. From how I understand the code, the field references are always either going to be in the table or not present (implying the field can't be renamed) and this part is where there is an opportunity to avoid searching for the field in the supertypes.

However field references (in the code, eg. method bodies) need to use the merged super map because they might be referencing one field in a class which is actually "owned" by the superclass, or might be referencing a field which has changed type.

The commit above doesn't change the latter behaviour, it still functions exactly the same. What it does is for the first scenario (field declarations) it only uses the raw field map **and** once a field is resolved, stores the resolved value (whether it's remapped or not) in the class's field map so that *references* then don't fall foul of the resolve-different-field-in-superclass thing.

Essentially, it should leave your desired behaviour in place, but handle the situation that a **non**-remapped field (eg. an orphan field which *should not get remapped*, like the ones in the mixins) effectively gets a mapping *to itself* generated at runtime, thus inhibiting the undesired behaviour described in the issue post.

Maybe I've missed something, but there's no case where a field *declaration*'s mapping should be resolved in a superclass's mapping table? Is that correct? if so, the above code should address the issue. In my tests, it fixes the problem and all of the mc classes (and references to their respective fields in other classes) get remapped.

**Comment by cpw** [comment] 2016-07-01 13:05
OK Mumfrey, I think I get what you're saying. Currently, FML doesn't distinguish between field reference sites and field declaration sites when it comes to remapping the field, and as a result, it sometimes remaps a field declaration site unecessarily?

If you can PR something, I'll take a proper look.

**Comment by Mumfrey** [comment] 2016-07-01 19:53
I have made the PR as requested. I have also prepared a lengthy but I hope quite clear explanation of the problem and the proposed changes to fix it. I'll be on IRC a bit later if you want to yell at me about it :smile:

**Comment by cpw** [comment] 2016-07-01 21:58
It's Canada day, we'll talk tomorrow hopefully. Thanks!

**Comment by Mumfrey** [comment] 2016-07-01 22:37
No worries dude have a good day, this can wait :smile:

**Comment by Actuarius** [comment] 2016-07-23 14:09
@williewillus added labels [Bug]

**Comment by cpw** [comment] 2016-07-23 16:19
Did I not accept the PR?

**Comment by williewillus** [comment] 2016-07-23 16:19
#3055 still open

**Comment by LexManos** [comment] 2016-09-12 21:53
Closing as this was fixed github just didnt understand cpw's commit message.

**Closed by LexManos** 2016-09-12 21:53 UTC
Labels: Bug
