### ISSUE TITLE
Goat horn Bug crash on multiplayer

### ISSUE THREAD

**Issue by Yrriel** [MinecraftForge/MinecraftForge#9110] opened 2022-10-23 03:19 UTC
**Minecraft Version:** 1.19.2

**Forge Version:** 43.1.1

**Logs:** The game crashed whilst rendering entity in world
Error: java.lang.NullPointerException: applyTransform() must not be called on a vanilla ArmPose!

**Steps to Reproduce:**
 1. (on multiplayer) Play with a friend 
 2. give him a horn
 3. let your friend use the horn
 4. **crashed on your client**

**Description of issue:**
I tried to horn, it works. but when my friend used it, the minecraft crashed.

**Comment by sciwhiz12** [comment] 2022-10-23 07:28
Duplicate of #8985

**Closed as not planned by sciwhiz12** 2022-10-23 07:28 UTC
Labels: Bug, 1.19

**Comment by tmvkrpxl0** [comment] 2022-10-23 23:12
This was my mistake, updating to 43.1.2 or higher would fix it
