### ISSUE TITLE
Minecarts seem to accelerate until they derail.

### ISSUE THREAD

**Issue by cprevoe** [MinecraftForge/MinecraftForge#2601] opened 2016-03-20 20:51 UTC
Note: This is most noticeable with hopper carts, and chest carts. 

How to reproduce: 
Create a rail loop in a 9x9 square with all the straight pieces being powered rail and corners being normal rail.

Behavior in vanilla 1.9: hopper carts and chest carts stay on the rail (though there is sometimes visual funkiness).
Behavior in forge: They speed up until they fly off their track.

Test conditions: Forge 12.16.0.1776. Removed all mods from the mods folder and used a Superflat Creative world created in vanilla fresh for this test.

**Comment by CovertJaguar** [comment] 2016-03-20 22:19
Confirmed. Investigating.

**Comment by CovertJaguar** [comment] 2016-03-20 23:14
Problem location. Fix on the way.

**Comment by gigaherz** [comment] 2016-03-21 14:45
@cprevoe: You may want to verify that this got fixed, and if so, close the issue? The "Fix #n" tag on the commit didn't get applied.

**Comment by AEnterprise** [comment] 2016-03-21 16:46
@gigaherz the fix tag did get applied, notice the small "i" icon next to it, the issue is still open cause the fix isn't on the main branch (yet)

**Comment by gigaherz** [comment] 2016-03-21 16:52
Oh I see.

**Closed** 2016-03-21 21:26 UTC
