### ISSUE TITLE
[1.10.2] Oak Tree dont call generateTree

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/MinecraftForge#3650] opened 2017-01-21 20:51 UTC
If you make a custom block were Oak Sapling can stand on, the block will replaced by dirt if the tree grows. 
This does not happen with spruce, birch, acacia, dark oak, giant spruce, giant jungle.
This does happen with oak, jungle.

I think this is because `Block.onPlantGrow(IBlockState state, World world, BlockPos pos, BlockPos source)` getts not called.

**Comment by SquidDev** [comment] 2017-01-21 21:51
Is this related to #2866?

**Comment by williewillus** [comment] 2017-01-21 22:16
Duplicate of 2866

**Comment by mcenderdragon** [comment] 2017-01-21 22:34
But it is still a thing and still annoing.

**Comment by mcenderdragon** [comment] 2017-01-21 22:39
On line 86 in `WorldGenBirchTree`  ` state.getBlock().onPlantGrow(state, worldIn, down, position);` is called to notify the block beneath to change to dirt if grass or farmland. 
In `WorldGenTree` (used to generate small oaks and jungle trees) on line 98 ` this.setDirtAt(worldIn, position.down());` is used. I suggest we change that to the onPlantGrow, like any other tree gen does.

**Closed as completed** 2017-01-22 03:39 UTC
