### ISSUE TITLE
ConcurrentModificationException upon player disconnect, deletes chunk

### ISSUE THREAD

**Issue by grothedev** [MinecraftForge/MinecraftForge#8581] opened 2022-04-23 05:22 UTC
**Minecraft Version:** 1.18.1

**Forge Version:** 39.0.88

**Logs:** ![image](https://user-images.githubusercontent.com/5280051/164878947-0c0acc83-1cc0-446a-9f50-bec9fa61160d.png)

**Steps to Reproduce:**
 1. log on, play the game, if there is something that trigger this it is currently unknown
 2. log off
 3. see the error happen in the log
 4. log on to see that a nearby chunk has been reverted back to seed state

**Description of issue:**
on rare occasions, a chunk that a player has loaded will get deleted when they log off. in both observed cases, this has been in a chunk with blocks from a handful of different mods. 

here is our modlist: 
- appleskin-forge-mc1.18-2.4.0.jar
- artifacts-1.18.1-4.0.3.jar
- BiomesOPlenty-1.18.1-15.0.0.104-universal.jar
- blockui-1.18.1-0.0.43-ALPHA.jar
- cc-tweaked-1.18.1-1.100.2.jar
- Clumps-forge-1.18.1-8.0.0+5.jar
- Colony4ComputerCraft-1.18.1-2.1.0.jar
- Controlling-forge-1.18.1-9.0+15.jar
- create-mc1.18.1_v0.4e.jar
- Cucumber-1.18.1-5.0.3.jar
- curios-forge-1.18.1-5.0.6.2.jar
- domum_ornamentum-1.18.1-1.0.39-ALPHA-universal.jar
- expandability-5.0.0-forge.jar
- flywheel-forge-1.18-0.6.1.jar
- hexcasting-0.5.0.jar
- ironchest-1.18-13.0.7.jar
- jei-1.18.1-9.2.1.69.jar
- kotlinforforge-3.1.0-obf.jar
- Mantle-1.18.1-1.8.31.jar
- minecolonies-1.18.1-1.0.428-RELEASE.jar
- MouseTweaks-forge-mc1.18-2.21.jar
- multi-piston-1.18-1.2.2-ALPHA.jar
- MysticalAgriculture-1.18.1-5.0.3.jar
- NaturesCompass-1.18.1-1.9.5-forge.jar
- Patchouli-1.18.1-65.jar
- productivebees-1.18.1-0.8.0.8.jar
- reap-1.18.1-1.0.0.jar
- structurize-1.18.1-1.0.342-RELEASE.jar
- TConstruct-1.18.1-3.4.1.46.jar
- TerraBlender-forge-1.18.1-1.1.0.77.jar
- torchmaster-18.0.3-beta.jar
- Xaeros_Minimap_22.3.0_Forge_1.18.jar
- XaerosWorldMap_1.20.3.1_Forge_1.18.jar

**Comment by sciwhiz12** [comment] 2022-05-08 03:30
Due to the nature of this exception and stacktrace and the steps provided, we cannot reproduce the issue to verify if it exists on a clean Forge server with no additional mods. Without confirmation that this exists on a clean Forge server (or even on a vanilla server), we cannot rule out the possibility that one of the mods present on your server is causing the error.

Because of this, I'll be closing this issue until confirmation can be provided that this issue exists on a clean Forge server (without any mods). If you or anyone else does find such confirmation, please open a new topic on the [Forge Support Forums](https://forums.minecraftforge.net/) first, as this issue tracker is intended for final bug reports and feature requests.

**Closed as completed by sciwhiz12** 2022-05-08 03:30 UTC
Labels: Bug, 1.18
