### ISSUE TITLE
Allow read timeout to be configurable again

### ISSUE THREAD

**Issue by TheAwesomeGem** [MinecraftForge/MinecraftForge#4671] opened 2018-01-09 20:49 UTC
Recently, the arg "-Dfml.readTimeout" was removed which allowed the timeout to be configurable. Now it's impossible to join servers that have over 240+ mods. I own 2 servers with Modern Skyblock modpack and a custom modpack, both having atleast 230+ mods and 90% of my players timeout when joining or switching to another dimension or even loading chunks. The only way to change the timeout is to edit NetHandlerPlayServer or FMLNetworkHandler as they are hardcoded values. On my server, atleast 40 players had this issue of timing out mostly whenever they are trying to join a world. It's not just my servers but other servers as well.

More Info: https://www.reddit.com/r/feedthebeast/comments/7ozc5n/time_out_problems_connecting_to_servers_with_112x/

https://www.reddit.com/r/feedthebeast/comments/7fjg5d/a_hardcoded_timeout_in_mc_may_be_preventing_me/

**Comment by LexManos** [comment] 2018-01-09 21:33
The read timeout hack was removed {or atleast should be} because it is no longer needed to cheat the netty system like it was in our older version of the handshake. If you're getting time out issues when switching dimensions, or loading chunks, its a issue with the server not the handshake. Which, like I said is what the original argument was to fix, and is no longer needed.

Doing a little more digging, I was half right. I forgot it was implemented as two arguments. The Login Timeout was removed. But the Read Timeout is [still implemented.](https://github.com/MinecraftForge/MinecraftForge/blob/b215d90589bbfcfcfeefc56218e913187cbd17f5/patches/minecraft/net/minecraft/network/NetworkSystem.java.patch#L40) So, ya, it still exists. Closing.

**Closed as completed** 2018-01-09 21:41 UTC

**Comment by TheAwesomeGem** [comment] 2018-01-10 03:43
What about modpack with over 240+ mods like Modern Skyblock. You cannot join the server due to how long it takes you to sync with the server at which point, the login timeout kicks you out. Why not make that configurable?

**Comment by LexManos** [comment] 2018-01-10 08:07
Because you CAN connect to servers with 240+ mods. It sounds more like you just have a crappy server or something else. You're making a baseless assumptionn of what the issue is. Most notably that you're referencing two separate things in the login sequence as the same thing. Back when we removed the login timeout override I created a test that held the fml handshake in a pending state with a sequence of pings for 5 minutes and it had no issue with the final login. This may be an issue with your server or clients dropping or not sending the keep alive packets. 

So, come back.with a reliable test case that can be reproduced. Or I'm going to have to assume your server is at fault here. As all tests on my end are passing just fine.

**Comment by mezz** [comment] 2018-01-10 16:47
There's probably a mod or mods doing too much work when you connect to the server.
JEI used to do that, and it would cause timeouts if it took too long. I had to move it to load at a better time.

**Comment by TheAwesomeGem** [comment] 2018-01-10 17:31
Seems like JEI Resources with JEI Block Drops are causing this. Removing the mod and all of my players can connect again.

**Comment by mezz** [comment] 2018-01-12 05:16
In the past I have seen issues with JEI Block Drops taking a long time.
