### ISSUE TITLE
[1.16] Issues when enabling both stencil buffer and "Fabulous" graphics 

### ISSUE THREAD

**Issue by malte0811** [MinecraftForge/MinecraftForge#6995] opened 2020-07-19 07:43 UTC
**Minecraft Version:** 1.16.1

**Forge Version:** Known to occur on 32.0.67, 32.0.69 and 32.0.70 (a3edfd3748d10a6781518bda7c65b07d41dfb338 running in a Forge dev workspace)

**Logs:** https://gist.github.com/malte0811/f7e488085d2f43e6d39617131be1bdbd

**Steps to Reproduce:**  
 Assuming a Forge dev workspace on a3edfd3748d10a6781518bda7c65b07d41dfb338 (currently the latest 1.16 commit)
 1. Make sure the [stencil buffer test mod](https://github.com/MinecraftForge/MinecraftForge/blob/1.16.x/src/test/java/net/minecraftforge/debug/client/rendering/StencilEnableTest.java#L31) is enabled (this is the default).
 2. Launch MC with test mods (`forge_test_client` gradle task).
 3. Create a superflat world (any world will most likely work).
 4. Enable "Fabulous" graphics
 5. Observe log spam

**Description of issue:**
This was originally reported in https://github.com/BluSunrize/ImmersiveEngineering/issues/4102. Enabling both stencil and fabulous graphics results in log spam and render issues.

Changing `useCombinedDepthStencilAttachment` does not affect this issue.

**Comment by Protected** [comment] 2020-08-16 11:52
I can confirm that this is still happening in 32.0.108 .

**Comment by MrDFLL** [comment] 2020-10-16 08:12
it Happens to me too

**Comment by malte0811** [comment] 2021-08-15 15:26
Why did you re-open this? Is my fix broken?

**Comment by pupnewfster** [comment] 2021-08-15 15:29
Probably because given 1.16 is still LTS and this is still an issue there as the fix was for 1.17, it makes sense to still track it for if people run into it in 1.16.

**Comment by gigaherz** [comment] 2021-08-15 16:02
Yep, I merged into 1.17 but not 1.16, so the commit's "closes x" bit was for the wrong version.

**Closed as completed** 2021-11-20 14:07 UTC
Labels: Rendering, 1.16
