### ISSUE TITLE
[1.17] Forge LiquidBlock constructor is broken

### ISSUE THREAD

**Issue by Luis-St** [MinecraftForge/MinecraftForge#8016] opened 2021-08-18 15:31 UTC
Minecraft Version: 1.17.1

Forge Version: 1.17.1-37.0.36

Logs: https://gist.github.com/Luis-st/54474d4ee2dd1afad9989f3357aa4759

Steps to Reproduce:
 1. register a custom LiquidBlock for a custom Fluid and use the forge constructor 

Description of issue:
Forge added a new constructor to the LiquidBlock, which takes a Supplier, 
but this Constructor is broken because the vanilla Field 'fluid' is not replaced with the Supplier Field 'supplier'.
In addition the Field 'stateCache' is not correctly set, because the Forge Constructor only set the Field to a new 
ArrayList and doesn't add the required FluidStates to the list

The only fix for the bug is at the moment to extends the LiquidBlock and replace all vanilla Fields with the Forge Supplier

**Comment by Lanse505** [comment] 2021-08-18 15:43
Duplicate of #8002 

Fixed in #7992

**Closed as completed** 2021-08-18 16:35 UTC
