### ISSUE TITLE
IRenderHandler is not getting all needed fields

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/MinecraftForge#6768] opened 2020-06-12 11:48 UTC
**Minecraft Version:** 1.15.2
**Forge Version:** 31.1.37

**Description of issue:**
The IRenderHandler  interface used for example custom weather, sky & clouds has no MatrixStack argument. This should be changed as these arguement are avilable & 1.15 no longer uses the global rotate state from GL11, so its complicated to recreated the used matrix stack.

**Comment by covers1624** [comment] 2020-06-12 12:40
Duplicate of: https://github.com/MinecraftForge/MinecraftForge/issues/6439 Associated PR: https://github.com/MinecraftForge/MinecraftForge/pull/6537

**Closed as completed** 2020-06-12 22:42 UTC
