### ISSUE TITLE
[1.14.4-28.0.95] Can't keep connection by making player operators

### ISSUE THREAD

**Issue by snowstep115** [MinecraftForge/MinecraftForge#6132] opened 2019-09-07 17:47 UTC
**Minecraft Version:** 1.14.4

**Forge Version:** 28.0.95

**Logs:** https://gist.github.com/snowstep115/38c0de729e99bfd088778ed7b1427ebb

**Steps to Reproduce:**
 1. Execute /op <user-name> at server console
 2. lost connection

**Description of issue:**
Here is a client-side screenshot.
http://snowstep115.pr-ac.jp/forge/20190908024204.png

**Comment by 2iguys** [comment] 2019-09-07 23:13
feel dumb, just found this issue with the same problem, can confirm that /op in console is the cause as far as my testing is concerned.

as for now, keeping your player deopped and deleting the old ops.json seems to resolve being able to reconnect. (you just can't do anything OP till issue is resolved i guess?)

**Comment by tterrag1098** [comment] 2019-09-08 06:25
Fixed via f777aba2273cf3901b09c81379cea34591b8edd8

**Closed as completed by tterrag1098** 2019-09-08 06:25 UTC
