### ISSUE TITLE
[1.12.2] Unalbe to open chests

### ISSUE THREAD

**Issue by Draskh** [MinecraftForge/MinecraftForge#4647] opened 2018-01-02 23:52 UTC
I updated forge from 1.12.2 - 14.23.1.2566 to 1.12.2 - 14.23.1.2583. After that I was unable to open chests. I have to downgrade forge to resolve this.

**Comment by liach** [comment] 2018-01-03 02:45
Dupe of #4613. Please search the forum and issue tracker before opening a new one!

**Closed as completed** 2018-01-03 02:56 UTC
