### ISSUE TITLE
PotionExpiryEvent is not called on the client side

### ISSUE THREAD

**Issue by eerussianguy** [MinecraftForge/MinecraftForge#8506] opened 2022-03-10 02:50 UTC
**Minecraft Version:** 1.18.2

**Forge Version:** 40.0.12

**Description of issue:**

Looking at this patch:
https://github.com/MinecraftForge/MinecraftForge/blob/df3c7ce19aceaacec1aee31c3c0125fdd4409de2/patches/minecraft/net/minecraft/world/entity/LivingEntity.java.patch#L46

The event is only posted after the side check. Of course mob effects are removed only on the server, however given that this is really the only way to know when potions are expiring, it's useful to be able to perform actions on both sides.

**Comment by sciwhiz12** [comment] 2022-03-26 07:13
Confirmed on 1.18.2-40.0.32 through code inspection. However, this looks to be intended, as the `PotionEvent`s related to expiry and removal (as well as addition, if I understand correctly) are fired only on the logical server through `Level#isClientSide` checks. Additionally, because the event has the side-effect of cancelling the expiry of the potion, it is not safe to move the event to fire before the side check, due to possible desync.

Closing as event works as intended. If you feel that a client-side event for potion expiry or removal (and addition) is useful and needed, please file a feature request or create a PR.

**Closed as completed by sciwhiz12** 2022-03-26 07:13 UTC
Labels: Bug, Wont Fix/Works As Intended, 1.18
