### ISSUE TITLE
Removing mod that adds dimension makes saves inaccessible

### ISSUE THREAD

**Issue by purpleposeidon** [MinecraftForge/MinecraftForge#3331] opened 2016-10-25 22:10 UTC
1. Have an SSP world that's been run with a mod that adds a dimension.
2. Remove it.
3. The world is no longer listed in the save selection screen, and the following error is printed to the console. This is with forge-1.10.2-12.18.2.2114.

```
[14:44:19] [Client thread/ERROR]: Exception reading […]/saves/New World/level.dat
java.lang.IllegalArgumentException: Invalid dimension id 4
    at net.minecraft.world.DimensionType.func_186069_a(DimensionType.java:77) ~[atm.class:?]
    at net.minecraft.world.storage.WorldInfo.<init>(WorldInfo.java:256) ~[baa.class:?]
    at net.minecraft.world.storage.SaveFormatOld.func_186353_a(SaveFormatOld.java:102) [azz.class:?]
    at net.minecraft.world.storage.SaveFormatOld.func_75803_c(SaveFormatOld.java:82) [azz.class:?]
    at net.minecraft.world.chunk.storage.AnvilSaveConverter.func_75799_b(SourceFile:57) [azw.class:?]
    at net.minecraft.client.gui.GuiListWorldSelection.func_186795_e(SourceFile:35) [big.class:?]
    at net.minecraft.client.gui.GuiListWorldSelection.<init>(SourceFile:28) [big.class:?]
    at net.minecraft.client.gui.GuiWorldSelection.func_73866_w_(SourceFile:43) [bie.class:?]
    at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:495) [bft.class:?]
    at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:965) [bcx.class:?]
    at net.minecraft.client.gui.GuiMainMenu.func_146284_a(GuiMainMenu.java:252) [bga.class:?]
    at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:460) [bft.class:?]
    at net.minecraft.client.gui.GuiMainMenu.func_73864_a(GuiMainMenu.java:553) [bga.class:?]
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548) [bft.class:?]
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517) [bft.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700) [bcx.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055) [bcx.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

**Comment by LexManos** [comment] 2016-10-25 22:22
Thats not a dimension its a world type. How would you expect to load say, a Void world without the game knowing what the void world is?
What exact mod did you add/remove and what world type did you select?

**Comment by Niko-sk2x** [comment] 2016-10-25 22:25
I may be wrong here, but I think `DimensionType` != `WorldType`

**Comment by LexManos** [comment] 2016-10-25 22:26
You are wrong, the classes are highly bundled together in 1.10.2.

**Comment by Niko-sk2x** [comment] 2016-10-25 23:00
I'm sure it is possible to add WorldType without adding DimensionType, and add DimensionType without new WorldType, just to confirm that I checked the code and I don't see any reason why they would be related. Dimension types in vanilla are overworld, nether and end. World types are default, flat, large biomes etc...

They seem completely unrelated and this error is clearly about dimension types, not world types.

**Comment by LexManos** [comment] 2016-10-26 00:08
HUmm I may be mistaken, could of sworn this was the loading of the world type... Been a while since I looked at it.
I'll look at it when I get home. Curious when they moved this data to the level.dat. If this is the case then im going to have to go in and write a re-direct because in Forge there can be multiple dimensions with the same DimensionType.

**Comment by purpleposeidon** [comment] 2016-10-26 00:51
The mod is Harvest Festival. As far as I'm aware it doesn't add a world type like the standard/superflat/amplified/Biomes of Plenty thing.

**Comment by GirafiStudios** [comment] 2016-10-26 03:40
The problem is that Harvest Festival was saving data to the level.dat. It was fixed in 0.5.6, so updating Harvest Festival should fix the problem :)

**Comment by joshiejack** [comment] 2016-10-26 03:42
For what it's worth I was saving data the same way the ender dragon does. I changed to use world saved data in newer versions because of this error 23 days ago. It's not simply just adding/removing dimensions. The issue was that it's trying to get a DimensionType for a dimension that doesn't exist anymore when loading the DimensionData, and because the id no longer exists, it throws the error.

![Code](http://i.imgur.com/Iqx1REV.png)

**Comment by LexManos** [comment] 2016-10-26 08:02
Ya, i've looked into this. The system that the end dragon uses is a reminant of Mojang's 1/2 done Dimension type system. 
Vanilla assumes only one dimension is using a type at a time.
In Forge we change this.
When I get a chance I'll look into changing this function to go with the normal dimension ID not type.
However, Tomarrow i'm leaving for a convention and will be back Tuesday so i'll hold off.
As Girafi said, your specific issue should be fixed by doing and upgrade of Harvest Festival

**Closed as completed** 2017-03-15 09:53 UTC
Labels: Bug
