### ISSUE TITLE
Sheets class classloading issue with banner patterns

### ISSUE THREAD

**Issue by MehVahdJukaar** [MinecraftForge/MinecraftForge#8976] opened 2022-08-16 18:35 UTC
**Minecraft Version:** 1.19

**Description of issue:**
The Sheets class contains some statically initialized maps that iterate over the registered banners. This worked fine when patterns were an enum but since they are not using a proper registry loading that class too early, as it's usually done when one references some atlases resource locations, those maps are initialized and they might not contain modded banner patterns. This obviously renders them invisible on banners. Should be up to forge to repopulate these, probably right before those textures get stitched

**Comment by sciwhiz12** [comment] 2022-08-16 18:37
Please provide a proper example case and/or steps to reproduce the issue, so we can absolutely confirm that any proposed fix works.

**Comment by MehVahdJukaar** [comment] 2022-08-16 21:54
To reproduce one can simply load the sheets class during mod init by referencing it and its internal maps will be initialized. This makes it so modded banner patterns will render invisible

**Comment by ChampionAsh5357** [comment] 2022-08-28 21:27
> To reproduce one can simply load the sheets class during mod init by referencing it and its internal maps will be initialized. This makes it so modded banner patterns will render invisible

This is not a valid test case. You are arguing Forge is at fault that a mod classloads something before it's supposed to.

I have written my own test case and cannot replicate your findings. Forge loads the `Sheets` class after banner registration, so unless you are forcing the classload yourself beforehand, then it is a nonissue.

Looking at your [code](https://github.com/ModdingForBlockheads/Waystones/blob/6c26157a39baeea913e378920304e1c9fe317790/forge/src/main/java/net/blay09/mods/waystones/ForgeWaystones.java#L15), you are classloading sheets during mod initialization. This shouldn't be done until at least `FMLClientSetupEvent` or any of the other model/texture events.

Closing this as the issue lies with the mod and not Forge.

**Closed as completed by ChampionAsh5357** 2022-08-28 21:27 UTC
Labels: Bug, Not Us, 1.19

**Comment by MehVahdJukaar** [comment] 2022-08-29 00:50
That's not my code. Also yes or course its not forge, it's vanilla but mods can't be expected to manage what class gets loaded at what time and it seems like something that could be easily fixed by forge this providing a better environment for everyone. If nothing is made of this I guess it doesn't matter anyways as I'm shipping a fix with my main mod so most people won't notice this issue if other mods mistakenly classload a class that they shouldn't (which I can't blame them, it also does not show any issue until you add mods that add banner patterns so it's hard to notice too hence the need for forge to do something about it). I really can't see any reason why this wouldn't be eligible to be added and I'm saying this as somebody that spent quite some time trying to figure out why in the world would other mods banner patterns not work

**Comment by ChampionAsh5357** [comment] 2022-08-29 01:42
> I really can't see any reason why this wouldn't be eligible to be added and I'm saying this as somebody that spent quite some time trying to figure out why in the world would other mods banner patterns not work

In my opinion, there's a difference between adding something that fixes or solves some vanilla problem versus adding something because a mod chooses to break vanilla and asks Forge to adjust it. It doesn't make sense why a modder couldn't move a single line of code to solve the issue rather than making a change which will satisfy their bad code. I've spent numerous hours wondering why things were broken only to realize I was doing things in the wrong order (especially true when I was trying to make model loaders at first in client init similar to the mod above). That doesn't mean I should make a fix to Forge to support that wrong code. It meant I should simply fix the code.

If another member of the triage team chooses to reverse my opinion, then that's fine. However, I stand by my decision and reasoning.

**Comment by Niko-sk2x** [comment] 2022-08-29 11:47
Would it then be possible to at least detect it being done too early and log a warning? That would make it actually possible for the mods breaking it to notice the issue. By the description the mods that break it don't actually see anything being broken.

**Comment by ChampionAsh5357** [comment] 2022-08-29 12:57
Sure, if somebody wants to write a PR for a feature to check a class isn't loaded before its proper time, that's fine with me. I'd also be okay with a dedicated page on the docs where niche cases like this can be reported if the PR is considered to be a no.

**Comment by MehVahdJukaar** [comment] 2022-08-29 14:21
Yeah my whole pont is just that, since it's something that's vey hard to detect unless you are looking for it so loggin an error is another perfectly reasonable solution which has the same phylosophy that other forge feature have of forcing modders to not break internal stuff, same reason, to my understanding, as to why we have events for everything or that configs aren't loaded earlier
