### ISSUE TITLE
Colored Items spawn non-colored particles

### ISSUE THREAD

**Issue by ochotonida** [MinecraftForge/MinecraftForge#4915] opened 2018-05-07 10:52 UTC
Items colored with IItemColor will spawn non-colored particles. This is an issue for colored food items for example, because the particles that appear when the food is eaten will not be colored.

**Comment by SteveKunG** [comment] 2018-05-07 11:43
#2018

**Comment by mezz** [comment] 2018-05-13 04:48
Closing as duplicate of #2018

**Closed as completed by mezz** 2018-05-13 04:48 UTC
