### ISSUE TITLE
[1.12][2581-2576] Null exception Initializing game

### ISSUE THREAD

**Issue by aschmois** [MinecraftForge/MinecraftForge#4626] opened 2017-12-26 21:27 UTC
Exception is thrown. No mod name is mentioned in stack trace. Issue is apparent with and without optifine and forge versions 2581-2576 (2575 works).

`java.lang.NullPointerException: Initializing game
	at net.minecraftforge.client.model.ModelStateComposition.apply(ModelStateComposition.java:43)
	at net.minecraftforge.client.model.MultiModelState.apply(MultiModelState.java:67)
	at net.minecraftforge.client.model.MultiModelState.getPartState(MultiModelState.java:50)
	at net.minecraftforge.client.model.ModelLoader$WeightedRandomModel.bake(ModelLoader.java:718)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:186)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

[2581 optifine.txt](https://github.com/MinecraftForge/MinecraftForge/files/1587894/2581.optifine.txt)
[2581 no optifine.txt](https://github.com/MinecraftForge/MinecraftForge/files/1587895/2581.no.optifine.txt)
[2577.txt](https://github.com/MinecraftForge/MinecraftForge/files/1587896/2577.txt)
[2576.txt](https://github.com/MinecraftForge/MinecraftForge/files/1587897/2576.txt)

**Comment by JamiesWhiteShirt** [comment] 2017-12-26 21:54
Duplicate of #4605. As far as I know, this is an issue with mods you have installed. When #4615 is pulled it should be more clear which mod is causing it.

**Closed as completed** 2017-12-26 23:15 UTC
Labels: Forum
