### ISSUE TITLE
Enchantments with isAllowedOnBooks false still appear in search creative tab

### ISSUE THREAD

**Issue by FlashFyreMods** [MinecraftForge/MinecraftForge#9716] opened 2023-09-15 05:22 UTC
**Minecraft Version:** 1.19.2

**Forge Version:** 43.2.21

**Steps to Reproduce:**
 1. Make an enchantment that overrides isAllowedOnBooks as false
 2. Search for the enchantment or enchanted book in the search tab

**Description of issue:**
Forge has a hook in IForgeEnchantment that checks the vanilla method isAllowedOnBooks, and if this is false for an enchantment instance, allegedly prevents it from being in the creative menu on books. However, even if you set this to false (or just override the allowedInCreativeTab method and return false), it still shows up on books if you search for an enchanted book or the enchantment name. So this hook seems to have been not implemented properly. I believe it is not checking every item that is remaining during the search.

**Comment by LexManos** [comment] 2023-09-16 19:19
So, [isAllowedOnBooks ](https://github.com/MinecraftForge/MinecraftForge/blob/1.19.2/patches/minecraft/net/minecraft/world/item/enchantment/Enchantment.java.patch#L50)is actually a Forge method, why it got moved out of our extension class to a patch file, I have no idea. It's on my list of things to cleanup.  

However, im unable to reproduce your issue. I changed the implementation of that to `return this != Enchantments.SMITE` and was able to verify that I could neither enchant smite to a book on the enchanting table, nor did it show up in the search in the creative menu. So unfortunately im gunna have to close this as unable to reproduce. And would suggest you hop on the [discord ](https://discord.minecraftforge.net/) to see if people are willing to help you debug.

Perhaps you have a complex implementation of that function that is only false later in life, after the creative tabs are populated?

**Closed as completed by LexManos** 2023-09-16 19:19 UTC
