### ISSUE TITLE
[1.13.2]  Cannot replace vanilla blocks

### ISSUE THREAD

**Issue by Pyre540** [MinecraftForge/MinecraftForge#5769] opened 2019-06-02 22:06 UTC
I tried to register custom block with vanilla registry name (similar to what I was doing in 1.12.2) to replace vanilla block (e.g. blockGlass) but unfortunately it didn't work (stacktrace below).

I checked what exactly is going on and found out that there is validStates mismatch (screen below):
- valid state for BlockGlass is apparently Block{minecraft:air}
- valid state for my block is Block{minecraft:glass}

It doesn't metter what block you try to replace the valid state for it is always Block{minecraft:air}.

[Screenshot](https://i.imgur.com/SF3PD8C.png)
[Stacktrace](https://pastebin.com/Ms5XuDHZ)

**Comment by Shadows-of-Fire** [comment] 2019-06-02 22:45
this is a duplicate of #5747

**Comment by bs2609** [comment] 2019-06-04 17:17
^ duplicate of #5747, comment there.

**Closed as completed by bs2609** 2019-06-04 17:17 UTC
