### ISSUE TITLE
Minecraft Forge Empty NBT string crash.

### ISSUE THREAD

**Issue by AnodyneEntity** [MinecraftForge/MinecraftForge#1797] opened 2015-04-14 05:47 UTC
Updated all the CoFH mods, Dragon API, RotaryCraft, Mekanism and update the Forge version to 1370 and now I get this crash when the server tries to save the world or I try to manually save the world.

http://pastebin.com/p1rqsqM5

Is this purely a forge issue? Or is one of the mods I updated causing it?

**Comment by cpw** [comment] 2015-04-19 16:07
Duplicate of #1798

**Closed by cpw** 2015-04-19 16:07 UTC
