### ISSUE TITLE
[1.18.2] Blocks defined in "optional" section ignored for fences and walls

### ISSUE THREAD

**Issue by Wabbit0101** [MinecraftForge/MinecraftForge#8641] opened 2022-05-30 14:48 UTC
**Minecraft Version:** 1.18.2

**Forge Version:** 40.1.20

**Logs:** n/a

**Steps to Reproduce:**
 1. Define either a new wall or fence
 2. But that item into the "optional" section of appropriate tag (eg "minecraft:walls" or "minecraft:fences")
 3. Run MC...place 2 new items next to each other- custom items do not connect (to self or similar) as expected
 4. Move custom item tag reference into "values" from "optional"
 5. Redo test at step 3
 6. Custom item connects as expected

**Description of issue:**
For some reason the "optional" tag section is not being processed or "seen". This was tested only on single-player for both fences and walls. Did not do a general test of "optional" for other class types/tags.

**Comment by sciwhiz12** [comment] 2022-05-30 14:52
To my knowledge, Forge's addition of the `optional` section for tags was removed in a recent Minecraft version in deference to vanilla's own addition of the `required` syntax for tag elements, as described in the [Minecraft Wiki page](https://minecraft.fandom.com/wiki/Tag#JSON_format). Closing as working as intended -- removed feature will not work after its removal.

**Comment by SizableShrimp** [comment] 2022-05-30 14:52
Can you provide code references please

**Closed as not planned** 2022-05-30 14:52 UTC
Labels: Wont Fix/Works As Intended, 1.18

**Comment by Wabbit0101** [comment] 2022-05-30 16:00
Ah...too bad, the Forge implementation made for much cleaner modpack adjustment.
