### ISSUE TITLE
[1.19] Custom fluids push stronger than they should

### ISSUE THREAD

**Issue by Minecraftschurli** [MinecraftForge/MinecraftForge#8897] opened 2022-07-21 09:06 UTC
**Minecraft Version:** 1.19
**Forge Version:** 41.0.99

**Logs:** no crash, no error, no warnings

**Steps to Reproduce:**
 1. Create a custom fluid with stock settings
 2. Try to walk up stream in that fluid (you can't)

**Description of issue:**
A fluid with stock settings should push the player exactly like water does but it is somehow stronger. Debugging shows it is not happening in `Entity#updateFluidHeightAndDoFluidPushing()` so it needs to come from somewhere else.

**Comment by desht** [comment] 2022-07-21 09:29
I've also noticed this, with modded fluids with no otherwise special mechanics.  We had a brief discussion on Discord about this, and my debugging shows that flowing modded fluids definitely accelerate the player entity significantly more strongly than flowing water does (up to 2.52 blocks/sec for modded fluids vs. 1.4 blocks/sec for water).

As @Minecraftschurli mentioned, debugging in `Entity#updateFluidHeightAndDoFluidPushing()` appears to show the same vector for water and modded fluids (0.014 along the axis the fluid is flowing), but the player's `getDeltaMovement()` is definitely larger when in modded fluids.

Example: debugging at `Entity#updateFluidHeightAndDoFluidPushing()`, line 3235, with Water and PneumaticCraft Vegetable Oil, both flowing in an eastward direction:

water:
```
fluid push: deltamovement = (0.06951353868883402, -0.005, 0.0), vec = (0.014, 0.0, 0.0)
fluid push: deltamovement = (0.06961083177973318, -0.005, 0.0), vec = (0.014, 0.0, 0.0)
fluid push: deltamovement = (0.06968866625361232, -0.005, 0.0), vec = (0.014, 0.0, 0.0)
fluid push: deltamovement = (0.0697509338336435, -0.005, 0.0), vec = (0.014, 0.0, 0.0)
fluid push: deltamovement = (0.06980074789841073, -0.005, 0.0), vec = (0.014, 0.0, 0.0)
``` 

vegetable oil:
```
fluid push: deltamovement = (0.12144232420975706, -0.005, 0.0), vec = (0.014, 0.0, 0.0)
fluid push: deltamovement = (0.13544232420975708, -0.005, 0.0), vec = (0.014, 0.0, 0.0)
fluid push: deltamovement = (0.12235386098240399, -0.005, 0.0), vec = (0.014, 0.0, 0.0)
fluid push: deltamovement = (0.13635386098240398, -0.005, 0.0), vec = (0.014, 0.0, 0.0)
fluid push: deltamovement = (0.12308309041138787, -0.005, 0.0), vec = (0.014, 0.0, 0.0)
```

So the player is moving nearly twice as fast (and the delta movement fluctuates more) in vegetable oil as in water, despite the fluids having the same movement vector.  Something else is obviously influencing the player's movement here, but I can't figure out what.  Will update if I find out more though.

**Comment by desht** [comment] 2022-07-21 09:39
Another observation: items dropped in two parallel streams (one water, one vegetable oil) seem to get moved at exactly the same speed, but chickens moved faster in the vegetable oil. The discrepancy may only apply to living entities.

**Comment by sciwhiz12** [comment] 2022-08-07 06:26
Please provide a simple test mod (a source file, preferrably) that provides a fluid which can be used to reproduce the issue.

**Comment by desht** [comment] 2022-08-08 06:08
https://github.com/MinecraftForge/MinecraftForge/blob/1.19.x/src/test/java/net/minecraftforge/debug/fluid/NewFluidTest.java should work for testing, I think?

**Comment by desht** [comment] 2022-08-08 08:10
Another observation I missed last time: the strength of the fluid push appears to be dependent on the depth of the fluid at that point.  I.e. if the flowing fluid block is 8 blocks away from the source it doesn't push hard at all, but once the `level` blockstate property is 3 or more, it pushes hard enough to prevent further player movement.

Again, only applies to modded fluids, water pushes just as hard regardless of level.

**Comment by sciwhiz12** [comment] 2022-08-08 09:24
> [https://github.com/MinecraftForge/MinecraftForge/blob/1.19.x/src/test/java/net/minecraftforge/debug/fluid/NewFluidTest.java](https://github.com/MinecraftForge/MinecraftForge/blob/1.19.x/src/test/java/net/minecraftforge/debug/fluid/NewFluidTest.java?rgh-link-date=2022-08-08T06%3A08%3A31Z) should work for testing, I think?

Yep, that works to reproduce the issue (after fixing the `mods.toml` due to a recently added test mod).

Curiously, changing out the fluid type of the custom fluid to use `ForgeMod.WATER_TYPE` seemingly fixes the issue, so it's a issue with custom fluid types specifically.

**Comment by ChampionAsh5357** [comment] 2022-08-08 11:56
Looks like a missed change within `LivingEntity#checkFallDamage` where it calls the fluid wrapping method a second time if the player is not in water. Fixing this is a bit of a puzzling issue since it wraps directly into boat logic for water and that the new `Entity#updateFluidHeightAndDoFluidPushing()` is applied across all fluids at once instead of multiple times individually.

So, the solution I imagine would be to check within `Entity#updateFluidHeightAndDoFluidPushing()` itself if the fluid should check fall damage and then skip applying the acceleration a second time if not. This should either occur if a) the player can swim in the fluid, b) the player takes no fall damage as soon as they enter the fluid, or c) a custom method which handles the associated logic.

**Comment by exceldxdy** [comment] 2022-09-26 20:09
I have a solution for this problem, found it while searching how to make a custom biome (I know, there's no relation between both things).
The solution is override the "move()" method while registering the fluid type (or override it in the custom class that extends FluidType).
Taking the example mod, the solution would look something like this:

```
public static RegistryObject<FluidType> test_fluid_type = FLUID_TYPES.register("test_fluid", () -> new FluidType(FluidType.Properties.create())
    {
        @Override
        public boolean move(FluidState est, LivingEntity ent, Vec3 vctMov, double grav) {
                    Vec3 movEnt = ent.getDeltaMovement();
                    if (est.isSource()){
                        if (movEnt.y > 0d) {
                            ent.setDeltaMovement(movEnt.multiply(1d, 1d, 1d)); //invented, I don't know the real water multiply values
                        } else if (movEnt.y < 0d) {
                            ent.setDeltaMovement(movEnt.multiply(1d, 1d, 1d)); //invented, I don't know the real water multiply values
                        } else {
                            ent.setDeltaMovement(movEnt.multiply(1d, 1d, 1d)); //invented, I don't know the real water multiply values
                        }
                    } else {
                        if (movEnt.y > 0d) {
                            ent.setDeltaMovement(movEnt.multiply(0.014d, 1d, 0.014d));
                        } else if (movEnt.y < 0d) {
                            ent.setDeltaMovement(movEnt.multiply(0.014d, 1d, 0.014d));
                        } else {
                            ent.setDeltaMovement(movEnt.multiply(0.014d, 1d, 0.014d));
                        }
                    }

                    return false;
                }
        @Override
        public void initializeClient(Consumer<IClientFluidTypeExtensions> consumer)
        {
            consumer.accept(new IClientFluidTypeExtensions()
            {
                @Override
                public ResourceLocation getStillTexture()
                {
                    return FLUID_STILL;
                }

                @Override
                public ResourceLocation getFlowingTexture()
                {
                    return FLUID_FLOWING;
                }

                @Nullable
                @Override
                public ResourceLocation getOverlayTexture()
                {
                    return FLUID_OVERLAY;
                }

                @Override
                public int getTintColor()
                {
                    return 0x3F1080FF;
                }
            });
        }
    });
```
Also set the "canPushEntity()" property to false.

**Comment by ChampionAsh5357** [comment] 2022-09-26 20:49
I mean, a simpler patch would be just to divide the vector by 2 until the logic is thought through and adjusted.

**Comment by exceldxdy** [comment] 2022-09-26 21:40
Of course, the simpler solution is just divide by 2 the x and z axis of the movement vector, but this solution has the advantage of being general, by that I mean that the default custom fluid has no physics for entities that are sinking/rising on the fluid, this solution (that it's not mine, all the credit is for the developer of Dreamland mod, dragoni7) also adds that physics for entity sinking/rising.

**Comment by ChampionAsh5357** [comment] 2022-09-26 22:16
> but this solution has the advantage of being general

There's not really a generic here; it's purely entity goes up and down which breaks all logic for water creatures and some land creatures.

> by that I mean that the default custom fluid has no physics for entities that are sinking/rising on the fluid

That's a bug. I do have a PR (#8754) that fixes that issue to apply the `#canSwim` towards it, but it needs a lot more work since a lot of the patches are highly complex just for a more verbose understanding. This just says all entities perform this motion, which essentially delegates the entity behavior in the fluid to the fluid itself.

> also adds that physics for entity sinking/rising

Not really, this just does bobbing, which would be fixed with the PR I mentioned. Additionally, this disables the actual physics in favor of a bobbing motion.

I don't mind the fix, especially since there's still work needed to be done. However, do not say it's a solution to the problem when it doesn't solve the initial problem. Also, whenever you present a fix, always list the benefits and drawbacks; otherwise, it could cause arguments between you and those who understand the issue and complaints from those who do not.

**Comment by LexManos** [comment] 2023-07-15 00:45
Unfortunately the check for fall damage modification does not appear to address the issue correctly. The concept of the 'default fluid' acting like water does not work considering the default values from the builder more accurately reflect lava. To do this properly would require keeping track of which fluids you are in and how they effect fall damage. Or removing the optimization/vanilla behavior of checking the fluid before before applying fall damage. This would break vanilla behavior. It would also still make your fluid not correctly prevent fall damage from tall enough heights. 

So right now the current solution is manually fix the deltas yourself in the move function, or add yourself to the water fluid tag and deal with the side effects.

Unfortunately the Fluid system is something that needs to be reworked and figure out all these divergences from intention that have crept in over time.

**Closed as completed by LexManos** 2023-07-15 00:45 UTC
Labels: Bug, Confirmed, Fluids, 1.19, Pending Rework
