### ISSUE TITLE
[1.8] TESR Item Rendering Hook is missing

### ISSUE THREAD

**Issue by Thog** [MinecraftForge/MinecraftForge#1582] opened 2014-12-17 18:10 UTC
I would like to use TESR but the render as Item (GUI, third person, first person) use TileEntityChestRenderer.

Because of that https://gist.github.com/Thog/84ae6576a1653a3f3694#file-gistfile1-java-L84

Best Regards, Thog.

**Comment by Nuchaz** [comment] 2015-04-27 20:56
Was this issue ever sorted? I can't find any reference in the changelogs that suggest so. This is one of the 2 major issues that has kept me from being able to update BiblioCraft to 1.8. 

I basically need the same stuff I had before with IItemRenderer. My most complex example is the BIblioCraft Atlas. For that I need to render the vanilla map, then layer several models on top of that. Since most of the models are waypoint pins placed on the map, I cannot know the location of them in advance, that has to be computed at run time. 

Another example is my framed blocks, they are rendered with textures that are chosen by the user so I have no foreknowledge of what textures will be rendered. I have to be able to change textures on demand, including textures in mods that I have never heard of. 

As far as I know, none of that is possible yet, unless I've missed something. 

I vote we just bring back IItemRenderer. It was easy to use and did everything I needed.

**Comment by ganymedes01** [comment] 2015-04-27 21:01
@Nuchaz No answer on it yet.
I'm sticking to 1.7 until they fix this. If that day never comes I'll probably use RenderCore (https://github.com/Parker8283/RenderCore) as it offers a similar functionality to the late IItemRenderer.

**Comment by Parker8283** [comment] 2015-04-27 21:04
GL Access has been removed from Blocks and Items. From what I heard, it is because Mojang is gearing towards only have data on the client, like the new JSON models, and in doing so, you would have no GL Access. No, it has not been reimplemented, and my attempts to readd them have been shot down because they either readded GL Access, or with the response "use models".

**Comment by chibill** [comment] 2015-04-27 21:38
Just use the model stuff. (If build craft can use it so can you..  )

**Comment by Parker8283** [comment] 2015-04-27 21:46
It is not my resistance to using models; believe me, I think that the concept of the system is good. However, it is how incomplete the system. There's no point in stirring this up again, because nothing good will come out of it. However, you can't really use models with TESRs, which is the real problem here. In that, if you try to render a TESR as an ItemStack, it renders as a vanilla chest. Which is the problem in this issue, and the reason it is still open; because it is unresolved and my attempts to resolve it have been shot down.

But like I said, I really don't want to stir this up again, so I'm done arguing about it. For now.

**Comment by ganymedes01** [comment] 2015-04-27 22:47
BuildCraft can use it because the most complicated thing it needs to render is a pipe...
Try rendering an aura node, or something that moves =P

**Comment by chibill** [comment] 2015-04-27 22:55
They used the ability to bake a model for it using the event.. Which you could do...

**Comment by ganymedes01** [comment] 2015-04-27 22:57
Yeah that works for most things, but not everything. There's a lot more to rendering than getting the shape right.

But I'm doing what parker did and get out of this before it gets stirred up again =P

**Comment by LexManos** [comment] 2015-04-27 23:20
If you have a specific need that is not filled. Explain it in detail. @Nuchaz 's seems fairly straight forward. And is supported by the model system. Albeit as i've stated to Fry before, having a nicer access to a 'nested' model would be useful. {Which is what his is, map model + icon models} Placement is simple using the ISmartModel's

As for his Framed blocks. Those are an interesting thing, being able to switch texture atlases in models would be a challenge but worth looking into. 

The MAIN downfall I see in the current Model system is it doesn't have Bilboard style models exposed. Everything else that modders have requested can be done with the model system. 
Its something that is worth looking into. IF modders can articulate their wants more then 'I want the old stuff back!'

Poking @RainWarrior as he is Forge's rendering guy.

**Comment by Parker8283** [comment] 2015-04-27 23:26
If someone shows me how to render a TESR as an ItemStack with the current system (which I've yet to see, although I've heard we can (apparently)), I'll be happy, as that's the one big thing that we can't do now, and is the biggest roadblock for me to fully jump to 1.8.

**Comment by LexManos** [comment] 2015-04-27 23:29
As I asked, please do not post what is essentially 'I want the old stuff' without giving proper explanation on what you're trying to do and why exactly the Model system does not work for you.

**Comment by ganymedes01** [comment] 2015-04-27 23:29
It's not so much as "I want the old stuff back", it's "the new stuff doesn't allow us to do what the old stuff did".

I need GL calls during the rendering of some of my models. To control lighting, effects, movement... For example, I have a model that has parts that glow in the dark. Can I do that with the current system?
What about rendering an entity as an item, could I do that dynamically, or would I have to create a JSON model for each entity? How would that work for entities that emit particle effects?

And the most obvious reason of all... Having a TESR model and then having to create it in a JSON format just to have it render as an item is silly...

**Comment by ganymedes01** [comment] 2015-04-27 23:30
In my case specifically, I have a mod that adds heads for several entities.
"Extracting" those heads off of the entities models is already complicated enough as it is, imagine me having to turn them into JSON? What about entities that use OBJ models, what would I do with those?

**Comment by ganymedes01** [comment] 2015-04-27 23:32
Can you do spheres with the new model?

**Comment by ShetiPhian** [comment] 2015-04-27 23:33
I bookmarked this forum topic for future use;
Render Tile Entity in inventory: http://www.minecraftforge.net/forum/index.php/topic,28873.0.html

**Comment by LexManos** [comment] 2015-04-27 23:43
You would load them like obj models. Fry was working on a update obj loader, not sure where he got with that. {I stay away from the specifics of rendering}
Particles: Entities can do that {items are entities}
Movement: Depends on what you mean.
Custom Lighting: I defer to fry, this is one of the few things I find legit, and I don't think can be done with models. However, a system could be designed.
As for JSON: JSON has not been a issue for ages. There are plenty of solutions to this both pragmatic and in support for other formats that address this. 

If you have a TESR 'model' it should be representable by some model format. 
Just a quick example. Something that would have a 'glow in the dark' segment would simply be a normal model + a sub-model that had lighting disabled. Something that would be completely possible with a 'stacked model' style system if it were designed properly.

As for spheres, yes you can do spheres.

@ShetiPhian Hijacking any instance of any core MC class is BAD. It causes incompatibility with others. That example should be pretty obvious why. And as I stated above, i've been specifically reluctant/holding back on hokking that exact spot until I can get modders to explain why they need it beyond 'I want the old stuff' The idea is to have modders actually TRY the new model system. A LOT of the old TESRs were only TESRs because they felt like loading a model.

**Comment by ShetiPhian** [comment] 2015-04-28 00:01
Just as TheGreyGhost pointed out,  If a mod doesn't daisy chain, all the mods loaded before it break. So that method is not ideal.

Personally I doubt I'll need it once obj support is back.

**Comment by LexManos** [comment] 2015-04-28 00:12
Then you should work with fry and get obj support in. It had to be re-written for the new model system. And there was someone who was working on it but he disappeared without pushing anything out.
OBJ IS WANTED. So go for it!

**Comment by Nuchaz** [comment] 2015-04-28 00:16
Thanks for chiming in here @LexManos. I wasn't aware nested custom models for item rendering was even possible. Does anyone have any examples on this? Looking at forges code, I can't quite wrap my brain around how it might work. I need an example using likely the newer .b3d model format. JSON models just won't do it for me, and I'll explain why.

This is another good example for an item rendering issue I have no clue how to solve. I have an item called the Waypoint Compass, which is a round compass model with a needle that points to an custom x, y, z coordinate that player inputs or gets from the atlas or map frames in BiblioCraft. So to do this, on the compass item I use the updateEntity() method to real time calculate needle position based on player yaw position and a damped harmonic motion equation (to give the needle a little bounce based on rotation speed of the player, the faster yaw changes, the larger the needle bounce). Simply put I am just calculating a float which I then save to NBT on the ItemStack. The item renderer then reads that float value and updates the rotation of the needle in real time. The compass itself is a nested OBJ model with 2 models. The base and the needle. 

The compass relates to the atlas in that if the atlas NBT contains a compass, the atlas item icon will change to be the atlas icon with the 3d OBJ compass layered on top. The needle position updates in all views, (inventory, first person, and third person).

For my framed blocks and their item counterparts, I'll try to explain how I do it now, maybe that will help us figure out a better solution that works in 1.8. Currently is what happens is you take one of these framed blocks in ItemStack form and put it on a "paneler" block along with an ItemStack of whatever block you want to get the texture from and apply to the framed block. The paneler tile then looks at the block with the texture you want and gets the IIcon.getIconName() string and saves that to the framed block NBT. The item renderer then reads the NBT and caches a ResourceLocation which I bind to the model when rendering. (which are all OBJ models). Basically the same thing happens in block TESR form too. The IIcon name string is transferred to the TileEntity and on NBT load a ResourceLocation is cached which the TESR reads and bindTexture.

Your right in that a lot of old TESRs are only that because we are loading custom models. I could never get OBJ models to work with the SimpleBlockRenderer. That and most of my blocks can change on demand, I was never sure how or if there was a way to change a baked model on demand. I'm sure it is much different now and that would be another something I think need an example of to understand better.

I think between this post and my last, that explains what I am having trouble with in updating to 1.8.

**Comment by ShetiPhian** [comment] 2015-04-28 00:38
Most of my stuff easily converted to the new json format, and some things even look better.
Stacked models would get rid of most of obj's (truthfully I don't have many), and maybe the rest can become b3d.

I do have one block giving trouble and not sure if this can be done with the current system.
The model can be a json, but the four textures in the json need to be placeholders that get replaced while rendering.
I can't pre-build a json for each wood combination, as its probably the most common thing added to the ore dictionary.

**Comment by Victorious3** [comment] 2015-04-28 05:07
I think I mentioned it already, but what about rendering text? ![Circuit](http://puu.sh/dB3hQ/2e6524f127.png)

**Comment by LexManos** [comment] 2015-04-28 06:32
Rendering text is simply flat faces on the model with texture coordinates that align to textures that look like ascii characters.

**Comment by laz2727** [comment] 2015-04-28 07:51
It doesn't really work with things that can have any text on them.

**Comment by Kubuxu** [comment] 2015-04-28 08:29
For example ZettaIndustries has RFMeters which can be collected and all the time show total RF flown on the 7seg screen.

**Comment by LexManos** [comment] 2015-04-28 08:50
With ISmartModels it totally can!

**Comment by Kubuxu** [comment] 2015-04-28 08:55
But this means that I would have to impement 7seg rendering two times. One for the in world on TESR (updating static renderer almost every tick is not good idea) and on ISmartModels for ItemRenderer.

I my case the solution would be to allow rendering of ISmartModlels in TESR.

**Comment by LexManos** [comment] 2015-04-28 08:59
You can render ISmartModels in the TESR, you can do whatever you want you are direct access to GL crap.

**Comment by Victorious3** [comment] 2015-04-28 14:19
@LexManos It isn't that easy. If it was, I'd already done it. The FontRender isn't using its 900 lines for nothing, sadly. MC's font isn't monospaced, and that's where the problems start. Its also spread to 224 textures. I know that it is doable, it has been done by MC anyways, but I'm not keen to copy paste most of the font renderer that already exists, it would be extremely painful to do so, and completely unproportional for something that is purely cosmetic.

**Comment by LapisSea** [comment] 2015-09-01 13:31
I can't get over that someone would even argue that IItemRenderer is not needed in 1.8! What about transparent rendering? What about animated rendering? What about dynamic vertex or UV rendering? What about dynamic matrix transformation? What about blend functions? What about heavy usage of static java values? What about the fact that not every modder wants to give an option to resource packs to change their models? The list goes on...

**Comment by heldplayer** [comment] 2015-09-01 13:47
As far as I know, it is currently not possible to render items that use shaders as part of the rendering. (Just adding to the list @LapisSea made)

**Comment by LapisSea** [comment] 2015-09-01 13:59
@heldplayer Yes thank you

**Comment by LexManos** [comment] 2015-09-01 19:21
"The old one is so much better and more flexible that I wouldn't even know about json models if the IItemRenderer and ISimpleBlockRenderingHandler was still a thing!"

You just hit on the head one of the many main reaons that it was removed, modder like you are to lazy and stubborn to even give the new system a chance unless forced.
And progress doesn't happen unless people give it a chance.

As for all your complaints about what cant be done. They all have one thing on common you kept using the word dynamic. AND THATS THE OTHER MAIN RESON A NEW SYSTEM IS/WAS NEEDED. People like you who have to be special snowflakes and screw with the gl state/stack. The new system does 99% of what you need in a extreamly controlled and efficient way. 

Transperancies, animations, can be done in the new system, shade and fry are on that. The rest of your complaints are about "dynamic" shit which is just stupid.

As for another reson for not having both is that NO the old system wont live side by side the new one without major changes and restrictions to modders or forge taking control of the full gl stack which would be atrocious for performance.

Point is, if you have specific downfalls we can adress them and see what we can do. But if you're just going to continue the "GIVE ME ALL THE SHIT SO I CAN SCREW IT UP" Tantrums, you can fuck off.

**Comment by ganymedes01** [comment] 2015-09-01 19:43
But Mojang has special cases for item rendering and it doesn't fuck up the whole game. We're talking about a 1 line patch. There's no need to re-write or break anything existing to do that.

As for modders doing things wrong with OpenGL... well then that's the modders fault isn't it? I don't see why restrict everyone from using it just because some numnuts might use it wrong. The mod who does it wrong will be easily identifiable :P

**Comment by LexManos** [comment] 2015-09-01 19:58
Youre telling me to make a "one line patch" and deal with the fuckload of thimgs that the modders break and we have to cleanup.

As for monang having that stop gap in there, THATS EXACTLY WHAT IT IS. A stop gap until they get the time to move everything over. There has been some issues on mojangs end that have caused issues with the rendering engine. I wont go into that more then to say the engine is in progress. Sonhelp progress it, dont hold it back.

And no, the mod doing it wrong is NOT easily identifiable because youre so deep in the gl shit nothing is tracked. FORGE specifically ME gets blamed for all your modders derping gl up because its so difficult to track who did it.

Peovide me a solution that prevents modders from fucking up others, leaking states, identifies and corrects those who do shit wrong. Then maybe ill consider it. But youre not getting IItemRenderer back in its old form. In a perfect world i would have to worry about it, but modders are far less then perfect, hell in some cases they are flat out malicious and i get the flack.

**Comment by asiekierka** [comment] 2015-09-01 20:14
@LexManos - There is no solution. Either modders will be left unhappy due
to them not being able to do thing X, or they will have direct OpenGL
access and you'll get the blame, or Forge will become bloated due to all
the special cases you need to add to make everyone happy.

Pick your poison.

2015-09-01 21:58 GMT+02:00 LexManos <notifications@github.com>:

**Comment by ganymedes01** [comment] 2015-09-01 20:45
What I meant by "easy to identify" is that any user who had the game working properly and after adding one mod saw all sorts of rendering issues, would probably be able to guess that the newly added mod is the culprit.

We have been using GL freely for years and it works doesn't it? Fucks ups show up every now ans again, but that's not exclusive to rendering. Modders do things wrong everywhere... And from what I've seen, forcing restrictions tends to cause even more fuck ups because of lazy workarounds, and core modding done wrong.

If a rendering error gets blamed on Forge, ask the user to reproduce it without mods (as you always do). If the error goes alway, problem solved, it's left to the user to figure out who's causing it.

**Comment by LapisSea** [comment] 2015-09-01 20:46
@LexManos first of all there is no reason to get mad. Let's try to say diplomatic.

"You just hit on the head one of the many main reaons that it was removed, modder like you are to lazy and stubborn to even give the new system a chance unless forced.
And progress doesn't happen unless people give it a chance." 
You have no right to say that what so ever. I gave it more than a chance. And it is jut simply not possible because... Well because it is a script! 

"As for all your complaints about what cant be done. They all have one thing on common you kept using the word dynamic. AND THATS THE OTHER MAIN RESON A NEW SYSTEM IS/WAS NEEDED. People like you who have to be special snowflakes and screw with the gl state/stack. The new system does 99% of what you need in a extreamly controlled and efficient way." 
The new system does 99% of what you need to render a standard item. Not to render anything more complicated than that.
Yes you are right it is extremely controlled. It is so controlled that you do not have any flexibility whatsoever. And a not so right on "extremely efficient" it is about 5% more efficient.

"Transperancies, animations, can be done in the new system, shade and fry are on that. The rest of your complaints are about "dynamic" shit which is just stupid."
That is your opinion. To you it is stupid to me it is an extremely powerful tool to do yaw dropping things. If they can be done than I really can't find a way. So i am asking how? But keep in mind that this things are advanced in the rendering.

"As for another reson for not having both is that NO the old system wont live side by side the new one without major changes and restrictions to modders or forge taking control of the full gl stack which would be atrocious for performance." So what is is our choice to use a 5% less efficient system on 10 items.

**Comment by LexManos** [comment] 2015-09-01 21:08
I dont have the stats with me for the systems that weve had in place to test things, but its not a "5%" or "10%" thing its a exponetial issue based on things accessed my modders.



Before this argument goes in yet another fucking circle.
State your EXACT cases of things you are wanting to do.
Ill have fry and shade look at it and give you a solution.

I know for a fact that quite literally you can do the exact same thing with the new system as you can with the old and gain direct gl access without using any bullshit hackery or asm shit like everyone is bitching about.

However FORGE WILL NOT SUPPORT PEOPLE BREAKING GL INTERNALS. so unless a valid soltion can be devised that at the very least gracefully handels modders fuckups then forge will not be giving you iitemrender back. People have already hacked it back in, and people have already fucked it up. 

Its sad because when i first did the 1
8 update 9 months ago, i was open to potentially just adding iitemrendsr back in but i wanted to see how it was NEEDED. and weve yet to get anything.

The only legit thing from this thread sofar is text, which is just in newd of a helper class so every mod doesnt need to do it manually. Fry had a poc that was working ill need to bug him about it.

So again let me repeat, start with exact issues and well start addressing them. 
My Issue: (Short description)
My Code: (Link to the code JUST FOR RENDERING, i do not want a link to your 50,0000,0000 item mod -.-)
Images: (Screenshots or videos showing the effect you want)
Attempts: list what you have attempted to do, and the SPECIFIC areas its fallen short.

**Comment by LexManos** [comment] 2015-09-01 21:22
Seince there is no pleasing you children. A solution will be put in place that will cause me and end users hundreds of thousands of hours of headake and work but fine -.- ive yelled at fry to do it. If it isnt done in 12 hours go fucking harass him.

**Closed by LexManos** 2015-09-01 21:22 UTC
