### ISSUE TITLE
Child objects of ItemPotion not usable in custom brewing recipes

### ISSUE THREAD

**Issue by Agadar** [MinecraftForge/MinecraftForge#2502] opened 2016-02-26 20:09 UTC
Child objects of ItemPotion are not usable in custom brewing recipes because the check in TileEntityBrewingStand.brewPotions() doesn't check if the output are ItemPotions, but if the output are **ItemPotions or children of ItemPotions**. See the snippet from TileEntityBrewingStand.brewPotions() below:

`if (this.brewingItemStacks[i] != null && this.brewingItemStacks[i].getItem() instanceof ItemPotion)`

The consequence of not being able to use child objects of ItemPotion is that modders are forced to make almost exact copies of ItemPotion that inherit from Item instead, which is quite a dirty solution.

**Comment by LexManos** [comment] 2016-02-26 20:18
For vanilla yes, but it's all controlled through the BrewingRecipeRegistry which you can add your own IBrewingRecipe handlers and control the input/output precisely. We will need more information and code if you are having issues. Also, this exact line fo c ode was requested to switch to instance of ages ago.

**Comment by Agadar** [comment] 2016-02-26 22:22
I had a class ItemPotionArch that inherited from ItemPotion. Adding a brewing recipe was child's play thanks to BrewingRecipeRegistry. However, when using ItemPotion or a child thereof in a custom brewing recipe, TileEntityBrewingStand.brewPotions() alters the output because the predicate

`if (this.brewingItemStacks[i] != null && this.brewingItemStacks[i].getItem() instanceof ItemPotion)`

is satisfied. The altering of the output is done in the subsequent code of said predicate:

```
int j = this.brewingItemStacks[i].getMetadata();
                    int k = this.getPotionResult(j, itemstack);
                    List<PotionEffect> list = Items.potionitem.getEffects(j);
                    List<PotionEffect> list1 = Items.potionitem.getEffects(k);

                    if (j > 0 && list == list1 || list != null && (list.equals(list1) || list1 == null))
                    {
                        if (!ItemPotion.isSplash(j) && ItemPotion.isSplash(k))
                        {
                            this.brewingItemStacks[i].setItemDamage(k);
                        }
                    }
                    else if (j != k)
                    {
                        this.brewingItemStacks[i].setItemDamage(k);
                    }
```

As you can see, this piece of code messes around with the output's item damage value. While the potion effects of ItemStacks of ItemPotionArch are stored in NBTTagCompounds, the item damage is still used to indicate whether an ItemStack of ItemPotionArch is a splash potion or not. As such, the interference from the above piece of code can really mess things up.

This was relatively easily solved by making ItemPotionArch inherit from Item instead of ItemPotion and simply copying over ItemPotion's methods, but that feels like a work-around as opposed to a real solution, really.

**Comment by williewillus** [comment] 2016-02-26 22:33
I think this'l be resolved in 1.9, where these silly meta flippy bit things have been removed in favor of direct manipulation of the NBT, and splashpotions have been split into separate items (iirc)

**Comment by LexManos** [comment] 2016-02-27 09:17
Hey, try actually stepping through the code you'll see that code is never actually executed.
Note the 
            if (false) { // Code moved to net.minecraftforge.common.brewing.VanillaBrewingRecipe

**Comment by Agadar** [comment] 2016-02-27 14:08
Lex: you are correct. I overlooked that line. Still, somewhere in the code the item damage values are being fiddled with outside of my own fiddling. When my ItemPotionArch inherits from Item, everything works at it should, but when it inherits from ItemPotion, my brewing recipes seemingly start behaving strangely. For reference's sake, this is the custom BrewingRecipe child I use for ItemPotionArch recipes, which respects the item damage value of the input:

```
public class StrictBrewingRecipe extends BrewingRecipe
{
	public StrictBrewingRecipe(ItemStack input, ItemStack ingredient, ItemStack output)
	{
		super(input, ingredient, output);
	}
	
	@Override
	public boolean isInput(ItemStack stack)
    {
        return super.isInput(stack) && ((!this.input.hasTagCompound() && !stack.hasTagCompound()) ||
        		(this.input.hasTagCompound() && this.input.getTagCompound().equals(stack.getTagCompound())));
    }
}
```

All in all, considering I don't know the exact cause of the problem and I already worked around it by making ItemPotionArch inherit from Item instead of ItemPotion, this issue doesn't really seems worth pursuing at this time.

**Comment by ganymedes01** [comment] 2016-02-28 00:59
I believe the problem is that the VanillaBrewingRecipe instance is being checked before the recipe that you added, and because it checks for ItemPotion, it returns a valid result for your item, which causes your recipe to never even get looked at.

I'm not sure how this could be solved... The original vanilla code didn't check for ```instanceof ItemPotion```, it checked for ```== Items.itemPotion```. Reverting back to that would fix the problem in this situation, but might break compatibility with mods that take advantage of the patch. Although I'd argue that those mods should instead add their own recipes to keep things standardised.

**Comment by AEnterprise** [comment] 2016-02-28 12:56
maybe we could swap some things around so the VanillaBrewingRecipe is only called upon as last? this allows the custom ones to return there potions without breaking any existing implementations

**Comment by Agadar** [comment] 2016-03-02 11:18
AEnterprise, I haven't checked the code to verify whether Vanilla recipes are indeed called upon before mod recipes, but if that is the case, then swapping the order around would definitely make it more friendly to use.

**Comment by diesieben07** [comment] 2016-05-25 23:35
`VanillaBrewingRecipe` now explicitly checks for all the vanilla potion items and does not use `instanceof ItemPotion`.

**Comment by Actuarius** [comment] 2016-05-25 23:35
@diesieben07 added labels [Bug]

**Closed by Actuarius** 2016-05-25 23:35 UTC
Labels: Bug
