### ISSUE TITLE
FMLControlledNamespacedRegistry violates @Nonnull contract

### ISSUE THREAD

**Issue by tterrag1098** [MinecraftForge/MinecraftForge#3064] opened 2016-07-05 06:04 UTC
Most of the registries are constructed with null value for `defaultValue`. This key is presumed to be `@Nonnull` and is expected to be so in the accessor methods.

Problem code: https://github.com/MinecraftForge/MinecraftForge/blob/8c02a0a4cce0855c3b461fae40807fd58e2e15de/src/main/java/net/minecraftforge/fml/common/registry/GameData.java#L62-L68

Assumed `@Nonnull` Example:
```java
    @Nonnull
    public V getObject(@Nullable K name)
    {
        V v = super.getObject(name);
        return (V)(v == null ? this.defaultValue : v);
    }
```

In the above code it is obviously presumed that `defaultValue` is never null.

Forge/FML is violating this contract and creating dangerous behavior for anyone using null inspection in their IDE.

**Comment by AlexIIL** [comment] 2016-07-13 14:09
However if you use ````Item.REGISTRY````, ````Biome.REGISTRY````, ````Potion.REGISTRY````, ````SoundEvent.REGISTRY````, or ````Enchantment.REGISTRY```` directly then you don't run into this issue (as the type is already correct to return ````@Nullable````). To run into this you would have to either:

1. Cast the registry to either the forge registry type or the defaulted type.
2. Get the registry object through ````GameData.get<Type>Registry()```` (which is deprecated).

(Correct me if I'm wrong though, as I basically want to make sure that direct access is actually safe.)

Unfortunately I have found uses of both with a quick github code search, although I don't know if the use cases were using forge 1.9.x / 1.10.x.

So isn't this actually only an issue if you use direct casting, rather than an issue for everyone who uses null inspection?

**Comment by blay09** [comment] 2016-07-13 15:15
You got it the wrong way around @AlexIIL; Item.REGISTRY is still of type RegistryNamespaced which has a `@Nullable` contract that is violated by the underlying FMLControlledNamespacedRegistry.

You could cast or get the FMLControlledNamespacedRegistry directly via the internal GameData.get<Type>Registry to hide the `@Nullable` contract and do null-checks (but obviously that's not the desired solution).

To fix, either
- all registries in GameData need to get non-null default values assigned to match up with Vanilla criteria, 
- or the return type of xxx.REGISTRY needs to be changed to FMLControlledNamespacedRegistry, 
- or `@Nullable` needs to be added to RegistryNamespaced.getObject()

**Comment by AlexIIL** [comment] 2016-07-13 15:32
@blay09 But ````RegistryNamespaced```` looks like this:
````java
    @Nullable
    public V getObject(@Nullable K name)
    {
        return super.getObject(name);
    }
````
(Note that it already has an ````@Nullable```` -- are we looking at different versions of MC code, or was point 3 meant to say ````@Nonnull````?)

Its only ````RegistryNamespacedDefaultedByKey```` that has an @Nonnull annotation:
````java
    @Nonnull
    public V getObject(@Nullable K name)
    {
        V v = super.getObject(name);
        return (V)(v == null ? this.defaultValue : v);
    }
````
The issue is that all forge registries extend the ````RegistryNamespacedDefaultedByKey```` class, which forces all of them to have a ````@Nonnull```` annotation when only the block + potion type registries need it.

EDIT: @blay09 you deleted your comment, does that mean you want to rewrite it or we are both confused?

**Comment by blay09** [comment] 2016-07-13 15:33
Sorry, I was confused and deleted it when I realized. You are indeed correct.

**Comment by AlexIIL** [comment] 2016-07-13 15:37
Ok, thanks for clarifying :)

**Comment by LexManos** [comment] 2016-07-13 18:58
Modders should only ever access registries using the modder facing API that we have designed.
The vanilla API is to complex and doesn't do what is needed. Such as this null return. There is no way to have something like 'contains()' in the vanilla registries.
This breaks a lot of old things and makes out lives harder.

Anyways, modders should only ever access through our API and we've created a class specifically to hold the references to these registries that modders should use:
https://github.com/MinecraftForge/MinecraftForge/blob/1.10.x/src/main/java/net/minecraftforge/fml/common/registry/ForgeRegistries.java

**Closed by LexManos** 2016-07-13 18:58 UTC
