### ISSUE TITLE
HarvestDropsEvent not fired.

### ISSUE THREAD

**Issue by Darkhax** [MinecraftForge/MinecraftForge#6242] opened 2019-10-16 02:11 UTC
**Minecraft Version:** 1.14.4

**Forge Version:** 28.1.56

**Logs:** N/A

**Steps to Reproduce:**
 1. Add a listener to the HarvestDropsEvent
 2. Run the game
 3. Listener is never fired

**Description of issue:**
It seems that with the 1.13/1.14 rewrite the HarvestDrops event was never patched back in. Following the call hierarchy back shows `ForgeEventFactory#fireBlockHarvesting` is never called. 

Hopefully this is an oversight and not intentional, as there are still many use cases for this event where something like loot tables is not suitable. For example, I am currently making a mod with a "Misfortune" curse enchantment which gives blocks a chance not to drop anything, and a Midas curse enchantment that has a chance to replace drops with gold nuggets.

**Comment by Tfarcenim** [comment] 2019-10-16 02:17
duplicate of https://github.com/MinecraftForge/MinecraftForge/issues/5828

**Comment by Unnoen** [comment] 2019-10-16 02:23
Closing as duplicate (https://github.com/MinecraftForge/MinecraftForge/issues/5828), however I can confirm this is still an issue.

**Closed as completed by Unnoen** 2019-10-16 02:23 UTC
