### ISSUE TITLE
[1.18.1] Players unable to join LAN server.

### ISSUE THREAD

**Issue by dragon3025** [MinecraftForge/MinecraftForge#8377] opened 2022-01-09 20:42 UTC
**Minecraft Version:** {1.18.1}

**Forge Version:** {1.18.1-forge-39.0.14}

**Logs:** {[latest.log](https://github.com/MinecraftForge/MinecraftForge/files/7835883/latest.log)}

Player unable to join LAN server, it could be when certain mods are installed. So far I know that people are having trouble with "Create" and "Crafting Automat". I saw some had the problem fixed by making sure both connections were private, but that didn't work for me.
Some links to people having issues:

- https://forums.minecraftforge.net/topic/104087-cant-play-on-lan-with-my-friend-in-minecraft-forge/
- https://www.reddit.com/r/CreateMod/comments/rxph6h/1181_create_4_cannot_join_lan_worlds/
- https://github.com/Lolcroc/CraftingAutomat/issues/17
- https://www.reddit.com/r/Minecraft/comments/r6zlo6/issues_with_118_lan_connect_java/

**Comment by TheCurle** [comment] 2022-01-09 21:15
I can confirm that Forge-Forge LAN connections work fine, but Create-Create LAN connections do not.
I can only assume that Create is doing something strange with synchronization packets, but we are unable to do anything regarding that. 

I suggest you report this to the Create authors. 

Until any actionable information is found, i'm closing this issue as not-us.

**Comment by Thutmose** [comment] 2022-01-19 16:17
Is this bug not what is fixed here? https://github.com/MinecraftForge/MinecraftForge/pull/8181

Edit: Maybe not, the problem with lan server seems to be something with the reference counts in the packets, though that could be a result of packet read orders as mentioned here?

**Comment by sciwhiz12** [comment] 2022-01-19 16:24
Looking at the issue's log, this is the issue that is to be fixed by #8181. (I can confirm, as I helped debug the issue publicly and internally.) Thank you @Thutmose for bringing this to our attention.

**Comment by vl2anh1** [comment] 2022-01-20 03:07
> Looking at the issue's log, this is the issue that is to be fixed by #8181. (I can confirm, as I helped debug the issue publicly and internally.) Thank you @Thutmose for bringing this to our attention.

im just play with my friend yesterday(19 jan 2022) in version 1.18.1 - 39.0.44 and still got that bug... so this bug can fix by our hand or it already fixed in the forge update ? (:v sorry but i have read #8181 but cant understand what you guys talking about..)

**Comment by sciwhiz12** [comment] 2022-01-20 04:19
@vl2anh1: The issue has not yet been fixed, and players cannot fix it themselves; it must either be patched in Forge (by PR #8181 or another such PR) or worked around by modders (by manually sending a new instance of the vanilla packet to each player, bypassing `PacketDistributor` or other similar means which reuse a single packet instance). Please be patient as we work towards fixing this issue, thank you.

**Closed as completed** 2022-01-28 03:33 UTC
Labels: Regression, Confirmed, 1.18
