### ISSUE TITLE
Loading an existing world with forge triggers two data reloads instead of one

### ISSUE THREAD

**Issue by Shadows-of-Fire** [MinecraftForge/MinecraftForge#8125] opened 2021-09-27 20:05 UTC
**Minecraft Version:** 1.16.5

**Forge Version:** 36.2.5

**Logs:** https://gist.github.com/Shadows-of-Fire/87b74bcecca041ee3a7e6c060dae7062
[World Creation on Forge](https://gist.github.com/Shadows-of-Fire/87b74bcecca041ee3a7e6c060dae7062#file-forge-debug-log-L332)
[World _Load_ on Forge (two reloads)](https://gist.github.com/Shadows-of-Fire/87b74bcecca041ee3a7e6c060dae7062#file-forge-debug-log-L332)
[World Creation on Vanilla](https://gist.github.com/Shadows-of-Fire/87b74bcecca041ee3a7e6c060dae7062#file-forge-debug-log-L332)
[World _Load_ on Vanilla (one reload)](https://gist.github.com/Shadows-of-Fire/87b74bcecca041ee3a7e6c060dae7062#file-forge-debug-log-L332)

**Steps to Reproduce:**
 1. Create a new instance with just forge
 2. Make a world
 3. Exit said world
 4. Load into said already existing world
 5. Observe that two data reloads happen.
 6. Repeat on vanilla, observing that only a single reload happens in step (5)

**Description of issue:**
Something forge is doing causes data resource to be reloaded twice instead of once when loading into an already generated world in singleplayer (does not happen when making the world for the first time).  I cannot determine why or how this is happening, but it is a clear deviation from vanilla and it drastically increases startup time in larger packs.

**Comment by LexManos** [comment] 2021-09-27 20:30
Working as intended, unfortunately due to how dynamic registries and data packs are loaded. You have to load them for the registry injections to work, and then reload them after we've corrected all the ID mappings.
It's not a great solution, feel free to try and find a better one. But it goes into completable future hell and Mojang's 1/2 static state system.
And 'drastically' is a bit of an overstatement. This extra pass in my test with 150 mods loaded adds a whole 3% to the loading time. Note: This is the data pack loading, not the resource packs, which is where the main costs are.

Edit: We don't have a "Works as Intended but if you find a better solution we're all ears", so ignore the "Wont Fix" part of the label.

**Comment by Shadows-of-Fire** [comment] 2021-09-27 20:35
Is it required to load the entire datapack system or only a part of it?
This looks to be where it is doing it <https://github.com/MinecraftForge/MinecraftForge/blob/166feefc023c7e153072a18e6b49982d7246fb0a/patches/minecraft/net/minecraft/client/Minecraft.java.patch#L338-L340>
But I can't really see why it needs to run this method twice.
I can't even see how this ties into the registry injection system at all really

**Comment by NillerMedDild** [comment] 2021-09-28 17:46
In modpacks that use datapacks extensively for customization, such as Enigmatica 6, the additional load time is very high sadly :/

**Comment by LexManos** [comment] 2021-09-28 18:03
Its needed so that ids can be persisted across saves, as explained in the commit. The dynamic registries copy their data from the built in seed registries. Its a convoluted mess which is why this seemed the sanest way to solve the issue. If you wish to look into it more, feel free.

**Comment by NillerMedDild** [comment] 2021-09-28 18:06
Duely noted, comment deleted. I'll delete this one in a bit too to keep the issue to the point.

**Comment by alcatrazEscapee** [comment] 2021-09-28 23:47
Worth mentioning that addition was the fix for #7586, so any other solution should keep that in mind (as it was thought to be fixed multiple times before this, as quoted "which isn't good.. but hey" solution.)

Also worth mentioning that to my knowledge this affects 1.17 as well.

Also *also* possibly worth mentioning, that mojang have (currently, as of 1.18 snapshots) palleted their biome container, meaning the only root cause of #7586, and so this could possibly be dropped by then. And just operate with the assumption that the only registry which is both dynamic and a forge registry (biomes), won't have isomorphic int IDs between worlds.

**Comment by alcatrazEscapee** [comment] 2021-10-19 12:43
@Shadows-of-Fire 
> But I can't really see why it needs to run this method twice.
> I can't even see how this ties into the registry injection system at all really

Allow me to explain how this actually works. First, we need to look at `RegistryAccess.builtin()`. In vanilla, this method

- Creates a new `RegistryAccess` instance.
- Then, iterates through all registries in the `RegistryAccess#BUILTIN` field and populates `RegistryReadOps.ResourceAccess.MemoryMap` with the contents of the registry, in encoded (JSON, in memory) form.
- `RegistryAccess#BUILTIN` is a field which, upon initialization, is essentially the same thing - it is a static copy of the registries at the time that `RegistryAccess` was classloaded.

This last bit is a bit problematic for mods. Because classloading of `RegistryAccess` before other mods can cause the `BUILTIN` field to be initialized, and as a result, no further registrations of any world generation registry type will appear in that field. So, Forge patches that, to instead of referring to the field, always refer to the current state of the `BuiltinRegistries`, which, among others, means it refers to `ForgeRegistries.BIOMES`.

So, calling `RegistryAccess.builtin()` copies the entire contents of `ForgeRegistries.BIOMES`, including the same int ID mappings.

Now, looking at this patch in particular:

- When `creating` is `false`, this has been called from `Minecraft.loadLevel`. Which, among other things, passes in the `Function4<...>` as `Minecraft::loadWorldData`.
- We then first call `makeServerStem`, passing in this quad function, and the `RegistryAccess` instance provided to `doLoadLevel`, which was initialized as `RegistryAcces.builtin` (An entire copy of the registries has been performed here).
- `makeServerStem` calls `ServerResources.loadResources`. This is what reads all resource files from JSON, and imports them into the `RegistryAccess` instance.
- It then blocks for this `ServerResources` to become available, and passes the `ResourceManager` (obtained from the `ServerResources`) into the `Minecraft::loadWorldData`
- Which then calls into `LevelStorageSource.getDataTag`...
- Which indirectly calls into `LevelStorageSource.getReader`
- And at the end there, there's a Forge hook for `WorldPersistenceHooks.handleWorldDataLoad`

At that point, we are in a bit of Forge code that runs some stuff, and frankly I have no idea what it's doing. ([Seriously, why are there comments about special cases in Minecraft 1.8 servers in this code still... with a //todo no less](https://github.com/MinecraftForge/MinecraftForge/blob/11bdf592c8ca08b871bbc441a6e79979107cca6d/src/main/java/net/minecraftforge/registries/GameData.java#L685-L690)). But what this *does* do, is modify the existing biome registry to have IDs loaded from the world. So, `ForgeRegistries.BIOMES` is mutated.

- Continuing on, in the case where we load a world, we now discard *everything*, including the results of that useless resource reload. However, the `RegistryAccess` that had been populated is now using old IDs, because it was created (in `RegistryAccess.builtin`, remember), before the Forge registry was remapped.
- So, we do the whole thing again, creating a new `RegistryAccess.builtin()`, and passing it through the resource reload chain (which incedentally, runs Forge's world persistence hooks **twice**.

---

So, can this be done better? I think so. `WorldPersistenceHooks` is to my understanding, a pluggable system for adding generic hooks to reading of `level.dat`... which I'd be surprised to see anyone uses. Somewhat problematically, the signature of `WorldPersistenceHook` means is starts to require additional data in a long call chain, which eventually has some dependencies on running the resource reload. Could this be done without totally rewriting `WorldPersistenceHooks` in a fairly breaking manner?... Maybe.

**Comment by alcatrazEscapee** [comment] 2021-10-19 18:24
Some additional context on @LexManos's remark about performance.

> And 'drastically' is a bit of an overstatement. This extra pass in my test with 150 mods loaded adds a whole 3% to the loading time. Note: This is the data pack loading, not the resource packs, which is where the main costs are.

This **depends on the mods**, clearly. For example, this is one (1) mod I have which includes a large world generation datapack, as well as other non-world generation recipes and data.

Creating a new world (selected log lines):
```
[14:07:13] [Render thread/INFO]: Reloading ResourceManager: Default, , resources, cyanide-1.0.0-1.17.1_mapped_parchment_mappificator.v16-1.17.1.jar, jei-1.17.1-8.1.0.26_mapped_parchment_mappificator.v16-1.17.1.jar
[14:07:46] [Server thread/INFO]: Starting integrated minecraft server version 1.17.1
[14:07:48] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[14:08:01] [Render thread/INFO]: Time elapsed: 12708 ms

Resource reloading: 33s
Generating the world: 13s (for comparison sake)
Time taken from "click create world" to in game? 46s
```

Loading an existing world:
```
[14:11:21] [Render thread/INFO]: Reloading ResourceManager: Default, , resources, cyanide-1.0.0-1.17.1_mapped_parchment_mappificator.v16-1.17.1.jar, jei-1.17.1-8.1.0
[14:11:50] [Render thread/INFO]: Reloading ResourceManager: Default, , resources, cyanide-1.0.0-1.17.1_mapped_parchment_mappificator.v16-1.17.1.jar, jei-1.17.1-8.1.0.26_mapped_parchment_mappificator.v16-1.17.1.jar
[14:12:22] [Server thread/INFO]: Starting integrated minecraft server version 1.17.1
[14:12:22] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[14:12:25] [Render thread/INFO]: Time elapsed: 2723 ms

First resource reload: 29s
Second resource reload: 32s
Loading world: 3s
Time taken from "click load world" to in game? 64s
```

Resource loading is **a lot slower than generating the world**, and having this additional resource reload **doubles** the time to get in world, adding an additional 30 seconds. Oh, and mind, this is with a mod which removes the experimental warning screen in a fashion that avoids doing the entire reload, an additional time. So with Forge and *not* this mod, there's an additional ~30s.

Full log of the above run:
[latest.log](https://github.com/MinecraftForge/MinecraftForge/files/7375789/latest.log)

The mod in question includes:
- 7,498 JSON `data` files, not including world gen.
- 1,024 JSON `data/worldgen` files.
And I've done some primitive checks to show that the time taken by these is in roughly equal proportion, despite the difference in file count.

**Closed as completed** 2022-01-12 02:00 UTC
Labels: Wont Fix/Works As Intended, 1.16
