### ISSUE TITLE
Biome ID's not persisting Forge 35.1.13 -> 35.1.29

### ISSUE THREAD

**Issue by Letoric** [MinecraftForge/MinecraftForge#7586] opened 2021-01-05 15:54 UTC
This is reproducible by downloading All the Mods 6 version 1.3.7, rolling a couple worlds until you see BYG biomes, and taking note of what they are, then upgrading to All the Mods 6 version 1.3.8 or 1.3.9. You will see that the biomes change to a different biome. There was no BYG update between the versions, but there was a biome blacklist update.

**Minecraft Version:** {Minecraft version}
1.16.4
**Forge Version:** {Forge version. *Version number, not latest/rb*}
35.1.13 / 35.1.29

**Comment by LexManos** [comment] 2021-01-05 19:19
Yes, this is how Biomes work now. We do not control the dynamic registry that's in the worlds at runtime. We just persist and manage the 'default' registry that gets seeded into new worlds.
There is a reason why there is a giant warning about removing data potentially corrupting your worlds with the new biome stuff.
If you make a biome mod, You need to make sure you keep things additive, or at the very least make dummies for things you remove.

And for the love of god, don't send your minions to directly ping me about this stuff there are other people on the team -.-

**Comment by TelepathicGrunt** [comment] 2021-01-25 15:29
`You need to make sure you keep things additive`
The issue is occurring even when people are adding new biome mods. Any change in the modlist regarding biome mods is enough to trigger the bug apparently. It's what I have been seeing and what people have been reporting while I am trying to help them out.

**Comment by LexManos** [comment] 2021-01-25 18:16
Provide a slim test mod set or quit complaining -.-
As stated my tests show that additive systems work fine.
That's the entire point of this commit: https://github.com/MinecraftForge/MinecraftForge/commit/7d00d015f3b6000c68f7e5fa1fda9777042d4114

**Comment by alcatrazEscapee** [comment] 2021-01-25 19:43
Provide a test mod you say? Gladly. It's a fairly simple reproduction case:

1) Load world with test mod, explore (use `/locatebiome` to find various locations of biomes `second`, `third`, `fourth` etc, observe in F3)
2) Mark these locations
3) Close world + game. Modify the test mod, add a `first` biome (Notably, this issue does not persist if you add `first` at the end of your registrations. This is to be expected, and if this is the point to be conceded, so be it. However, this would:
    - require mods to only add biomes at the end of existing registrations, and,
    - still break as soon as there's more than one mod in play (now you cannot control "only add new biomes at the end of the id space").
4) Load world + game again. Observe that the biomes in these locations has changed. In addition `/locatebiome` will be near useless and contradictory to what's appearing in F3. (Although this is to be expected if the biome generation has changed at all, which it has). I also use the following "log when hit" breakpoint in `PlayerEntity#tick()` to demonstrate that the biome is not just incorrect on F3, but also in dedicated server side code

```java
"Biome: " + player.world.func_241828_r().getRegistry(Registry.BIOME_KEY).getKey(player.world.getBiome(player.position))
```

This can be reproduced with addition of new biomes, and with removal. (Prior to https://github.com/MinecraftForge/MinecraftForge/commit/7d00d015f3b6000c68f7e5fa1fda9777042d4114 it was also reproducible by changing the biome registration order however that actually was fixed by this. Hurray! it did solve part of the issue, e.g. phase 1 you might say.)

[Test Mod](https://github.com/alcatrazEscapee/MinecraftForge/commit/7b2a7247f59e30932bd5ecfa39fdcca11fbb0d0c)

**Comment by LexManos** [comment] 2021-01-26 02:16
Thank you Alcatraz for actually being a constructive part of this conversation.
With your test mod I was able to reproduce what you've been experiencing.
This comes down to a order of operations thing, due to the really annoying system we use to inject in combination to the way vanilla loads local worlds.
To clarify my tests passed because I was testing the registries themselves, between dedicated server and client. Unfortunately, that didn't catch the case where the local client disagreed with the local server because.. why the hell would it ever do that.. but yay Minecraft -.-

**Closed as completed** 2021-01-26 02:24 UTC
