### ISSUE TITLE
[1.13.2] Crash in RuntimeDistCleaner

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/MinecraftForge#5585] opened 2019-03-01 21:38 UTC
Forge Version: 25.0.64, (First time seen in 25.0.13)
Classed & log: https://gist.github.com/mcenderdragon/30d84eb04bbe8224754e44f30dc2992a

Crash:
```
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to [Ljava.lang.String;
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.lambda$remove$1(RuntimeDistCleaner.java:122)
	at java.util.stream.MatchOps$1MatchSink.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.anyMatch(Unknown Source)
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.remove(RuntimeDistCleaner.java:122)
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClass(RuntimeDistCleaner.java:74)
```

**Comment by cpw** [comment] 2019-03-02 16:21
The problem is in the ItemRam class somehow. I can't find that on your public git repos.

**Comment by SamboyCoding** [comment] 2019-03-02 16:57
Cpw the class is in the gist

**Comment by mcenderdragon** [comment] 2019-03-02 17:22
After moving `FPMain.tab_items` to an independet class it works so somehwere in FPMain is the error.

**Comment by cpw** [comment] 2019-03-02 17:58
Can you share FPMain please?

**Comment by mcenderdragon** [comment] 2019-03-02 18:43
Here: https://gist.github.com/mcenderdragon/4962ae6da70bc430001f4a19f1f522ea#file-fpmain_recompiled-java.
I added the java base file and the recompiled version (so that what eclipse creates as output)

**Comment by cpw** [comment] 2019-03-02 20:47
Closing this issue. @OnlyIn does not have a method "proxy" and that is why it is crashing. You should not be using OnlyIn in your code, you should not be using "ignore errors" (though it is understandable).

**Closed as completed by cpw** 2019-03-02 20:47 UTC

**Comment by mcenderdragon** [comment] 2019-03-02 21:26
Is it possible to throw an error containing the class name for the future? This one was not good understandable.

**Comment by Niko-sk2x** [comment] 2019-03-03 02:21
I think that while it's not impossible to add it for this one case, there is no real way to guarantee that a sensible error is shown in all cases eclipse compiler produces an invalid class. At one point I had eclipse compiler generate a class that didn't pass the verifier, and also one that that ASM itself would not be able to process, and no decompiler was able to decompile it (and guess how I know about it...)

If you really want to run even with compile errors, you will probably just have to debug the issues that happen as a result on your own.
