### ISSUE TITLE
Armor does not respect Attribute modifiers

### ISSUE THREAD

**Issue by CoderAtParadise** [MinecraftForge/MinecraftForge#3629] opened 2017-01-14 01:43 UTC
[Initial Report](http://www.minecraftforge.net/forum/index.php?topic=44666.0)
The ISpecialArmor changes does not respect armor attribute modifiers

**Comment by mezz** [comment] 2017-01-14 02:24
Is this a duplicate of https://github.com/MinecraftForge/MinecraftForge/issues/3095 ?

**Comment by CoderAtParadise** [comment] 2017-01-14 02:52
It is and is still present it seems

**Comment by mezz** [comment] 2017-01-14 02:53
Ok, thanks.

**Closed as completed by mezz** 2017-01-14 02:53 UTC
Labels: Bug
