### ISSUE TITLE
[1.7.10] Persistent mobs seem to duplicate

### ISSUE THREAD

**Issue by Azanor** [MinecraftForge/MinecraftForge#1642] opened 2015-01-16 06:18 UTC
I'm not 100% sure if this is forge or vanilla related, but here goes.
Persistent mobs (animals, name-tagged mobs or mobs with canDespawn() set to false) seem to occasionally duplicate under certain, mysterious circumstances. 
It was originally noticed and reported in regards to my golems (see https://github.com/Azanor/thaumcraft/issues/1501), but it seems to happen with nametagged mobs and some animals as well.
Has anyone else experienced this?

**Comment by bloodmc** [comment] 2015-01-16 07:04
@Azanor I had a similar issue with MoCreatures after updating to 1.7 and ended up having to override the setDead method with the following 

```java
    @Override
    public void setDead() {
        // Server check required to prevent tamed entities from being duplicated on client-side
        if (MoCreatures.isServer() && getIsTamed() && getHealth() > 0 {
            return;
        }
        super.setDead();
    }
````

**Comment by Azanor** [comment] 2015-01-16 07:17
So the duplication was clientside only? The ones reported to me seemed to be both client and serverside.

**Comment by bloodmc** [comment] 2015-01-16 07:21
@Azanor Yes, I believe so but we fixed it ages ago so I figured I would provide it just in case =) I made a comment on your issue so hopefully we get a bit more details on the mods/server software they are using.

**Comment by LexManos** [comment] 2015-01-16 23:04
It sounds like this would be a client side only ghosting.
Kinda curious what causes it tho. If you have a way to reproduce that'd be awesome..
Kinda curious why that 'fix' fixes it.. that would basically just make the entity stay alive on the server. Potentially when it's 'dead' from being away from the player for too.
Need more information :/

**Comment by Terpo** [comment] 2015-01-17 13:29
The thaumcraft golem duplication does not happen client side only. You can use the golem bell to deconstruct them and get the items and they work just like the original ones.

**Comment by LexManos** [comment] 2016-05-29 01:44
Closing due to never being able to duplicate or document.

**Closed by LexManos** 2016-05-29 01:44 UTC
Labels: Bug
