### ISSUE TITLE
Crash on fresh install of 1.15.2 with no mods on Java 13

### ISSUE THREAD

**Issue by za3k** [MinecraftForge/MinecraftForge#6576] opened 2020-03-19 01:48 UTC
**Minecraft Version:** 1.15.2
**Forge Version:** 21.1.25
**OS:** Linux Debian 10
**Crashlog:** [crashlog](https://gist.github.com/za3k/0f36aaec5e670432c6da0e3ea40f197a)

OpenJDK 8: Fine
OpenJDK 11: Fine
Oracle Java 13: Crash (`[Render thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Failed to resolve handler for "net.minecraftforge.fml.network.simple.SimpleChannel$$Lambda$2192/0x00000008013a8c40@75b3ef1a"`)

**Steps to Reproduce:**
 1. Install a fresh (client) copy of forge. In my case everything my 'mods' folder is "XXX.jar.DISABLED" (confirmed by watching boot process) and I deleted 'versions' and 'config' content.
 2. Press play
 3. At the end of the forge progress process, I get a crash with the version above.
 4. (Note) Vanilla Minecraft 1.15.2 runs fine with the crash versions

Fixes could be:
- Write an installation guide and put it in "documentation" on the site. Mention requirements in the installation guide.
- Display a clearer error message (at run time covers more cases than install time).
- Make it work (idk if that's worthwhile)

**Comment by diesieben07** [comment] 2020-03-19 13:54
This is caused by the fact that [the TypeTools library](https://github.com/jhalterman/typetools) does not work on Java 13 yet due to enhanced security checks on reflection into JDK internals.
I'm looking into making a pull request to them to make it work.

**Comment by diesieben07** [comment] 2020-03-19 16:49
Turns out they already have a PR open for that:
https://github.com/jhalterman/typetools/pull/66

Once that is pulled, Forge can update.

**Comment by skiprocks999** [comment] 2020-03-22 17:35
Hello,
Is there any progress on the fix?

**Comment by DaemonUmbra** [comment] 2020-03-22 19:08
> Hello,
> Is there any progress on the fix?

Have you read the conversation or have you only read the issue name?

**Comment by skiprocks999** [comment] 2020-03-22 20:25
I read the conversation I just was wondering if there's been any progress

**Comment by DaemonUmbra** [comment] 2020-03-22 20:27
Do you see any in either place?

**Comment by pluto00987** [comment] 2020-04-06 23:17
I can confirm the same crash using Java 14 as well (not unexpectedly).

**Comment by ichttt** [comment] 2020-05-14 21:48
Hopefully fixed in https://github.com/MinecraftForge/MinecraftForge/commit/1a317a7306a0ff2283a59b57ef3e1b8262301c1c

**Closed as completed by ichttt** 2020-05-14 21:48 UTC
Labels: Blocked Upstream
