### ISSUE TITLE
Client-side-only events fired on Dist.DEDICATED_SERVER if addListener() used unconditionally

### ISSUE THREAD

**Issue by PaintNinja** [MinecraftForge/MinecraftForge#8577] opened 2022-04-21 12:47 UTC
**Minecraft Version:** 1.18.2

**Forge Version:** 40.1.0

I can confirm that this also applies to 1.16.5-36.2.34 and 1.17.1-37.1.1.

**Description of issue and to reproduce:**

When mods add event listeners to the event bus, those events are always fired regardless of sidedness. This leads to crashes as client-side-only events are fired on dedicated servers due to mod devs reasonably assuming that client events are only fired on clients and thus load client-side classes within these events.

```java
public static final Logger LOGGER = LogManager.getLogger();
public ExampleMod() {
    FMLJavaModLoadingContext.get().getModEventBus().addListener(this::clientSetup);
}
private void clientSetup(final FMLClientSetupEvent event) {
    LOGGER.info("FMLClientSetupEvent fired"); // fires on Dist.DEDICATED_SERVER
}
```

To workaround this issue, devs need to wrap the addListener call in a dist check like so:
```java
if (FMLEnvironment.dist == Dist.CLIENT)
    FMLJavaModLoadingContext.get().getModEventBus().addListener(this::clientSetup);
```
or use the `@Mod.EventBusSubscriber` with the appropriate dist value.

**Possible solution:**
Add a runtime `FMLEnvironment.dist` check to `addListener()` for sided events so that devs don't need to explicitly do so themselves.

Fixing this issue would fix a bunch of mods that crash when loaded on the wrong side and slightly reduce the amount of code needed to properly register event listeners this way.

**Comment by sciwhiz12** [comment] 2022-04-21 13:07
I cannot see in what possible way this issue -- the wrong setup event being fired on the wrong physical side/distribution -- can occur. Both events are referenced only (excluding imports and javadocs) in one place: 

https://github.com/MinecraftForge/MinecraftForge/blob/8ade7bbaebdaa263b0391fd165d5e4e033b52c60/src/fmlcommon/java/net/minecraftforge/fml/core/ModStateProvider.java#L37

As one can see, this uses `DistExecutor` to select the setup event used based on the current physical side (accessed through `FMLEnvironment.dist`). This means that it should be **impossible** that the wrong event for a physical side is fired, as the definition of the mod state responsible for firing the event prevents such an occurence.

For now, I will be closing this issue as an impossibility according to code investigation. Please provide logs and/or an example reproducible setup if this issue is verifiably correct.

(As a side-note, the proposed potential solution cannot be done because `addListener` is part of the EventBus project, which does not depend on FML and therefore cannot access `FMLEnvironment.dist`.)

**Closed as completed by sciwhiz12** 2022-04-21 13:07 UTC
Labels: Bug
