### ISSUE TITLE
forge:reach_distance and forge:attack_range seem to go away when swapped between hands if attribute is applied to both hands.

### ISSUE THREAD

**Issue by bconlon1** [MinecraftForge/MinecraftForge#8637] opened 2022-05-28 22:26 UTC
**Minecraft Version:** 1.18.2

**Forge Version:** 40.1.25

**Logs:** N/A.

**Steps to Reproduce:**
(This was performed in a Forge-only environment with no mods).
1. Spawn an item with the attributes;
- `forge:reach_distance`: `/give @p diamond_sword{AttributeModifiers:[{AttributeName:"forge:reach_distance",Amount:5,Slot:mainhand,Name:"test",UUID:[I;-122124,24674,3193,-49348]},{AttributeName:"forge:reach_distance",Amount:5,Slot:offhand,Name:"test",UUID:[I;-122124,24674,3193,-49348]}]} 1`
- `forge:attack_range`: `/give @p diamond_sword{AttributeModifiers:[{AttributeName:"forge:attack_range",Amount:5,Slot:mainhand,Name:"test",UUID:[I;-122124,24674,3193,-49348]},{AttributeName:"forge:attack_range",Amount:5,Slot:offhand,Name:"test",UUID:[I;-122124,24674,3193,-49348]}]} 1`
2. Put the item in the player's mainhand.
3. Switch the item to the offhand with the hotkey for switching hands.
4. Switch the item again back to the mainhand with the hotkey.
5. The item loses the attribute, observable from the player no longer having the same extended reach distance and having the default reach distance instead. The item gets the attribute back if its deselected and selected again in some other way.

**Description of issue:**
Switching an item that has the `forge:reach_distance` or the `forge:attack_range` modifier on both hand slots between hands seems to get rid of the attribute temporarily. This doesn't seem to be an issue though when the modifier is just on the main hand. I am unsure if this applies to any other attributes, these reach attributes were the only two I ran into issues with during modded implementation of them.

**Comment by sciwhiz12** [comment] 2022-05-29 00:36
Using the items provided from the commands unmodified reproduces the observed error. However, changing the UUIDs of the offhand and mainhand attribute modifiers to be different from each other restores the expected behavior -- the attribute's effect remains in place

<details>
<summary>Commands for summoning the items with modified UUIDs</summary>

- `/give @p diamond_sword{AttributeModifiers:[{AttributeName:"forge:reach_distance",Amount:5,Slot:mainhand,Name:"test",UUID:[I;-1,2,3,-4]},{AttributeName:"forge:reach_distance",Amount:5,Slot:offhand,Name:"test",UUID:[I;1,-2,-3,4]}]} 1`
- `/give @p diamond_sword{AttributeModifiers:[{AttributeName:"forge:attack_range",Amount:5,Slot:mainhand,Name:"test",UUID:[I;-4,3,2,-1]},{AttributeName:"forge:attack_range",Amount:5,Slot:offhand,Name:"test",UUID:[I;4,-3,-2,1]}]} 1`

</details>

As the name implies, the UUID or Universally Unique ID of an attribute modifier must be unique and consistent. (This is often done by generating a UUID from online, and storing it as a constant.) The items given had attribute modifiers which break that expectation -- having the same UUID for both attribute modifiers -- leading to the unexpected behaviors shown.

The solution is to change the attribute modifiers' UUIDs to be different from each other. As the issue is caused by user error, I am closing the issue as working as intended.

**Closed as not planned by sciwhiz12** 2022-05-29 00:36 UTC
Labels: Bug, Wont Fix/Works As Intended, 1.18
