### ISSUE TITLE
[1.19] The world generator in minecraft:overworld and other dimensions from mods breaks after loading mod with custom worldgen datapack.

### ISSUE THREAD

**Issue by KedisPL** [MinecraftForge/MinecraftForge#8714] opened 2022-06-10 12:18 UTC
**Minecraft Version:** 1.19

**Forge Version:** 41.0.22
**Logs:** None, as there are no errors in the logs.

**Steps to Reproduce:**
1. Enter the world with a mod with a new dimension.
2 The worlds generator is breaking.

**Description of issue:**
The world generator in minecraft:overworld and other dimensions from mods breaks after loading mod with custom worldgen datapack. I will point out that my mod does not change the dimension generator of minecraft:overworld
![2022-06-10_13 57 36](https://user-images.githubusercontent.com/79972336/173062555-bde0b7b9-97cc-4065-882e-c3280fa25cf5.png)
![2022-06-10_14 06 18](https://user-images.githubusercontent.com/79972336/173062577-72b7ee2a-098e-459c-b97c-901d748309bb.png)

**Comment by GirafiStudios** [comment] 2022-06-10 12:20
Pretty sure it´s the same, as what have already been reported here https://github.com/MinecraftForge/MinecraftForge/issues/8676
 :)

**Comment by sciwhiz12** [comment] 2022-06-13 11:20
Please provide a minimal reproducible example (mod + datapack) that accurately reproduces the issue, as well as descriptions (written or screenshot) of the resulting unexpected behavior. Additionally, please look at the issue linked by GirafiStudios, as that may be the root cause of this issue.

**Comment by KedisPL** [comment] 2022-06-13 12:25
This happens with every mod/datapack which adds a new dimension. 
Example mod:
[mod jar is in this zip.zip](https://github.com/MinecraftForge/MinecraftForge/files/8890950/mod.jar.is.in.this.zip.zip)
Example datapack in this comment:
https://github.com/MinecraftForge/MinecraftForge/issues/8713#issuecomment-1152347183
Screenshots:
![2022-06-13_14 21 24](https://user-images.githubusercontent.com/79972336/173351438-5c9abdac-0f9c-41f9-96b3-fd09a4652139.png)
![2022-06-13_14 22 44](https://user-images.githubusercontent.com/79972336/173351469-13c96715-da4a-4004-950b-215987c12d08.png)
![2022-06-13_14 29 13](https://user-images.githubusercontent.com/79972336/173352453-46fcfa69-e082-4389-a332-10c9c986ca2d.png)

**Comment by sciwhiz12** [comment] 2022-06-16 15:29
I cannot load the given mod in a Forge 1.19 client, and I can find no anomalies in a world using 1.19-41.0.22 and the linked datapack. 

Given @GirafiStudios's suggestion that this is a duplicate of #8676, which has been solved as of 1.19-41.0.21 through #8693, I am closing this issue as fixed.

If you believe that the issue still exists, please re-open the issue with a comment to a proper, working, minimal (as small as reasonably possible, not a full mod) reproducible example of the issue in action, including the Forge version, coordinates, world seed, and other relevant information.

**Closed as completed by sciwhiz12** 2022-06-16 15:29 UTC
Labels: Bug, Needs Update, 1.19
