### ISSUE TITLE
Client update forge2703 Unable to enter the server

### ISSUE THREAD

**Issue by Anguriaboy** [MinecraftForge/MinecraftForge#4954] opened 2018-05-27 01:57 UTC
Issue Description
Client update Forge-14.23.4.2703 Unable to enter the server。
![default](https://user-images.githubusercontent.com/39192846/40581819-5d5a6f9e-6194-11e8-83cb-5a1ef8ce1a41.jpg)

**Comment by 3TUSK** [comment] 2018-05-27 02:17
See #4942

**Comment by liach** [comment] 2018-05-27 03:05
已经解决，请关闭此问题 （按白色的`close issue`按钮）

**Comment by Anguriaboy** [comment] 2018-05-27 04:05
@liach 关键是还有这问题呀0.0

**Comment by 3TUSK** [comment] 2018-05-27 04:24
@Anguriaboy 请将 Forge 更新到 1.12.2-14.23.4.2705。

For anyone else who is also experiencing this issue: Update Forge to 14.23.4.2705 which should solve the problem!

Also this issue is in fact duplicate of #4923.

**Comment by LexManos** [comment] 2018-05-27 05:48
English only people.

**Closed as completed by LexManos** 2018-05-27 05:48 UTC
