### ISSUE TITLE
[1.7.10ls] Random missing textures?

### ISSUE THREAD

**Issue by ganymedes01** [MinecraftForge/MinecraftForge#1829] opened 2015-04-25 15:35 UTC
Just updated to the newest forge (1.7.10-10.13.3.1395-1710ls) and it looks like it's messing with texture loading:
![screen shot 2015-04-25 at 12 31 01](https://cloud.githubusercontent.com/assets/5294529/7333484/5b759d00-eb47-11e4-8fcd-41a7d46f8bcd.png)

It didn't happen before, and it seems to affect different textures each time I load the game (or if I have different mods loaded), the screenshot was taken with no mods loaded.

**Comment by ganymedes01** [comment] 2015-04-25 15:37
In case it's relevant:

I'm running OS X 10.10.3
I have two video cards:
-Intel HD Graphics 4000
-NVIDIA GeForce GT 650M

**Comment by RainWarrior** [comment] 2015-04-25 15:44
newest 1.7 or 1.8?

**Comment by Parker8283** [comment] 2015-04-25 16:28
Title says 1.7.10

**Comment by cpw** [comment] 2015-04-25 16:40
Please downgrade to 1387 and verify it doesn't happen there..

**Comment by ganymedes01** [comment] 2015-04-25 18:40
@RainWarrior Sorry, I forgot to add the forge version. it's 1.7.10-10.13.3.1395-1710ls

**Comment by ganymedes01** [comment] 2015-04-25 18:50
@cpw Reverted to 1387 and the issue is no longer present.

**Comment by ganymedes01** [comment] 2015-04-25 18:52
I also noticed it affects modded items as well as vanilla ones. But not all of them, I can't notice any logic behind which items fail and which don't.

It doesn't affect block icon. Those all seem to work correctly.

**Comment by ganymedes01** [comment] 2015-04-25 19:00
I realised I was on java 8, so I decided to go back to 7 to see if anything changed, this is what it looks like now:
![screen shot 2015-04-25 at 15 59 22](https://cloud.githubusercontent.com/assets/5294529/7334236/30c392fc-eb64-11e4-816d-6ee1f4f7ded7.png)

**Comment by RainWarrior** [comment] 2015-04-25 19:10
Can you please post your full fml log?

**Comment by ganymedes01** [comment] 2015-04-25 19:13
That's the "fml-client-latest.log" one, right?

**Comment by RainWarrior** [comment] 2015-04-25 19:26
yup

**Comment by RainWarrior** [comment] 2015-04-25 22:01
Hmm. You have ExampleMod loaded, but I assume it's the default one shipped with FG, and you don't actually do anything in there?
Can you also try refreshing resources after waiting a few seconds, and tell if it changes anything?

**Comment by JDLogic** [comment] 2015-04-26 00:51
I have the same problem and computer specs as gany. It looks like the problem was introduce at forge build 1389-1710ls. Doing a resource reload (f3+t) fixes the missing textures until the game is relaunched.

**Comment by cpw** [comment] 2015-04-26 01:28
@fry possible this is the driver issue manifesting? To the submitters, try setting enabled to false in the splash.properties file.. You might need latest forge to do that..

**Comment by ganymedes01** [comment] 2015-04-26 03:39
@RainWarrior Yeah I haven't touched the ExampleMod (never use it)

**Comment by ganymedes01** [comment] 2015-04-26 03:50
@cpw I found a splash.properties file in build/tmp/recompSrc/assets/fml but editing doesn't seem to have any effect. There is also one inside the forgeSrc jar, is that the one I need to edit?

**Comment by LexManos** [comment] 2015-04-26 04:21
Its a config file, in the config folder -.-

**Comment by ganymedes01** [comment] 2015-04-26 04:38
This is all I've got in my config folder:
![screen shot 2015-04-26 at 01 37 10](https://cloud.githubusercontent.com/assets/5294529/7335902/ec278076-ebb4-11e4-931e-abaeb1155e07.png)

**Comment by LexManos** [comment] 2015-04-26 05:54
Bah, Fry didnt update the Forge build with his commits to FML.
https://gist.github.com/LexManos/3c700306331080598daf
Toss that into your workspace and upload the images it generates.

**Comment by ganymedes01** [comment] 2015-04-26 16:10
Got 6 images:
![textures_blocks_0](https://cloud.githubusercontent.com/assets/5294529/7338038/7e1a5a48-ec15-11e4-86b8-254bd514474b.png)
![textures_blocks_1](https://cloud.githubusercontent.com/assets/5294529/7338037/7e1744b6-ec15-11e4-839a-7528076b6060.png)
![textures_blocks_2](https://cloud.githubusercontent.com/assets/5294529/7338041/7e1c3b6a-ec15-11e4-8123-e0070806cc89.png)
![textures_blocks_3](https://cloud.githubusercontent.com/assets/5294529/7338042/7e1d5f86-ec15-11e4-8239-84568b538c90.png)
![textures_blocks_4](https://cloud.githubusercontent.com/assets/5294529/7338039/7e1ab740-ec15-11e4-8329-35940ca249d4.png)
![textures_items_0](https://cloud.githubusercontent.com/assets/5294529/7338040/7e1c105e-ec15-11e4-9162-1b3bd34cc8cb.png)

**Comment by ganymedes01** [comment] 2015-04-26 16:16
Doing that texture dump fixes the issue...

**Comment by parashep** [comment] 2015-04-26 19:55
same thing on build 1396. OS 10.10.1, NVIDIA GeForce 320M. resource reload does indeed fix the issue during play. no issue on Windows machine with integrated graphics, haven't tested on Windows with the NVIDIA card.

**Comment by JDLogic** [comment] 2015-04-26 20:31
I ran forge (1395-1710ls) once with the new splash screen disabled (as cpw suggested) and now the textures load properly every time with the splash screen enabled. I tried to reproduce this issue by setting up a new forge environment and have been unsuccessful.

**Comment by LexManos** [comment] 2015-04-26 20:33
Interesting, something is putting your desktop or *something* onto those textures... They shouldn't have any of that text or folder icons.

**Comment by ganymedes01** [comment] 2015-04-26 23:30
I've noticed that my desktop shows up on the stitched textures even in vanilla. If you notice the desktop is only in the areas that are not being occupied by actual textures, so they don't get in the way.
The issue here is that something is messing up the mapping of each texture causing the desktop to be rendered in-game.

**Comment by ganymedes01** [comment] 2015-04-26 23:36
Since doing the texture dump fixed the issue, I tried narrowing down which GL call was "fixing" it.
```JAVA
GL11.glGetTexImage(GL11.GL_TEXTURE_2D, level, GL12.GL_BGRA, GL12.GL_UNSIGNED_INT_8_8_8_8_REV, buffer);
```
Commenting out the line above causes the issue to not be fixed. So wtv that does (my GL knowledge is weak) is fixing it lol

**Comment by ganymedes01** [comment] 2015-04-26 23:37
I have windows on a partition on my laptop. I can try running it on it to see if the issue is OSX exclusive...
Just let me know if you want it done.

**Comment by cpw** [comment] 2015-04-26 23:56
Fascinating. I wonder what causes the texture allocation to jumble up. Perhaps some mod in your system is trying to be clever and is derping up the stitch process, but that seems very unlikely..

The get texture method seems to be fixing it, right?

**Comment by LexManos** [comment] 2015-04-26 23:59
The call does nothing but read memory from the GPU.
It takes a bit of time, which might be enough for another thread to stop derping or something.
However the is no reason your desktop show be showing up in this at all. You have *something* wrong with your graphics card. Drivers maybe fubar?

**Comment by ganymedes01** [comment] 2015-04-27 00:00
@cpw There are not mods in the system apart from the example mod (which I haven't touched)
And yeah the get texture method fixes it.

**Comment by ganymedes01** [comment] 2015-04-27 00:04
@LexManos I haven't touched anything related to drivers. I noticed there's an update to OS X I haven't installed yet. I'll download it (which will take a while) and see if the problem persists.

**Comment by parashep** [comment] 2015-04-27 00:24
I don't think that a driver issue would be the problem given that it *is* happening with multiple people and only on new versions of Forge. Given that Apple supplies the drivers if there was an issue with the driver, many many people would be affected in the future ;)

**Comment by ganymedes01** [comment] 2015-04-27 00:27
I think if it was a driver problem I'd be seeing similar issues in other applications not only modded minecraft.

**Comment by LexManos** [comment] 2015-04-27 00:47
It could be a specific driver issue and it could be a specific piece of hardware issue there are a lot of factors that come into play.
SOMETHING is causing your atlase's to contain your desktop.
Forge {or well Minecraft} does not copy your desktop buffer from anywhere.
What it DOES is tell your GPU 'hey you have a texture here, copy it to this section of this other texture'
Not many games do that whole stitching process. So it wouldn't necessarily be evident in other games.
Best to go through and find common denominators, and see if it can be tracked down and fixed.

**Comment by cpw** [comment] 2015-04-27 00:50
It has been seen on the same hardware twice. It doesn't rule out a driver issue. Lex, the display uses textures to draw the desktop. It could be just a non-zero texture.. Perhaps the desktop thinks the gltex is available for a short period?

**Comment by parashep** [comment] 2015-04-29 00:18
same thing on an ATI Radeon HD 2600 Pro as well as my GeForce 320M :)
*there's* 3 different cards from 2 different manufacturers.

**Comment by cpw** [comment] 2015-04-29 00:19
Mac?

**Comment by parashep** [comment] 2015-04-29 00:20
yeah, that was meant as a follow-up to my previous comment from a few days ago. Mac of course.

**Comment by cpw** [comment] 2015-04-29 00:39
I'm suspecting some sort of race condition with the desktop, due to the threading.

**Comment by ganymedes01** [comment] 2015-04-29 00:56
It's what sounds more likely to me too

**Comment by parashep** [comment] 2015-04-29 05:27
in both cases I've experienced, unrelated items can also appear as part of the item graphic, often flashing between the correct item and another item

**Comment by fkaa** [comment] 2015-05-03 17:04
Does not occur for me with Intel HD 4000 on 10.10.2 (1389-1710ls). I believe the discrepancies between drivers tested are in how they handle undefined behaviour.

In `net.minecraft.client.render.TextureMap` the implementation for uploading the sprites to the driver is a bit wonky. Right after it updates the progress with `"Allocating GL texture"`, it calls:
```java
TextureUtil.allocateTextureImpl(this.getGlTextureId(), ...)
```
Now, there are two weird things going on here. Firstly, `TextureMap` extends `AbstractTexture`, which defines the following:
```java
protected int glTextureId = -1;

public int getGlTextureId() {
    if (this.glTextureId == -1) {
        this.glTextureId = TextureUtil.glGenTextures();
    }
    return this.glTextureId;
}

public void deleteGlTexture() {
    if (this.glTextureId != -1) {
        TextureUtil.deleteTexture(this.glTextureId);
        this.glTextureId = -1;
    }
}
```
Now this is fine on its own, this means `TextureMap` will manage its own texture object internally (`glTextureId` is not accessible from the outside). So far, we've passed our newly created texture object to the "allocation" method. If we look inside, we can totally understand what's going on:
```java
public static void deleteTexture(int p_147942_0_) {
    GL11.glDeleteTextures(p_147942_0_);
}

static void bindTexture(int p_94277_0_) {
    GL11.glBindTexture(GL11.GL_TEXTURE_2D, p_94277_0_);
}

public static void allocateTextureImpl(int p_147946_0_, int p_147946_1_, int p_147946_2_, int p_147946_3_, float p_147946_4_) {
    deleteTexture(p_147946_0_);
    bindTexture(p_147946_0_);

    if (OpenGlHelper.anisotropicFilteringSupported) {
        GL11.glTexParameterf(GL11.GL_TEXTURE_2D, 34046, p_147946_4_);
    }

    if (p_147946_1_ > 0) {
        GL11.glTexParameteri(GL11.GL_TEXTURE_2D, GL12.GL_TEXTURE_MAX_LEVEL, p_147946_1_);
        GL11.glTexParameterf(GL11.GL_TEXTURE_2D, GL12.GL_TEXTURE_MIN_LOD, 0.0F);
        GL11.glTexParameterf(GL11.GL_TEXTURE_2D, GL12.GL_TEXTURE_MAX_LOD, (float) p_147946_1_);
        GL11.glTexParameterf(GL11.GL_TEXTURE_2D, GL14.GL_TEXTURE_LOD_BIAS, 0.0F);
    }

    for (int i1 = 0; i1 <= p_147946_1_; ++i1) {
        GL11.glTexImage2D(GL11.GL_TEXTURE_2D, i1, GL11.GL_RGBA, p_147946_2_ >> i1, p_147946_3_ >> i1, 0, GL12.GL_BGRA, GL12.GL_UNSIGNED_INT_8_8_8_8_REV, (IntBuffer)null);
    }
}
```
So no we've deleted our newly created texture object, bound the now non-existant object to our target, `GL_TEXTURE_2D`, and finally, we're reserving enough space to hold all the sprites. wat?

Performing texture operations on invalid texture objects (in this case, non-existant) is undefined behavior, and I have no idea why this runs in the first place. Possible explanation could be that some drivers operate as if the handle was never deleted, and then when `this.getGlTextureId()` is called again, it happens to be before any other texture objects were created and it takes ownership over the previous object.

**Comment by cpw** [comment] 2015-05-03 17:33
Interesting observations. @rainwarrior would you care to comment? Does this flow look a bit derped to you?

**Comment by fkaa** [comment] 2015-05-03 17:35
@cpw: I had some discussions with grum and @RainWarrior about this. This is related to `glGenTextures()` being called in another thread while the deleted object is marked as available.

**Comment by fkaa** [comment] 2015-05-03 17:38
Additionally I had some misconceptions about how texture objects worked. `glBindTexture()` takes ownership of the object, rather then `glGenTextures()`, which only provides a unused object. So effectively the delete, bind was a hint to the driver to release data.

**Comment by LexManos** [comment] 2015-05-03 20:41
What is the proposed solution, also, why is another thread touching these textures at all? Nothing should be moved to the new loading thread.

**Comment by RainWarrior** [comment] 2015-05-04 19:42
Please try build 1401, and tell if it fixes this issue.

**Comment by ganymedes01** [comment] 2015-05-04 19:54
Nope, same problem.
(Animated forge icon looks rather cool btw! But I think it could use some scaling down. It's blocking the text a bit)

**Comment by bdew** [comment] 2015-05-21 09:15
FWIW i'm getting the same issue running in dev environment on an iMac with NVIDIA GeForce GT 750M, OSX 10.10.3, running forge 10.13.3.1408.

It was not happening with Forge 10.13.2. Turning the new load screen off fixes this as well.

**Comment by clienthax** [comment] 2015-08-09 01:03
Reproducible on 1.8 latest on the same card, got to be a driver issue.

**Comment by Eternaldoom** [comment] 2015-08-10 18:52
Doesn't occur for me with a GTX 960 using NVIDIA Web Drivers (Mac OS 10.10.4).

**Comment by lazandrei19** [comment] 2015-08-12 15:26
Occurs to me with the splash screen turned on. Mac OS X 10.10.3, GTX 780 Ti, forge 1450. Gone after turning the splash screen off

**Comment by yiweig** [comment] 2015-08-20 04:11
OS X 10.10.5
NVIDIA GeForce GT 750M 2048 MB
Minecraft 1.8.8
Forge 11.14.3.1450

Still occuring. But F3 + T does fix it for the current game only.

**Comment by yiweig** [comment] 2015-08-20 17:44
![screen shot 2015-08-20 at 10 42 03](https://cloud.githubusercontent.com/assets/6099687/9390813/55bae9b4-4728-11e5-9d16-a606cb2342d0.png)

For reference, this is what I see

**Comment by yiweig** [comment] 2015-08-20 17:46
I went ahead and disabled the Forge splash screen (`enabled=false` in `splash.properties`) and I no longer have the texture issues. But if I re-enable the splash screen the issues return.

**Comment by LexManos** [comment] 2015-08-21 21:27
Yes, because you have a shitty mac that has broken drivers that don't follow standards of not overwriting textures it is told that are still in use!
Either way, just disable the loading screen and you're done.
This thread is done. Macs suck, once Abrar fixed Forge's build server I will default Macs to have the loading screen disabled because im sick of seeing this.

**Closed by LexManos** 2015-08-21 21:27 UTC

**Comment by parashep** [comment] 2015-08-21 21:38
wow, nice team this sure is

**Comment by yiweig** [comment] 2015-08-21 22:05
For the record, this isn't in the EAQs.

**Comment by ganymedes01** [comment] 2015-08-21 22:36
Well.. after some searching I found a person that was having the same issue, was able to fix it, and explained how.
Here's the link to how he fixed it, it seems like it was a trivial solution (and something he was doing wrong, not a OS X...)
http://itquestionz.com/questions/1740274/random-pieces-of-screen-are-being-rendered-opengl-what-error-does-this-indicate

I hope it helps...

**Comment by diesieben07** [comment] 2015-08-21 22:40
| For the record, this isn't in the EAQs.

**Comment by diesieben07** [comment] 2015-08-21 22:40
> For the record, this isn't in the EAQs.

For the record, it is.

**Comment by yiweig** [comment] 2015-08-21 23:00
Could you link it?

The EAQs say to disable the splash screen if your text is distorted, I couldn't find anything about item textures.

**Comment by diesieben07** [comment] 2015-08-22 00:16
Well, that's what I meant. I figured people might use their brains for a change.

**Comment by parashep** [comment] 2015-08-22 00:23
Extremely presumptuous that people would see the other issue and assume it has the same cause, because they look totally different. Not to mention that forge is very popular with kids and other people who aren't necessarily proficient with technology. I would really recommend adding it as a separate known issue.

**Comment by BlakeDarwinXE** [comment] 2015-10-23 14:16
For any other Mac user here is what I changed. The thread able is way to long, and filled with unhelpful comments.

In your config folder there is a hidden file called splash.properties.
Change:
```
enabled=true
```

To
```
enabled=false
```
