### ISSUE TITLE
IllegalReferenceCountException on player join

### ISSUE THREAD

**Issue by LXGaming** [MinecraftForge/MinecraftForge#4533] opened 2017-11-19 02:03 UTC
Running Forge 14.23.0.2546 (1.12.2)

I'm unsure if this is an issue with Forge or the mod everlastingabilities.

Error: https://pastebin.com/fAsHVFyU

**Comment by liach** [comment] 2017-11-19 03:45
@LXGaming Close this, report to the mod author first.

**Comment by williewillus** [comment] 2017-11-19 07:16
duplicate of #4523 , update to 2543+ to fix it

**Comment by liach** [comment] 2017-11-19 07:18
> Running Forge 14.23.0.2546

@williewillus

**Comment by bs2609** [comment] 2017-11-19 07:34
See https://github.com/CyclopsMC/CyclopsCore/pull/94.

**Closed as completed** 2017-11-19 22:36 UTC
