### ISSUE TITLE
[1.16.1] Seaking in water acts as if holding jump

### ISSUE THREAD

**Issue by tehbiga** [MinecraftForge/MinecraftForge#6826] opened 2020-06-26 10:53 UTC
**Minecraft Version:** `1.16.1`

**Forge Version:** `32.0.7`

**Steps to Reproduce:**
 1. Start Minecraft 1.16.1 world with forge 32.0.7 _(No mods)_
 2. Find water and try to swim
 3. Press _Sneak_

**Description of issue:**
Decided to start checking out Forge for 1.16.1 today and happen to spawn in a small island in an ocean.
I went to swim to another island but when I tried to sprint-swim I realized I was moving very slowly and sneaking caused me to raise up to the surface instead of swim downward.

I launched vanilla 1.16.1 without forge and did not have this issue.

**Extra notes:**
I used GDLauncher to create this instance since the Twitch app is wildly behind again.

**Comment by TheCurle** [comment] 2020-06-26 10:54
Duplicate of #6817

**Closed as completed by TheCurle** 2020-06-26 10:54 UTC
Labels: Bug, Fluids, 1.16

**Comment by tehbiga** [comment] 2020-06-26 11:16
Ah didn't think to check pull requests, my bad!

**Comment by TheCurle** [comment] 2020-06-26 11:17
No worries. It's a pretty silly bug, so it'll be fixed in the next round of pulls.
