### ISSUE TITLE
[31.2.0+] Mouse position shifted in menus under wayland

### ISSUE THREAD

**Issue by jvanbruegge** [MinecraftForge/MinecraftForge#7334] opened 2020-09-17 13:34 UTC
**Minecraft Version:** 1.15.2, 1.16.3

**Forge Version:** 31.2.0, 34.0.7 - does **not** happen with 31.1.0

**Logs:** [latest.log](https://gist.github.com/jvanbruegge/d8eb7e399020d42f1f922b1f9e4dd1f1)

**Steps to Reproduce:**
 1. Use the sway desktop under Linux
 2. Get to the main menu
 3. Try to press a button

**Description of issue:**
When starting Minecraft, the FML early loading does not happen in a small floating window, but in a full normal window. Then when you get to the main menu, I need to have the mouse just below the right side of the M of the Minecraft title string to hit the singleplayer button. Same happens for forge 34.0.7 for Minecraft 1.16.3.
This bug apparently was introduced after 31.1.0, because I have no problems with that version

**Comment by cpw** [comment] 2020-09-18 13:36
This sounds like an incompatibility between LWJGL and wayland. We don't do anything special with the "mouse position" logic at all. Most likely, the problem is that wayland is not properly reporting window decoration data to LWJGL, so the data isn't properly offset. This could be your window manager as well (since that's responsible for decoration, typically).

I'm going to close this as "not reproducible" and certainly "not something we can fix". Sadly, I don't have a wayland compatible graphics setup, to try and reproduce this.

**Closed as completed by cpw** 2020-09-18 13:36 UTC

**Comment by jvanbruegge** [comment] 2020-09-18 13:39
But does the lwjgl version change between forge versions?
Because minecraft 1.15.2 with forge 31.1.0 works, while the same 1.15.2 with forge 31.2.0 does not work.
I assumed lwjgl is tied to minecraft, not forge

**Comment by malte0811** [comment] 2020-09-18 13:46
I've seen something similar happen when resizing the "early startup" window under XFCE4. Un- and re-resizing the window fixes it in that case. Not sure whether it's the same issue, at least it's similar.

**Comment by cpw** [comment] 2020-09-18 14:08
It's a decoration problem, and there's probably something wrong with how LWJGL is receiving the data. If a resize fixes it, it's been an X issue since, oh, about 1998.

> Does lwjgl version change?

Not by forge, no, but certainly, minecraft regularly revises their LWJGL version.

**Comment by jvanbruegge** [comment] 2020-09-18 14:39
Then i doubt lwjgl is at fault here, because running development version with 31.1.0 and then just (and only) change the forge version number in the build.grade makes this appear

**Comment by XFactHD** [comment] 2020-09-18 14:47
There where a lot of changes/fixes related to the early loading screen (AFAIK it uses a lot of LWJGL stuff directly) between 31.1.0 and 31.2.0, you could try doing a binary search for the exact version that "broke" it

**Comment by jvanbruegge** [comment] 2020-09-18 14:48
Yeah, i wanted to a bisec tomorrow when I got time

**Comment by TheCurle** [comment] 2020-09-18 14:49
I suggest looking at 31.1.51 and 31.1.62. Those are the only updates that mention the early progress window in their changelogs.

**Comment by cpw** [comment] 2020-09-18 17:11
good luck. I cannot reproduce in any way, and I highly suspect a problem with your X/wayland setup.

**Comment by jaredlll08** [comment] 2020-09-27 05:38
Just going to put it out there, I can reliably reproduce this on a semi fresh Ubuntu 20.04.

I don't believe I've changed any desktop environment / window manager related settings, and I am 95% sure that I was running into the same issue on Manjaro with KDE Plasma, I don't have that system setup anymore to test though.

The trick to reproduce is to make the early loading screen full screen.

https://blamejared.com/forge_7334.gif

This is with forge `1.16.3-34.0.9`

**Comment by jvanbruegge** [comment] 2020-10-05 09:12
I just confirmed that this is fixed in HEAD. Now I will try the latest 1.16.3 release.

**Comment by jvanbruegge** [comment] 2020-10-05 10:08
This is weird. It works if I run forge_client from idea, but using the latest version for my own mod does not

**Comment by jvanbruegge** [comment] 2020-10-05 10:21
I strongly supect this commit to be the origin of the issue: https://github.com/MinecraftForge/MinecraftForge/commit/438c969fefbec86bcb8d512cf8e1e508f3b774d4
Probably something about the window handover, because the early loading window is not resizeable and as sway is a tiling window manager it then immediatly makes the window full screen
