### ISSUE TITLE
Chat Misaligned From Vanilla Position + Tooltips

### ISSUE THREAD

**Issue by yurisuika** [MinecraftForge/MinecraftForge#9205] opened 2022-12-11 14:08 UTC
**Minecraft Version:** 1.19.3

**Forge Version:** 44.0.6

**Description of issue:**
The vanilla chat position is aligned with the armor icons.

![image](https://user-images.githubusercontent.com/7410303/206904062-f04eb569-2c16-4e4e-83de-6783c74282d2.png)

Forge 44.0.x is pushing it up by 8 pixels, which is not even the full 9 pixels of a chat line height.

![image](https://user-images.githubusercontent.com/7410303/206904393-5be74f86-8f44-4cf9-a32e-6a846f7d3353.png)

This also has the side affect of misaligning the chat from the tooltips positioned by `screenToChatY`. You might not see the cursor, but you can see this is rendering far too low.

![image](https://user-images.githubusercontent.com/7410303/206904470-950beebf-c0d8-4f5d-adaa-86ee5e645344.png)

PR #9184 attempts to fix this by adding 8 to the height for `CustomizeGuiOverlayEvent.Chat` in `renderChat`, but I cannot say if this is the proper way to go about it, as it seems to have had the value of `48` for a while. This issue was not present in 1.19.2 as of 43.2.0 and earlier, but is present starting in 44.0.0.

Instead, I do believe the proper way to fix this is to modify the `translate` in `renderChat`. I see this is taken from the changes regarding chat in the vanilla GUI. Instead of it being `pStack.translate(event.getPosX(), (event.getPosY() - height + 40) / chat.getScale(), 0.0D);`, it should be `pStack.translate(event.getPosX(), (event.getPosY() - height + 48) / chat.getScale(), 0.0D);`

**Comment by sciwhiz12** [comment] 2022-12-11 16:09
Fixed by #9184. 

Looking at the code in 1.19.2, the constant `48` is taken from `Gui#render`, from the `PoseStack#translate` call before the call to `ChatComponent#render`: `p_93031_.translate(0.0D, (double)(this.screenHeight - 48), 0.0D);`. `this.screenHeight - 48` is passed to `CustomizeGuiOverlayEvent.Chat` as the `posY`, which is then later used as the second value to a `PoseStack#translate` call in `ForgeGui#renderChat`.

In 1.19.3, alongside other changes, the constant (or at least its nearest equivalent, which seems to be the constant in `Mth.floor((float)(l - 40) / f)` in `ChatComponent#render`) changed from `48` to `40`, possibly due to the removal of the chat preview feature (though that is speculation on my part, without digging further into this).

Regardless, the issue is fixed, and I can find no visual differences between vanilla and the fix introduced by the PR.

**Closed as completed by sciwhiz12** 2022-12-11 16:09 UTC
Labels: Bug, Confirmed, Rendering, 1.19
